/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  BodyUploadAudio,
  HTTPValidationError
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type uploadAudioResponse200 = {
  data: unknown
  status: 200
}

export type uploadAudioResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type uploadAudioResponseSuccess = (uploadAudioResponse200) & {
  headers: Headers;
};
export type uploadAudioResponseError = (uploadAudioResponse422) & {
  headers: Headers;
};

export type uploadAudioResponse = (uploadAudioResponseSuccess | uploadAudioResponseError)

export const getUploadAudioUrl = (cid: number,) => {




  return `/consultations/${cid}/audio`
}

/**
 * @summary Upload Audio
 */
export const uploadAudio = async (cid: number,
    bodyUploadAudio: BodyUploadAudio, options?: RequestInit): Promise<uploadAudioResponse> => {
    const formData = new FormData();
formData.append(`file`, bodyUploadAudio.file);
if(bodyUploadAudio.language !== undefined) {
 formData.append(`language`, bodyUploadAudio.language);
 }
if(bodyUploadAudio.speaker !== undefined) {
 formData.append(`speaker`, bodyUploadAudio.speaker);
 }

  return mutator<uploadAudioResponse>(getUploadAudioUrl(cid),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}




export const getUploadAudioMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAudio>>, TError,{cid: number;data: BodyType<BodyUploadAudio>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadAudio>>, TError,{cid: number;data: BodyType<BodyUploadAudio>}, TContext> => {

const mutationKey = ['uploadAudio'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadAudio>>, {cid: number;data: BodyType<BodyUploadAudio>}> = (props) => {
          const {cid,data} = props ?? {};

          return  uploadAudio(cid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadAudioMutationResult = NonNullable<Awaited<ReturnType<typeof uploadAudio>>>
    export type UploadAudioMutationBody = BodyType<BodyUploadAudio>
    export type UploadAudioMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Upload Audio
 */
export const useUploadAudio = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAudio>>, TError,{cid: number;data: BodyType<BodyUploadAudio>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadAudio>>,
        TError,
        {cid: number;data: BodyType<BodyUploadAudio>},
        TContext
      > => {
      return useMutation(getUploadAudioMutationOptions(options), queryClient);
    }
