/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType } from '../api/sdk-mutator';





export type createConsultationResponse200 = {
  data: unknown
  status: 200
}

export type createConsultationResponseSuccess = (createConsultationResponse200) & {
  headers: Headers;
};
;

export type createConsultationResponse = (createConsultationResponseSuccess)

export const getCreateConsultationUrl = () => {




  return `/consultations`
}

/**
 * @summary Create Consultation
 */
export const createConsultation = async ( options?: RequestInit): Promise<createConsultationResponse> => {

  return mutator<createConsultationResponse>(getCreateConsultationUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getCreateConsultationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createConsultation>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createConsultation>>, TError,void, TContext> => {

const mutationKey = ['createConsultation'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createConsultation>>, void> = () => {


          return  createConsultation()
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateConsultationMutationResult = NonNullable<Awaited<ReturnType<typeof createConsultation>>>

    export type CreateConsultationMutationError = ErrorType<unknown>

    /**
 * @summary Create Consultation
 */
export const useCreateConsultation = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createConsultation>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createConsultation>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getCreateConsultationMutationOptions(options), queryClient);
    }
