/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ConsultationIn,
  HTTPValidationError
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type createConsultationResponse200 = {
  data: unknown
  status: 200
}

export type createConsultationResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createConsultationResponseSuccess = (createConsultationResponse200) & {
  headers: Headers;
};
export type createConsultationResponseError = (createConsultationResponse422) & {
  headers: Headers;
};

export type createConsultationResponse = (createConsultationResponseSuccess | createConsultationResponseError)

export const getCreateConsultationUrl = () => {




  return `/consultations`
}

/**
 * @summary Create Consultation
 */
export const createConsultation = async (consultationInNull?: ConsultationIn | null, options?: RequestInit): Promise<createConsultationResponse> => {

  return mutator<createConsultationResponse>(getCreateConsultationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(consultationInNull)
  }
);}




export const getCreateConsultationMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createConsultation>>, TError,{data?: BodyType<ConsultationIn | null>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createConsultation>>, TError,{data?: BodyType<ConsultationIn | null>}, TContext> => {

const mutationKey = ['createConsultation'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createConsultation>>, {data?: BodyType<ConsultationIn | null>}> = (props) => {
          const {data} = props ?? {};

          return  createConsultation(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateConsultationMutationResult = NonNullable<Awaited<ReturnType<typeof createConsultation>>>
    export type CreateConsultationMutationBody = BodyType<ConsultationIn | null> | undefined
    export type CreateConsultationMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Consultation
 */
export const useCreateConsultation = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createConsultation>>, TError,{data?: BodyType<ConsultationIn | null>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createConsultation>>,
        TError,
        {data?: BodyType<ConsultationIn | null>},
        TContext
      > => {
      return useMutation(getCreateConsultationMutationOptions(options), queryClient);
    }
