/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyUploadJihvaPhoto,
  ExaminationIn,
  HTTPValidationError
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type parikshaSchemaResponse200 = {
  data: unknown
  status: 200
}

export type parikshaSchemaResponseSuccess = (parikshaSchemaResponse200) & {
  headers: Headers;
};
;

export type parikshaSchemaResponse = (parikshaSchemaResponseSuccess)

export const getParikshaSchemaUrl = () => {




  return `/pariksha/schema`
}

/**
 * @summary Pariksha Schema
 */
export const parikshaSchema = async ( options?: RequestInit): Promise<parikshaSchemaResponse> => {

  return mutator<parikshaSchemaResponse>(getParikshaSchemaUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getParikshaSchemaQueryKey = () => {
    return [
    `/pariksha/schema`
    ] as const;
    }


export const getParikshaSchemaQueryOptions = <TData = Awaited<ReturnType<typeof parikshaSchema>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof parikshaSchema>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getParikshaSchemaQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof parikshaSchema>>> = ({ signal }) => parikshaSchema({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof parikshaSchema>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ParikshaSchemaQueryResult = NonNullable<Awaited<ReturnType<typeof parikshaSchema>>>
export type ParikshaSchemaQueryError = ErrorType<unknown>


export function useParikshaSchema<TData = Awaited<ReturnType<typeof parikshaSchema>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof parikshaSchema>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof parikshaSchema>>,
          TError,
          Awaited<ReturnType<typeof parikshaSchema>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useParikshaSchema<TData = Awaited<ReturnType<typeof parikshaSchema>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof parikshaSchema>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof parikshaSchema>>,
          TError,
          Awaited<ReturnType<typeof parikshaSchema>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useParikshaSchema<TData = Awaited<ReturnType<typeof parikshaSchema>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof parikshaSchema>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Pariksha Schema
 */

export function useParikshaSchema<TData = Awaited<ReturnType<typeof parikshaSchema>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof parikshaSchema>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getParikshaSchemaQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type saveExaminationResponse200 = {
  data: unknown
  status: 200
}

export type saveExaminationResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type saveExaminationResponseSuccess = (saveExaminationResponse200) & {
  headers: Headers;
};
export type saveExaminationResponseError = (saveExaminationResponse422) & {
  headers: Headers;
};

export type saveExaminationResponse = (saveExaminationResponseSuccess | saveExaminationResponseError)

export const getSaveExaminationUrl = (cid: number,) => {




  return `/consultations/${cid}/examination`
}

/**
 * @summary Save Examination
 */
export const saveExamination = async (cid: number,
    examinationIn: ExaminationIn, options?: RequestInit): Promise<saveExaminationResponse> => {

  return mutator<saveExaminationResponse>(getSaveExaminationUrl(cid),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(examinationIn)
  }
);}




export const getSaveExaminationMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveExamination>>, TError,{cid: number;data: BodyType<ExaminationIn>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof saveExamination>>, TError,{cid: number;data: BodyType<ExaminationIn>}, TContext> => {

const mutationKey = ['saveExamination'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof saveExamination>>, {cid: number;data: BodyType<ExaminationIn>}> = (props) => {
          const {cid,data} = props ?? {};

          return  saveExamination(cid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SaveExaminationMutationResult = NonNullable<Awaited<ReturnType<typeof saveExamination>>>
    export type SaveExaminationMutationBody = BodyType<ExaminationIn>
    export type SaveExaminationMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Save Examination
 */
export const useSaveExamination = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveExamination>>, TError,{cid: number;data: BodyType<ExaminationIn>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof saveExamination>>,
        TError,
        {cid: number;data: BodyType<ExaminationIn>},
        TContext
      > => {
      return useMutation(getSaveExaminationMutationOptions(options), queryClient);
    }
    export type getExaminationResponse200 = {
  data: unknown
  status: 200
}

export type getExaminationResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getExaminationResponseSuccess = (getExaminationResponse200) & {
  headers: Headers;
};
export type getExaminationResponseError = (getExaminationResponse422) & {
  headers: Headers;
};

export type getExaminationResponse = (getExaminationResponseSuccess | getExaminationResponseError)

export const getGetExaminationUrl = (cid: number,) => {




  return `/consultations/${cid}/examination`
}

/**
 * @summary Get Examination
 */
export const getExamination = async (cid: number, options?: RequestInit): Promise<getExaminationResponse> => {

  return mutator<getExaminationResponse>(getGetExaminationUrl(cid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetExaminationQueryKey = (cid: number,) => {
    return [
    `/consultations/${cid}/examination`
    ] as const;
    }


export const getGetExaminationQueryOptions = <TData = Awaited<ReturnType<typeof getExamination>>, TError = ErrorType<HTTPValidationError>>(cid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExamination>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetExaminationQueryKey(cid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getExamination>>> = ({ signal }) => getExamination(cid, { signal });





   return  { queryKey, queryFn, enabled: cid !== null && cid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getExamination>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetExaminationQueryResult = NonNullable<Awaited<ReturnType<typeof getExamination>>>
export type GetExaminationQueryError = ErrorType<HTTPValidationError>


export function useGetExamination<TData = Awaited<ReturnType<typeof getExamination>>, TError = ErrorType<HTTPValidationError>>(
 cid: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExamination>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExamination>>,
          TError,
          Awaited<ReturnType<typeof getExamination>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExamination<TData = Awaited<ReturnType<typeof getExamination>>, TError = ErrorType<HTTPValidationError>>(
 cid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExamination>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExamination>>,
          TError,
          Awaited<ReturnType<typeof getExamination>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExamination<TData = Awaited<ReturnType<typeof getExamination>>, TError = ErrorType<HTTPValidationError>>(
 cid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExamination>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Examination
 */

export function useGetExamination<TData = Awaited<ReturnType<typeof getExamination>>, TError = ErrorType<HTTPValidationError>>(
 cid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExamination>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetExaminationQueryOptions(cid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type uploadJihvaPhotoResponse200 = {
  data: unknown
  status: 200
}

export type uploadJihvaPhotoResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type uploadJihvaPhotoResponseSuccess = (uploadJihvaPhotoResponse200) & {
  headers: Headers;
};
export type uploadJihvaPhotoResponseError = (uploadJihvaPhotoResponse422) & {
  headers: Headers;
};

export type uploadJihvaPhotoResponse = (uploadJihvaPhotoResponseSuccess | uploadJihvaPhotoResponseError)

export const getUploadJihvaPhotoUrl = (cid: number,) => {




  return `/consultations/${cid}/examination/jihva-photo`
}

/**
 * @summary Upload Jihva Photo
 */
export const uploadJihvaPhoto = async (cid: number,
    bodyUploadJihvaPhoto: BodyUploadJihvaPhoto, options?: RequestInit): Promise<uploadJihvaPhotoResponse> => {
    const formData = new FormData();
formData.append(`file`, bodyUploadJihvaPhoto.file);
if(bodyUploadJihvaPhoto.consent !== undefined) {
 formData.append(`consent`, bodyUploadJihvaPhoto.consent.toString())
 }

  return mutator<uploadJihvaPhotoResponse>(getUploadJihvaPhotoUrl(cid),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}




export const getUploadJihvaPhotoMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadJihvaPhoto>>, TError,{cid: number;data: BodyType<BodyUploadJihvaPhoto>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadJihvaPhoto>>, TError,{cid: number;data: BodyType<BodyUploadJihvaPhoto>}, TContext> => {

const mutationKey = ['uploadJihvaPhoto'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadJihvaPhoto>>, {cid: number;data: BodyType<BodyUploadJihvaPhoto>}> = (props) => {
          const {cid,data} = props ?? {};

          return  uploadJihvaPhoto(cid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadJihvaPhotoMutationResult = NonNullable<Awaited<ReturnType<typeof uploadJihvaPhoto>>>
    export type UploadJihvaPhotoMutationBody = BodyType<BodyUploadJihvaPhoto>
    export type UploadJihvaPhotoMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Upload Jihva Photo
 */
export const useUploadJihvaPhoto = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadJihvaPhoto>>, TError,{cid: number;data: BodyType<BodyUploadJihvaPhoto>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadJihvaPhoto>>,
        TError,
        {cid: number;data: BodyType<BodyUploadJihvaPhoto>},
        TContext
      > => {
      return useMutation(getUploadJihvaPhotoMutationOptions(options), queryClient);
    }
