/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  PatientIn,
  PatientOut
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type patientsListResponse200 = {
  data: PatientOut[]
  status: 200
}

export type patientsListResponseSuccess = (patientsListResponse200) & {
  headers: Headers;
};
;

export type patientsListResponse = (patientsListResponseSuccess)

export const getPatientsListUrl = () => {




  return `/api/v1/patients`
}

/**
 * All patients, newest first. Search/filters are client-side (the list is small).
 * @summary Patients List
 */
export const patientsList = async ( options?: RequestInit): Promise<patientsListResponse> => {

  return mutator<patientsListResponse>(getPatientsListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPatientsListQueryKey = () => {
    return [
    `/api/v1/patients`
    ] as const;
    }


export const getPatientsListQueryOptions = <TData = Awaited<ReturnType<typeof patientsList>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patientsList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPatientsListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof patientsList>>> = ({ signal }) => patientsList({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof patientsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PatientsListQueryResult = NonNullable<Awaited<ReturnType<typeof patientsList>>>
export type PatientsListQueryError = ErrorType<unknown>


export function usePatientsList<TData = Awaited<ReturnType<typeof patientsList>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof patientsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patientsList>>,
          TError,
          Awaited<ReturnType<typeof patientsList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatientsList<TData = Awaited<ReturnType<typeof patientsList>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patientsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patientsList>>,
          TError,
          Awaited<ReturnType<typeof patientsList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatientsList<TData = Awaited<ReturnType<typeof patientsList>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patientsList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Patients List
 */

export function usePatientsList<TData = Awaited<ReturnType<typeof patientsList>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patientsList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPatientsListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type patientsCreateResponse201 = {
  data: PatientOut
  status: 201
}

export type patientsCreateResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type patientsCreateResponseSuccess = (patientsCreateResponse201) & {
  headers: Headers;
};
export type patientsCreateResponseError = (patientsCreateResponse422) & {
  headers: Headers;
};

export type patientsCreateResponse = (patientsCreateResponseSuccess | patientsCreateResponseError)

export const getPatientsCreateUrl = () => {




  return `/api/v1/patients`
}

/**
 * @summary Patients Create
 */
export const patientsCreate = async (patientIn: PatientIn, options?: RequestInit): Promise<patientsCreateResponse> => {

  return mutator<patientsCreateResponse>(getPatientsCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patientIn)
  }
);}




export const getPatientsCreateMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patientsCreate>>, TError,{data: BodyType<PatientIn>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patientsCreate>>, TError,{data: BodyType<PatientIn>}, TContext> => {

const mutationKey = ['patientsCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patientsCreate>>, {data: BodyType<PatientIn>}> = (props) => {
          const {data} = props ?? {};

          return  patientsCreate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatientsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof patientsCreate>>>
    export type PatientsCreateMutationBody = BodyType<PatientIn>
    export type PatientsCreateMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Patients Create
 */
export const usePatientsCreate = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patientsCreate>>, TError,{data: BodyType<PatientIn>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patientsCreate>>,
        TError,
        {data: BodyType<PatientIn>},
        TContext
      > => {
      return useMutation(getPatientsCreateMutationOptions(options), queryClient);
    }
    export type patientsRetrieveResponse200 = {
  data: PatientOut
  status: 200
}

export type patientsRetrieveResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type patientsRetrieveResponseSuccess = (patientsRetrieveResponse200) & {
  headers: Headers;
};
export type patientsRetrieveResponseError = (patientsRetrieveResponse422) & {
  headers: Headers;
};

export type patientsRetrieveResponse = (patientsRetrieveResponseSuccess | patientsRetrieveResponseError)

export const getPatientsRetrieveUrl = (patientId: string,) => {




  return `/api/v1/patients/${patientId}`
}

/**
 * @summary Patients Retrieve
 */
export const patientsRetrieve = async (patientId: string, options?: RequestInit): Promise<patientsRetrieveResponse> => {

  return mutator<patientsRetrieveResponse>(getPatientsRetrieveUrl(patientId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPatientsRetrieveQueryKey = (patientId: string,) => {
    return [
    `/api/v1/patients/${patientId}`
    ] as const;
    }


export const getPatientsRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof patientsRetrieve>>, TError = ErrorType<HTTPValidationError>>(patientId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patientsRetrieve>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPatientsRetrieveQueryKey(patientId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof patientsRetrieve>>> = ({ signal }) => patientsRetrieve(patientId, { signal });





   return  { queryKey, queryFn, enabled: patientId !== null && patientId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof patientsRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PatientsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof patientsRetrieve>>>
export type PatientsRetrieveQueryError = ErrorType<HTTPValidationError>


export function usePatientsRetrieve<TData = Awaited<ReturnType<typeof patientsRetrieve>>, TError = ErrorType<HTTPValidationError>>(
 patientId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof patientsRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patientsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof patientsRetrieve>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatientsRetrieve<TData = Awaited<ReturnType<typeof patientsRetrieve>>, TError = ErrorType<HTTPValidationError>>(
 patientId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patientsRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patientsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof patientsRetrieve>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatientsRetrieve<TData = Awaited<ReturnType<typeof patientsRetrieve>>, TError = ErrorType<HTTPValidationError>>(
 patientId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patientsRetrieve>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Patients Retrieve
 */

export function usePatientsRetrieve<TData = Awaited<ReturnType<typeof patientsRetrieve>>, TError = ErrorType<HTTPValidationError>>(
 patientId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patientsRetrieve>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPatientsRetrieveQueryOptions(patientId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type patientsUpdateResponse200 = {
  data: PatientOut
  status: 200
}

export type patientsUpdateResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type patientsUpdateResponseSuccess = (patientsUpdateResponse200) & {
  headers: Headers;
};
export type patientsUpdateResponseError = (patientsUpdateResponse422) & {
  headers: Headers;
};

export type patientsUpdateResponse = (patientsUpdateResponseSuccess | patientsUpdateResponseError)

export const getPatientsUpdateUrl = (patientId: string,) => {




  return `/api/v1/patients/${patientId}`
}

/**
 * @summary Patients Update
 */
export const patientsUpdate = async (patientId: string,
    patientIn: PatientIn, options?: RequestInit): Promise<patientsUpdateResponse> => {

  return mutator<patientsUpdateResponse>(getPatientsUpdateUrl(patientId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patientIn)
  }
);}




export const getPatientsUpdateMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patientsUpdate>>, TError,{patientId: string;data: BodyType<PatientIn>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patientsUpdate>>, TError,{patientId: string;data: BodyType<PatientIn>}, TContext> => {

const mutationKey = ['patientsUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patientsUpdate>>, {patientId: string;data: BodyType<PatientIn>}> = (props) => {
          const {patientId,data} = props ?? {};

          return  patientsUpdate(patientId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatientsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof patientsUpdate>>>
    export type PatientsUpdateMutationBody = BodyType<PatientIn>
    export type PatientsUpdateMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Patients Update
 */
export const usePatientsUpdate = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patientsUpdate>>, TError,{patientId: string;data: BodyType<PatientIn>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patientsUpdate>>,
        TError,
        {patientId: string;data: BodyType<PatientIn>},
        TContext
      > => {
      return useMutation(getPatientsUpdateMutationOptions(options), queryClient);
    }
    export type patientsDeleteResponse204 = {
  data: void
  status: 204
}

export type patientsDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type patientsDeleteResponseSuccess = (patientsDeleteResponse204) & {
  headers: Headers;
};
export type patientsDeleteResponseError = (patientsDeleteResponse422) & {
  headers: Headers;
};

export type patientsDeleteResponse = (patientsDeleteResponseSuccess | patientsDeleteResponseError)

export const getPatientsDeleteUrl = (patientId: string,) => {




  return `/api/v1/patients/${patientId}`
}

/**
 * @summary Patients Delete
 */
export const patientsDelete = async (patientId: string, options?: RequestInit): Promise<patientsDeleteResponse> => {

  return mutator<patientsDeleteResponse>(getPatientsDeleteUrl(patientId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getPatientsDeleteMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patientsDelete>>, TError,{patientId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patientsDelete>>, TError,{patientId: string}, TContext> => {

const mutationKey = ['patientsDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patientsDelete>>, {patientId: string}> = (props) => {
          const {patientId} = props ?? {};

          return  patientsDelete(patientId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatientsDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof patientsDelete>>>

    export type PatientsDeleteMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Patients Delete
 */
export const usePatientsDelete = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patientsDelete>>, TError,{patientId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patientsDelete>>,
        TError,
        {patientId: string},
        TContext
      > => {
      return useMutation(getPatientsDeleteMutationOptions(options), queryClient);
    }
