/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EditIn,
  HTTPValidationError
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type listTranscriptsResponse200 = {
  data: unknown
  status: 200
}

export type listTranscriptsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listTranscriptsResponseSuccess = (listTranscriptsResponse200) & {
  headers: Headers;
};
export type listTranscriptsResponseError = (listTranscriptsResponse422) & {
  headers: Headers;
};

export type listTranscriptsResponse = (listTranscriptsResponseSuccess | listTranscriptsResponseError)

export const getListTranscriptsUrl = (cid: number,) => {




  return `/consultations/${cid}/transcripts`
}

/**
 * @summary List Transcripts
 */
export const listTranscripts = async (cid: number, options?: RequestInit): Promise<listTranscriptsResponse> => {

  return mutator<listTranscriptsResponse>(getListTranscriptsUrl(cid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListTranscriptsQueryKey = (cid: number,) => {
    return [
    `/consultations/${cid}/transcripts`
    ] as const;
    }


export const getListTranscriptsQueryOptions = <TData = Awaited<ReturnType<typeof listTranscripts>>, TError = ErrorType<HTTPValidationError>>(cid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTranscripts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTranscriptsQueryKey(cid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTranscripts>>> = ({ signal }) => listTranscripts(cid, { signal });





   return  { queryKey, queryFn, enabled: cid !== null && cid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTranscripts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTranscriptsQueryResult = NonNullable<Awaited<ReturnType<typeof listTranscripts>>>
export type ListTranscriptsQueryError = ErrorType<HTTPValidationError>


export function useListTranscripts<TData = Awaited<ReturnType<typeof listTranscripts>>, TError = ErrorType<HTTPValidationError>>(
 cid: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTranscripts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTranscripts>>,
          TError,
          Awaited<ReturnType<typeof listTranscripts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTranscripts<TData = Awaited<ReturnType<typeof listTranscripts>>, TError = ErrorType<HTTPValidationError>>(
 cid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTranscripts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTranscripts>>,
          TError,
          Awaited<ReturnType<typeof listTranscripts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTranscripts<TData = Awaited<ReturnType<typeof listTranscripts>>, TError = ErrorType<HTTPValidationError>>(
 cid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTranscripts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Transcripts
 */

export function useListTranscripts<TData = Awaited<ReturnType<typeof listTranscripts>>, TError = ErrorType<HTTPValidationError>>(
 cid: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTranscripts>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTranscriptsQueryOptions(cid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type editTranscriptResponse200 = {
  data: unknown
  status: 200
}

export type editTranscriptResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type editTranscriptResponseSuccess = (editTranscriptResponse200) & {
  headers: Headers;
};
export type editTranscriptResponseError = (editTranscriptResponse422) & {
  headers: Headers;
};

export type editTranscriptResponse = (editTranscriptResponseSuccess | editTranscriptResponseError)

export const getEditTranscriptUrl = (tid: number,) => {




  return `/transcripts/${tid}`
}

/**
 * @summary Edit Transcript
 */
export const editTranscript = async (tid: number,
    editIn: EditIn, options?: RequestInit): Promise<editTranscriptResponse> => {

  return mutator<editTranscriptResponse>(getEditTranscriptUrl(tid),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(editIn)
  }
);}




export const getEditTranscriptMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editTranscript>>, TError,{tid: number;data: BodyType<EditIn>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof editTranscript>>, TError,{tid: number;data: BodyType<EditIn>}, TContext> => {

const mutationKey = ['editTranscript'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editTranscript>>, {tid: number;data: BodyType<EditIn>}> = (props) => {
          const {tid,data} = props ?? {};

          return  editTranscript(tid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EditTranscriptMutationResult = NonNullable<Awaited<ReturnType<typeof editTranscript>>>
    export type EditTranscriptMutationBody = BodyType<EditIn>
    export type EditTranscriptMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Edit Transcript
 */
export const useEditTranscript = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editTranscript>>, TError,{tid: number;data: BodyType<EditIn>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof editTranscript>>,
        TError,
        {tid: number;data: BodyType<EditIn>},
        TContext
      > => {
      return useMutation(getEditTranscriptMutationOptions(options), queryClient);
    }
