/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  MatchingVersesParams
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType } from '../api/sdk-mutator';





export type matchingVersesResponse200 = {
  data: unknown
  status: 200
}

export type matchingVersesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type matchingVersesResponseSuccess = (matchingVersesResponse200) & {
  headers: Headers;
};
export type matchingVersesResponseError = (matchingVersesResponse422) & {
  headers: Headers;
};

export type matchingVersesResponse = (matchingVersesResponseSuccess | matchingVersesResponseError)

export const getMatchingVersesUrl = (cid: number,
    params?: MatchingVersesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/consultations/${cid}/verses?${stringifiedParams}` : `/consultations/${cid}/verses`
}

/**
 * Red-flag screen + top-k Charaka Samhita verses for the latest examination and transcripts. No LLM.
 * @summary Matching Verses
 */
export const matchingVerses = async (cid: number,
    params?: MatchingVersesParams, options?: RequestInit): Promise<matchingVersesResponse> => {

  return mutator<matchingVersesResponse>(getMatchingVersesUrl(cid,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getMatchingVersesQueryKey = (cid: number,
    params?: MatchingVersesParams,) => {
    return [
    `/consultations/${cid}/verses`, ...(params ? [params] : [])
    ] as const;
    }


export const getMatchingVersesQueryOptions = <TData = Awaited<ReturnType<typeof matchingVerses>>, TError = ErrorType<HTTPValidationError>>(cid: number,
    params?: MatchingVersesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof matchingVerses>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMatchingVersesQueryKey(cid,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof matchingVerses>>> = ({ signal }) => matchingVerses(cid,params, { signal });





   return  { queryKey, queryFn, enabled: cid !== null && cid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof matchingVerses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MatchingVersesQueryResult = NonNullable<Awaited<ReturnType<typeof matchingVerses>>>
export type MatchingVersesQueryError = ErrorType<HTTPValidationError>


export function useMatchingVerses<TData = Awaited<ReturnType<typeof matchingVerses>>, TError = ErrorType<HTTPValidationError>>(
 cid: number,
    params: undefined |  MatchingVersesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof matchingVerses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof matchingVerses>>,
          TError,
          Awaited<ReturnType<typeof matchingVerses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMatchingVerses<TData = Awaited<ReturnType<typeof matchingVerses>>, TError = ErrorType<HTTPValidationError>>(
 cid: number,
    params?: MatchingVersesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof matchingVerses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof matchingVerses>>,
          TError,
          Awaited<ReturnType<typeof matchingVerses>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMatchingVerses<TData = Awaited<ReturnType<typeof matchingVerses>>, TError = ErrorType<HTTPValidationError>>(
 cid: number,
    params?: MatchingVersesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof matchingVerses>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Matching Verses
 */

export function useMatchingVerses<TData = Awaited<ReturnType<typeof matchingVerses>>, TError = ErrorType<HTTPValidationError>>(
 cid: number,
    params?: MatchingVersesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof matchingVerses>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMatchingVersesQueryOptions(cid,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






