/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminAnnouncementRecipientsParams,
  AdminAnnouncementScheduleOccurrencesParams,
  AdminListAnnouncementSchedulesParams,
  AdminListAnnouncementsParams,
  AdminListNotificationsParams,
  AdminProcessDueAnnouncementSchedulesParams,
  AlertsSummary,
  AnnouncementCreate,
  AnnouncementList,
  AnnouncementOut,
  AnnouncementRecipientList,
  AnnouncementScheduleCreate,
  AnnouncementScheduleList,
  AnnouncementScheduleOut,
  DismissResult,
  HTTPValidationError,
  MarkAllResult,
  NotificationList,
  NotificationOut,
  ProcessDueSummary,
  PushPublicKeyOut,
  PushSubscribeRequest,
  PushSubscribeResult,
  PushUnsubscribeRequest,
  PushUnsubscribeResult,
  ScheduleStatusUpdate,
  UnreadCountOut
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type adminListNotificationsResponse200 = {
  data: NotificationList
  status: 200
}

export type adminListNotificationsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListNotificationsResponseSuccess = (adminListNotificationsResponse200) & {
  headers: Headers;
};
export type adminListNotificationsResponseError = (adminListNotificationsResponse422) & {
  headers: Headers;
};

export type adminListNotificationsResponse = (adminListNotificationsResponseSuccess | adminListNotificationsResponseError)

export const getAdminListNotificationsUrl = (params?: AdminListNotificationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/notifications?${stringifiedParams}` : `/api/v1/admin/notifications`
}

/**
 * @summary List Notifications
 */
export const adminListNotifications = async (params?: AdminListNotificationsParams, options?: RequestInit): Promise<adminListNotificationsResponse> => {

  return mutator<adminListNotificationsResponse>(getAdminListNotificationsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListNotificationsQueryKey = (params?: AdminListNotificationsParams,) => {
    return [
    `/api/v1/admin/notifications`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListNotificationsQueryOptions = <TData = Awaited<ReturnType<typeof adminListNotifications>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListNotificationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListNotifications>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListNotificationsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListNotifications>>> = ({ signal }) => adminListNotifications(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListNotifications>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListNotificationsQueryResult = NonNullable<Awaited<ReturnType<typeof adminListNotifications>>>
export type AdminListNotificationsQueryError = ErrorType<HTTPValidationError>


export function useAdminListNotifications<TData = Awaited<ReturnType<typeof adminListNotifications>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListNotificationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListNotifications>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListNotifications>>,
          TError,
          Awaited<ReturnType<typeof adminListNotifications>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListNotifications<TData = Awaited<ReturnType<typeof adminListNotifications>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListNotificationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListNotifications>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListNotifications>>,
          TError,
          Awaited<ReturnType<typeof adminListNotifications>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListNotifications<TData = Awaited<ReturnType<typeof adminListNotifications>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListNotificationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListNotifications>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Notifications
 */

export function useAdminListNotifications<TData = Awaited<ReturnType<typeof adminListNotifications>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListNotificationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListNotifications>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListNotificationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminNotificationUnreadCountResponse200 = {
  data: UnreadCountOut
  status: 200
}

export type adminNotificationUnreadCountResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminNotificationUnreadCountResponseSuccess = (adminNotificationUnreadCountResponse200) & {
  headers: Headers;
};
export type adminNotificationUnreadCountResponseError = (adminNotificationUnreadCountResponse422) & {
  headers: Headers;
};

export type adminNotificationUnreadCountResponse = (adminNotificationUnreadCountResponseSuccess | adminNotificationUnreadCountResponseError)

export const getAdminNotificationUnreadCountUrl = () => {




  return `/api/v1/admin/notifications/unread-count`
}

/**
 * @summary Notification Unread Count
 */
export const adminNotificationUnreadCount = async ( options?: RequestInit): Promise<adminNotificationUnreadCountResponse> => {

  return mutator<adminNotificationUnreadCountResponse>(getAdminNotificationUnreadCountUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminNotificationUnreadCountQueryKey = () => {
    return [
    `/api/v1/admin/notifications/unread-count`
    ] as const;
    }


export const getAdminNotificationUnreadCountQueryOptions = <TData = Awaited<ReturnType<typeof adminNotificationUnreadCount>>, TError = ErrorType<HTTPValidationError>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminNotificationUnreadCount>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminNotificationUnreadCountQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminNotificationUnreadCount>>> = ({ signal }) => adminNotificationUnreadCount({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminNotificationUnreadCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminNotificationUnreadCountQueryResult = NonNullable<Awaited<ReturnType<typeof adminNotificationUnreadCount>>>
export type AdminNotificationUnreadCountQueryError = ErrorType<HTTPValidationError>


export function useAdminNotificationUnreadCount<TData = Awaited<ReturnType<typeof adminNotificationUnreadCount>>, TError = ErrorType<HTTPValidationError>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminNotificationUnreadCount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminNotificationUnreadCount>>,
          TError,
          Awaited<ReturnType<typeof adminNotificationUnreadCount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminNotificationUnreadCount<TData = Awaited<ReturnType<typeof adminNotificationUnreadCount>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminNotificationUnreadCount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminNotificationUnreadCount>>,
          TError,
          Awaited<ReturnType<typeof adminNotificationUnreadCount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminNotificationUnreadCount<TData = Awaited<ReturnType<typeof adminNotificationUnreadCount>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminNotificationUnreadCount>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Notification Unread Count
 */

export function useAdminNotificationUnreadCount<TData = Awaited<ReturnType<typeof adminNotificationUnreadCount>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminNotificationUnreadCount>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminNotificationUnreadCountQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminMarkAllNotificationsReadResponse200 = {
  data: MarkAllResult
  status: 200
}

export type adminMarkAllNotificationsReadResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminMarkAllNotificationsReadResponseSuccess = (adminMarkAllNotificationsReadResponse200) & {
  headers: Headers;
};
export type adminMarkAllNotificationsReadResponseError = (adminMarkAllNotificationsReadResponse422) & {
  headers: Headers;
};

export type adminMarkAllNotificationsReadResponse = (adminMarkAllNotificationsReadResponseSuccess | adminMarkAllNotificationsReadResponseError)

export const getAdminMarkAllNotificationsReadUrl = () => {




  return `/api/v1/admin/notifications/read-all`
}

/**
 * @summary Mark All Read
 */
export const adminMarkAllNotificationsRead = async ( options?: RequestInit): Promise<adminMarkAllNotificationsReadResponse> => {

  return mutator<adminMarkAllNotificationsReadResponse>(getAdminMarkAllNotificationsReadUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminMarkAllNotificationsReadMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminMarkAllNotificationsRead>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminMarkAllNotificationsRead>>, TError,void, TContext> => {

const mutationKey = ['adminMarkAllNotificationsRead'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminMarkAllNotificationsRead>>, void> = () => {


          return  adminMarkAllNotificationsRead()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminMarkAllNotificationsReadMutationResult = NonNullable<Awaited<ReturnType<typeof adminMarkAllNotificationsRead>>>

    export type AdminMarkAllNotificationsReadMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Mark All Read
 */
export const useAdminMarkAllNotificationsRead = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminMarkAllNotificationsRead>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminMarkAllNotificationsRead>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAdminMarkAllNotificationsReadMutationOptions(options), queryClient);
    }
    export type adminMarkNotificationReadResponse200 = {
  data: NotificationOut
  status: 200
}

export type adminMarkNotificationReadResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminMarkNotificationReadResponseSuccess = (adminMarkNotificationReadResponse200) & {
  headers: Headers;
};
export type adminMarkNotificationReadResponseError = (adminMarkNotificationReadResponse422) & {
  headers: Headers;
};

export type adminMarkNotificationReadResponse = (adminMarkNotificationReadResponseSuccess | adminMarkNotificationReadResponseError)

export const getAdminMarkNotificationReadUrl = (notificationUuid: string,) => {




  return `/api/v1/admin/notifications/${notificationUuid}/read`
}

/**
 * @summary Mark Notification Read
 */
export const adminMarkNotificationRead = async (notificationUuid: string, options?: RequestInit): Promise<adminMarkNotificationReadResponse> => {

  return mutator<adminMarkNotificationReadResponse>(getAdminMarkNotificationReadUrl(notificationUuid),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminMarkNotificationReadMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminMarkNotificationRead>>, TError,{notificationUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminMarkNotificationRead>>, TError,{notificationUuid: string}, TContext> => {

const mutationKey = ['adminMarkNotificationRead'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminMarkNotificationRead>>, {notificationUuid: string}> = (props) => {
          const {notificationUuid} = props ?? {};

          return  adminMarkNotificationRead(notificationUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminMarkNotificationReadMutationResult = NonNullable<Awaited<ReturnType<typeof adminMarkNotificationRead>>>

    export type AdminMarkNotificationReadMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Mark Notification Read
 */
export const useAdminMarkNotificationRead = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminMarkNotificationRead>>, TError,{notificationUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminMarkNotificationRead>>,
        TError,
        {notificationUuid: string},
        TContext
      > => {
      return useMutation(getAdminMarkNotificationReadMutationOptions(options), queryClient);
    }
    export type adminAcknowledgeNotificationResponse200 = {
  data: NotificationOut
  status: 200
}

export type adminAcknowledgeNotificationResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminAcknowledgeNotificationResponseSuccess = (adminAcknowledgeNotificationResponse200) & {
  headers: Headers;
};
export type adminAcknowledgeNotificationResponseError = (adminAcknowledgeNotificationResponse422) & {
  headers: Headers;
};

export type adminAcknowledgeNotificationResponse = (adminAcknowledgeNotificationResponseSuccess | adminAcknowledgeNotificationResponseError)

export const getAdminAcknowledgeNotificationUrl = (notificationUuid: string,) => {




  return `/api/v1/admin/notifications/${notificationUuid}/acknowledge`
}

/**
 * @summary Acknowledge Notification
 */
export const adminAcknowledgeNotification = async (notificationUuid: string, options?: RequestInit): Promise<adminAcknowledgeNotificationResponse> => {

  return mutator<adminAcknowledgeNotificationResponse>(getAdminAcknowledgeNotificationUrl(notificationUuid),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminAcknowledgeNotificationMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAcknowledgeNotification>>, TError,{notificationUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminAcknowledgeNotification>>, TError,{notificationUuid: string}, TContext> => {

const mutationKey = ['adminAcknowledgeNotification'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminAcknowledgeNotification>>, {notificationUuid: string}> = (props) => {
          const {notificationUuid} = props ?? {};

          return  adminAcknowledgeNotification(notificationUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminAcknowledgeNotificationMutationResult = NonNullable<Awaited<ReturnType<typeof adminAcknowledgeNotification>>>

    export type AdminAcknowledgeNotificationMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Acknowledge Notification
 */
export const useAdminAcknowledgeNotification = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAcknowledgeNotification>>, TError,{notificationUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminAcknowledgeNotification>>,
        TError,
        {notificationUuid: string},
        TContext
      > => {
      return useMutation(getAdminAcknowledgeNotificationMutationOptions(options), queryClient);
    }
    export type adminDismissNotificationResponse200 = {
  data: DismissResult
  status: 200
}

export type adminDismissNotificationResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminDismissNotificationResponseSuccess = (adminDismissNotificationResponse200) & {
  headers: Headers;
};
export type adminDismissNotificationResponseError = (adminDismissNotificationResponse422) & {
  headers: Headers;
};

export type adminDismissNotificationResponse = (adminDismissNotificationResponseSuccess | adminDismissNotificationResponseError)

export const getAdminDismissNotificationUrl = (notificationUuid: string,) => {




  return `/api/v1/admin/notifications/${notificationUuid}/dismiss`
}

/**
 * @summary Dismiss Notification
 */
export const adminDismissNotification = async (notificationUuid: string, options?: RequestInit): Promise<adminDismissNotificationResponse> => {

  return mutator<adminDismissNotificationResponse>(getAdminDismissNotificationUrl(notificationUuid),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminDismissNotificationMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDismissNotification>>, TError,{notificationUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminDismissNotification>>, TError,{notificationUuid: string}, TContext> => {

const mutationKey = ['adminDismissNotification'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminDismissNotification>>, {notificationUuid: string}> = (props) => {
          const {notificationUuid} = props ?? {};

          return  adminDismissNotification(notificationUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminDismissNotificationMutationResult = NonNullable<Awaited<ReturnType<typeof adminDismissNotification>>>

    export type AdminDismissNotificationMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Dismiss Notification
 */
export const useAdminDismissNotification = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDismissNotification>>, TError,{notificationUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminDismissNotification>>,
        TError,
        {notificationUuid: string},
        TContext
      > => {
      return useMutation(getAdminDismissNotificationMutationOptions(options), queryClient);
    }
    export type adminPushPublicKeyResponse200 = {
  data: PushPublicKeyOut
  status: 200
}

export type adminPushPublicKeyResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminPushPublicKeyResponseSuccess = (adminPushPublicKeyResponse200) & {
  headers: Headers;
};
export type adminPushPublicKeyResponseError = (adminPushPublicKeyResponse422) & {
  headers: Headers;
};

export type adminPushPublicKeyResponse = (adminPushPublicKeyResponseSuccess | adminPushPublicKeyResponseError)

export const getAdminPushPublicKeyUrl = () => {




  return `/api/v1/admin/notifications/push/public-key`
}

/**
 * @summary Push Public Key
 */
export const adminPushPublicKey = async ( options?: RequestInit): Promise<adminPushPublicKeyResponse> => {

  return mutator<adminPushPublicKeyResponse>(getAdminPushPublicKeyUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminPushPublicKeyQueryKey = () => {
    return [
    `/api/v1/admin/notifications/push/public-key`
    ] as const;
    }


export const getAdminPushPublicKeyQueryOptions = <TData = Awaited<ReturnType<typeof adminPushPublicKey>>, TError = ErrorType<HTTPValidationError>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPushPublicKey>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminPushPublicKeyQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminPushPublicKey>>> = ({ signal }) => adminPushPublicKey({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminPushPublicKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminPushPublicKeyQueryResult = NonNullable<Awaited<ReturnType<typeof adminPushPublicKey>>>
export type AdminPushPublicKeyQueryError = ErrorType<HTTPValidationError>


export function useAdminPushPublicKey<TData = Awaited<ReturnType<typeof adminPushPublicKey>>, TError = ErrorType<HTTPValidationError>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPushPublicKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminPushPublicKey>>,
          TError,
          Awaited<ReturnType<typeof adminPushPublicKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminPushPublicKey<TData = Awaited<ReturnType<typeof adminPushPublicKey>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPushPublicKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminPushPublicKey>>,
          TError,
          Awaited<ReturnType<typeof adminPushPublicKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminPushPublicKey<TData = Awaited<ReturnType<typeof adminPushPublicKey>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPushPublicKey>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Push Public Key
 */

export function useAdminPushPublicKey<TData = Awaited<ReturnType<typeof adminPushPublicKey>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPushPublicKey>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminPushPublicKeyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminPushSubscribeResponse200 = {
  data: PushSubscribeResult
  status: 200
}

export type adminPushSubscribeResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminPushSubscribeResponseSuccess = (adminPushSubscribeResponse200) & {
  headers: Headers;
};
export type adminPushSubscribeResponseError = (adminPushSubscribeResponse422) & {
  headers: Headers;
};

export type adminPushSubscribeResponse = (adminPushSubscribeResponseSuccess | adminPushSubscribeResponseError)

export const getAdminPushSubscribeUrl = () => {




  return `/api/v1/admin/notifications/push/subscriptions`
}

/**
 * @summary Push Subscribe
 */
export const adminPushSubscribe = async (pushSubscribeRequest: PushSubscribeRequest, options?: RequestInit): Promise<adminPushSubscribeResponse> => {

  return mutator<adminPushSubscribeResponse>(getAdminPushSubscribeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(pushSubscribeRequest)
  }
);}




export const getAdminPushSubscribeMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminPushSubscribe>>, TError,{data: BodyType<PushSubscribeRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminPushSubscribe>>, TError,{data: BodyType<PushSubscribeRequest>}, TContext> => {

const mutationKey = ['adminPushSubscribe'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminPushSubscribe>>, {data: BodyType<PushSubscribeRequest>}> = (props) => {
          const {data} = props ?? {};

          return  adminPushSubscribe(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminPushSubscribeMutationResult = NonNullable<Awaited<ReturnType<typeof adminPushSubscribe>>>
    export type AdminPushSubscribeMutationBody = BodyType<PushSubscribeRequest>
    export type AdminPushSubscribeMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Push Subscribe
 */
export const useAdminPushSubscribe = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminPushSubscribe>>, TError,{data: BodyType<PushSubscribeRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminPushSubscribe>>,
        TError,
        {data: BodyType<PushSubscribeRequest>},
        TContext
      > => {
      return useMutation(getAdminPushSubscribeMutationOptions(options), queryClient);
    }
    export type adminPushUnsubscribeResponse200 = {
  data: PushUnsubscribeResult
  status: 200
}

export type adminPushUnsubscribeResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminPushUnsubscribeResponseSuccess = (adminPushUnsubscribeResponse200) & {
  headers: Headers;
};
export type adminPushUnsubscribeResponseError = (adminPushUnsubscribeResponse422) & {
  headers: Headers;
};

export type adminPushUnsubscribeResponse = (adminPushUnsubscribeResponseSuccess | adminPushUnsubscribeResponseError)

export const getAdminPushUnsubscribeUrl = () => {




  return `/api/v1/admin/notifications/push/subscriptions`
}

/**
 * @summary Push Unsubscribe
 */
export const adminPushUnsubscribe = async (pushUnsubscribeRequest: PushUnsubscribeRequest, options?: RequestInit): Promise<adminPushUnsubscribeResponse> => {

  return mutator<adminPushUnsubscribeResponse>(getAdminPushUnsubscribeUrl(),
  {
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(pushUnsubscribeRequest)
  }
);}




export const getAdminPushUnsubscribeMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminPushUnsubscribe>>, TError,{data: BodyType<PushUnsubscribeRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminPushUnsubscribe>>, TError,{data: BodyType<PushUnsubscribeRequest>}, TContext> => {

const mutationKey = ['adminPushUnsubscribe'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminPushUnsubscribe>>, {data: BodyType<PushUnsubscribeRequest>}> = (props) => {
          const {data} = props ?? {};

          return  adminPushUnsubscribe(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminPushUnsubscribeMutationResult = NonNullable<Awaited<ReturnType<typeof adminPushUnsubscribe>>>
    export type AdminPushUnsubscribeMutationBody = BodyType<PushUnsubscribeRequest>
    export type AdminPushUnsubscribeMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Push Unsubscribe
 */
export const useAdminPushUnsubscribe = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminPushUnsubscribe>>, TError,{data: BodyType<PushUnsubscribeRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminPushUnsubscribe>>,
        TError,
        {data: BodyType<PushUnsubscribeRequest>},
        TContext
      > => {
      return useMutation(getAdminPushUnsubscribeMutationOptions(options), queryClient);
    }
    export type adminCreateAnnouncementResponse201 = {
  data: AnnouncementOut
  status: 201
}

export type adminCreateAnnouncementResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCreateAnnouncementResponseSuccess = (adminCreateAnnouncementResponse201) & {
  headers: Headers;
};
export type adminCreateAnnouncementResponseError = (adminCreateAnnouncementResponse422) & {
  headers: Headers;
};

export type adminCreateAnnouncementResponse = (adminCreateAnnouncementResponseSuccess | adminCreateAnnouncementResponseError)

export const getAdminCreateAnnouncementUrl = () => {




  return `/api/v1/admin/notifications/announcements`
}

/**
 * @summary Create Announcement
 */
export const adminCreateAnnouncement = async (announcementCreate: AnnouncementCreate, options?: RequestInit): Promise<adminCreateAnnouncementResponse> => {

  return mutator<adminCreateAnnouncementResponse>(getAdminCreateAnnouncementUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(announcementCreate)
  }
);}




export const getAdminCreateAnnouncementMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateAnnouncement>>, TError,{data: BodyType<AnnouncementCreate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateAnnouncement>>, TError,{data: BodyType<AnnouncementCreate>}, TContext> => {

const mutationKey = ['adminCreateAnnouncement'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateAnnouncement>>, {data: BodyType<AnnouncementCreate>}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateAnnouncement(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateAnnouncementMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateAnnouncement>>>
    export type AdminCreateAnnouncementMutationBody = BodyType<AnnouncementCreate>
    export type AdminCreateAnnouncementMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Announcement
 */
export const useAdminCreateAnnouncement = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateAnnouncement>>, TError,{data: BodyType<AnnouncementCreate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateAnnouncement>>,
        TError,
        {data: BodyType<AnnouncementCreate>},
        TContext
      > => {
      return useMutation(getAdminCreateAnnouncementMutationOptions(options), queryClient);
    }
    export type adminListAnnouncementsResponse200 = {
  data: AnnouncementList
  status: 200
}

export type adminListAnnouncementsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListAnnouncementsResponseSuccess = (adminListAnnouncementsResponse200) & {
  headers: Headers;
};
export type adminListAnnouncementsResponseError = (adminListAnnouncementsResponse422) & {
  headers: Headers;
};

export type adminListAnnouncementsResponse = (adminListAnnouncementsResponseSuccess | adminListAnnouncementsResponseError)

export const getAdminListAnnouncementsUrl = (params?: AdminListAnnouncementsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/notifications/announcements?${stringifiedParams}` : `/api/v1/admin/notifications/announcements`
}

/**
 * @summary List Announcements
 */
export const adminListAnnouncements = async (params?: AdminListAnnouncementsParams, options?: RequestInit): Promise<adminListAnnouncementsResponse> => {

  return mutator<adminListAnnouncementsResponse>(getAdminListAnnouncementsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListAnnouncementsQueryKey = (params?: AdminListAnnouncementsParams,) => {
    return [
    `/api/v1/admin/notifications/announcements`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListAnnouncementsQueryOptions = <TData = Awaited<ReturnType<typeof adminListAnnouncements>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListAnnouncementsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListAnnouncements>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListAnnouncementsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListAnnouncements>>> = ({ signal }) => adminListAnnouncements(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListAnnouncements>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListAnnouncementsQueryResult = NonNullable<Awaited<ReturnType<typeof adminListAnnouncements>>>
export type AdminListAnnouncementsQueryError = ErrorType<HTTPValidationError>


export function useAdminListAnnouncements<TData = Awaited<ReturnType<typeof adminListAnnouncements>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListAnnouncementsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListAnnouncements>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListAnnouncements>>,
          TError,
          Awaited<ReturnType<typeof adminListAnnouncements>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListAnnouncements<TData = Awaited<ReturnType<typeof adminListAnnouncements>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListAnnouncementsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListAnnouncements>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListAnnouncements>>,
          TError,
          Awaited<ReturnType<typeof adminListAnnouncements>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListAnnouncements<TData = Awaited<ReturnType<typeof adminListAnnouncements>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListAnnouncementsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListAnnouncements>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Announcements
 */

export function useAdminListAnnouncements<TData = Awaited<ReturnType<typeof adminListAnnouncements>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListAnnouncementsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListAnnouncements>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListAnnouncementsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminAnnouncementRecipientsResponse200 = {
  data: AnnouncementRecipientList
  status: 200
}

export type adminAnnouncementRecipientsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminAnnouncementRecipientsResponseSuccess = (adminAnnouncementRecipientsResponse200) & {
  headers: Headers;
};
export type adminAnnouncementRecipientsResponseError = (adminAnnouncementRecipientsResponse422) & {
  headers: Headers;
};

export type adminAnnouncementRecipientsResponse = (adminAnnouncementRecipientsResponseSuccess | adminAnnouncementRecipientsResponseError)

export const getAdminAnnouncementRecipientsUrl = (announcementUuid: string,
    params?: AdminAnnouncementRecipientsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/notifications/announcements/${announcementUuid}/recipients?${stringifiedParams}` : `/api/v1/admin/notifications/announcements/${announcementUuid}/recipients`
}

/**
 * @summary Announcement Recipients
 */
export const adminAnnouncementRecipients = async (announcementUuid: string,
    params?: AdminAnnouncementRecipientsParams, options?: RequestInit): Promise<adminAnnouncementRecipientsResponse> => {

  return mutator<adminAnnouncementRecipientsResponse>(getAdminAnnouncementRecipientsUrl(announcementUuid,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminAnnouncementRecipientsQueryKey = (announcementUuid: string,
    params?: AdminAnnouncementRecipientsParams,) => {
    return [
    `/api/v1/admin/notifications/announcements/${announcementUuid}/recipients`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminAnnouncementRecipientsQueryOptions = <TData = Awaited<ReturnType<typeof adminAnnouncementRecipients>>, TError = ErrorType<HTTPValidationError>>(announcementUuid: string,
    params?: AdminAnnouncementRecipientsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminAnnouncementRecipients>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminAnnouncementRecipientsQueryKey(announcementUuid,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminAnnouncementRecipients>>> = ({ signal }) => adminAnnouncementRecipients(announcementUuid,params, { signal });





   return  { queryKey, queryFn, enabled: announcementUuid !== null && announcementUuid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminAnnouncementRecipients>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminAnnouncementRecipientsQueryResult = NonNullable<Awaited<ReturnType<typeof adminAnnouncementRecipients>>>
export type AdminAnnouncementRecipientsQueryError = ErrorType<HTTPValidationError>


export function useAdminAnnouncementRecipients<TData = Awaited<ReturnType<typeof adminAnnouncementRecipients>>, TError = ErrorType<HTTPValidationError>>(
 announcementUuid: string,
    params: undefined |  AdminAnnouncementRecipientsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminAnnouncementRecipients>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminAnnouncementRecipients>>,
          TError,
          Awaited<ReturnType<typeof adminAnnouncementRecipients>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminAnnouncementRecipients<TData = Awaited<ReturnType<typeof adminAnnouncementRecipients>>, TError = ErrorType<HTTPValidationError>>(
 announcementUuid: string,
    params?: AdminAnnouncementRecipientsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminAnnouncementRecipients>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminAnnouncementRecipients>>,
          TError,
          Awaited<ReturnType<typeof adminAnnouncementRecipients>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminAnnouncementRecipients<TData = Awaited<ReturnType<typeof adminAnnouncementRecipients>>, TError = ErrorType<HTTPValidationError>>(
 announcementUuid: string,
    params?: AdminAnnouncementRecipientsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminAnnouncementRecipients>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Announcement Recipients
 */

export function useAdminAnnouncementRecipients<TData = Awaited<ReturnType<typeof adminAnnouncementRecipients>>, TError = ErrorType<HTTPValidationError>>(
 announcementUuid: string,
    params?: AdminAnnouncementRecipientsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminAnnouncementRecipients>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminAnnouncementRecipientsQueryOptions(announcementUuid,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminCreateAnnouncementScheduleResponse201 = {
  data: AnnouncementScheduleOut
  status: 201
}

export type adminCreateAnnouncementScheduleResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCreateAnnouncementScheduleResponseSuccess = (adminCreateAnnouncementScheduleResponse201) & {
  headers: Headers;
};
export type adminCreateAnnouncementScheduleResponseError = (adminCreateAnnouncementScheduleResponse422) & {
  headers: Headers;
};

export type adminCreateAnnouncementScheduleResponse = (adminCreateAnnouncementScheduleResponseSuccess | adminCreateAnnouncementScheduleResponseError)

export const getAdminCreateAnnouncementScheduleUrl = () => {




  return `/api/v1/admin/notifications/announcement-schedules`
}

/**
 * @summary Create Announcement Schedule
 */
export const adminCreateAnnouncementSchedule = async (announcementScheduleCreate: AnnouncementScheduleCreate, options?: RequestInit): Promise<adminCreateAnnouncementScheduleResponse> => {

  return mutator<adminCreateAnnouncementScheduleResponse>(getAdminCreateAnnouncementScheduleUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(announcementScheduleCreate)
  }
);}




export const getAdminCreateAnnouncementScheduleMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateAnnouncementSchedule>>, TError,{data: BodyType<AnnouncementScheduleCreate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateAnnouncementSchedule>>, TError,{data: BodyType<AnnouncementScheduleCreate>}, TContext> => {

const mutationKey = ['adminCreateAnnouncementSchedule'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateAnnouncementSchedule>>, {data: BodyType<AnnouncementScheduleCreate>}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateAnnouncementSchedule(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateAnnouncementScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateAnnouncementSchedule>>>
    export type AdminCreateAnnouncementScheduleMutationBody = BodyType<AnnouncementScheduleCreate>
    export type AdminCreateAnnouncementScheduleMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Announcement Schedule
 */
export const useAdminCreateAnnouncementSchedule = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateAnnouncementSchedule>>, TError,{data: BodyType<AnnouncementScheduleCreate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateAnnouncementSchedule>>,
        TError,
        {data: BodyType<AnnouncementScheduleCreate>},
        TContext
      > => {
      return useMutation(getAdminCreateAnnouncementScheduleMutationOptions(options), queryClient);
    }
    export type adminListAnnouncementSchedulesResponse200 = {
  data: AnnouncementScheduleList
  status: 200
}

export type adminListAnnouncementSchedulesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListAnnouncementSchedulesResponseSuccess = (adminListAnnouncementSchedulesResponse200) & {
  headers: Headers;
};
export type adminListAnnouncementSchedulesResponseError = (adminListAnnouncementSchedulesResponse422) & {
  headers: Headers;
};

export type adminListAnnouncementSchedulesResponse = (adminListAnnouncementSchedulesResponseSuccess | adminListAnnouncementSchedulesResponseError)

export const getAdminListAnnouncementSchedulesUrl = (params?: AdminListAnnouncementSchedulesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/notifications/announcement-schedules?${stringifiedParams}` : `/api/v1/admin/notifications/announcement-schedules`
}

/**
 * @summary List Announcement Schedules
 */
export const adminListAnnouncementSchedules = async (params?: AdminListAnnouncementSchedulesParams, options?: RequestInit): Promise<adminListAnnouncementSchedulesResponse> => {

  return mutator<adminListAnnouncementSchedulesResponse>(getAdminListAnnouncementSchedulesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListAnnouncementSchedulesQueryKey = (params?: AdminListAnnouncementSchedulesParams,) => {
    return [
    `/api/v1/admin/notifications/announcement-schedules`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListAnnouncementSchedulesQueryOptions = <TData = Awaited<ReturnType<typeof adminListAnnouncementSchedules>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListAnnouncementSchedulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListAnnouncementSchedules>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListAnnouncementSchedulesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListAnnouncementSchedules>>> = ({ signal }) => adminListAnnouncementSchedules(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListAnnouncementSchedules>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListAnnouncementSchedulesQueryResult = NonNullable<Awaited<ReturnType<typeof adminListAnnouncementSchedules>>>
export type AdminListAnnouncementSchedulesQueryError = ErrorType<HTTPValidationError>


export function useAdminListAnnouncementSchedules<TData = Awaited<ReturnType<typeof adminListAnnouncementSchedules>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListAnnouncementSchedulesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListAnnouncementSchedules>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListAnnouncementSchedules>>,
          TError,
          Awaited<ReturnType<typeof adminListAnnouncementSchedules>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListAnnouncementSchedules<TData = Awaited<ReturnType<typeof adminListAnnouncementSchedules>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListAnnouncementSchedulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListAnnouncementSchedules>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListAnnouncementSchedules>>,
          TError,
          Awaited<ReturnType<typeof adminListAnnouncementSchedules>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListAnnouncementSchedules<TData = Awaited<ReturnType<typeof adminListAnnouncementSchedules>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListAnnouncementSchedulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListAnnouncementSchedules>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Announcement Schedules
 */

export function useAdminListAnnouncementSchedules<TData = Awaited<ReturnType<typeof adminListAnnouncementSchedules>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListAnnouncementSchedulesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListAnnouncementSchedules>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListAnnouncementSchedulesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminProcessDueAlertsResponse200 = {
  data: AlertsSummary
  status: 200
}

export type adminProcessDueAlertsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminProcessDueAlertsResponseSuccess = (adminProcessDueAlertsResponse200) & {
  headers: Headers;
};
export type adminProcessDueAlertsResponseError = (adminProcessDueAlertsResponse422) & {
  headers: Headers;
};

export type adminProcessDueAlertsResponse = (adminProcessDueAlertsResponseSuccess | adminProcessDueAlertsResponseError)

export const getAdminProcessDueAlertsUrl = () => {




  return `/api/v1/admin/notifications/alerts/process-due`
}

/**
 * Cron-style business-alert sweep: low/out stock, expiring batches, aging
production items → notifications + Web Push (dedup makes reruns safe).
 * @summary Process Due Alerts
 */
export const adminProcessDueAlerts = async ( options?: RequestInit): Promise<adminProcessDueAlertsResponse> => {

  return mutator<adminProcessDueAlertsResponse>(getAdminProcessDueAlertsUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminProcessDueAlertsMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminProcessDueAlerts>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminProcessDueAlerts>>, TError,void, TContext> => {

const mutationKey = ['adminProcessDueAlerts'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminProcessDueAlerts>>, void> = () => {


          return  adminProcessDueAlerts()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminProcessDueAlertsMutationResult = NonNullable<Awaited<ReturnType<typeof adminProcessDueAlerts>>>

    export type AdminProcessDueAlertsMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Process Due Alerts
 */
export const useAdminProcessDueAlerts = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminProcessDueAlerts>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminProcessDueAlerts>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAdminProcessDueAlertsMutationOptions(options), queryClient);
    }
    export type adminProcessDueAnnouncementSchedulesResponse200 = {
  data: ProcessDueSummary
  status: 200
}

export type adminProcessDueAnnouncementSchedulesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminProcessDueAnnouncementSchedulesResponseSuccess = (adminProcessDueAnnouncementSchedulesResponse200) & {
  headers: Headers;
};
export type adminProcessDueAnnouncementSchedulesResponseError = (adminProcessDueAnnouncementSchedulesResponse422) & {
  headers: Headers;
};

export type adminProcessDueAnnouncementSchedulesResponse = (adminProcessDueAnnouncementSchedulesResponseSuccess | adminProcessDueAnnouncementSchedulesResponseError)

export const getAdminProcessDueAnnouncementSchedulesUrl = (params?: AdminProcessDueAnnouncementSchedulesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/notifications/announcement-schedules/process-due?${stringifiedParams}` : `/api/v1/admin/notifications/announcement-schedules/process-due`
}

/**
 * @summary Process Due Announcement Schedules
 */
export const adminProcessDueAnnouncementSchedules = async (params?: AdminProcessDueAnnouncementSchedulesParams, options?: RequestInit): Promise<adminProcessDueAnnouncementSchedulesResponse> => {

  return mutator<adminProcessDueAnnouncementSchedulesResponse>(getAdminProcessDueAnnouncementSchedulesUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminProcessDueAnnouncementSchedulesMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminProcessDueAnnouncementSchedules>>, TError,{params?: AdminProcessDueAnnouncementSchedulesParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminProcessDueAnnouncementSchedules>>, TError,{params?: AdminProcessDueAnnouncementSchedulesParams}, TContext> => {

const mutationKey = ['adminProcessDueAnnouncementSchedules'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminProcessDueAnnouncementSchedules>>, {params?: AdminProcessDueAnnouncementSchedulesParams}> = (props) => {
          const {params} = props ?? {};

          return  adminProcessDueAnnouncementSchedules(params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminProcessDueAnnouncementSchedulesMutationResult = NonNullable<Awaited<ReturnType<typeof adminProcessDueAnnouncementSchedules>>>

    export type AdminProcessDueAnnouncementSchedulesMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Process Due Announcement Schedules
 */
export const useAdminProcessDueAnnouncementSchedules = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminProcessDueAnnouncementSchedules>>, TError,{params?: AdminProcessDueAnnouncementSchedulesParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminProcessDueAnnouncementSchedules>>,
        TError,
        {params?: AdminProcessDueAnnouncementSchedulesParams},
        TContext
      > => {
      return useMutation(getAdminProcessDueAnnouncementSchedulesMutationOptions(options), queryClient);
    }
    export type adminGetAnnouncementScheduleResponse200 = {
  data: AnnouncementScheduleOut
  status: 200
}

export type adminGetAnnouncementScheduleResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminGetAnnouncementScheduleResponseSuccess = (adminGetAnnouncementScheduleResponse200) & {
  headers: Headers;
};
export type adminGetAnnouncementScheduleResponseError = (adminGetAnnouncementScheduleResponse422) & {
  headers: Headers;
};

export type adminGetAnnouncementScheduleResponse = (adminGetAnnouncementScheduleResponseSuccess | adminGetAnnouncementScheduleResponseError)

export const getAdminGetAnnouncementScheduleUrl = (scheduleUuid: string,) => {




  return `/api/v1/admin/notifications/announcement-schedules/${scheduleUuid}`
}

/**
 * @summary Get Announcement Schedule
 */
export const adminGetAnnouncementSchedule = async (scheduleUuid: string, options?: RequestInit): Promise<adminGetAnnouncementScheduleResponse> => {

  return mutator<adminGetAnnouncementScheduleResponse>(getAdminGetAnnouncementScheduleUrl(scheduleUuid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminGetAnnouncementScheduleQueryKey = (scheduleUuid: string,) => {
    return [
    `/api/v1/admin/notifications/announcement-schedules/${scheduleUuid}`
    ] as const;
    }


export const getAdminGetAnnouncementScheduleQueryOptions = <TData = Awaited<ReturnType<typeof adminGetAnnouncementSchedule>>, TError = ErrorType<HTTPValidationError>>(scheduleUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetAnnouncementSchedule>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetAnnouncementScheduleQueryKey(scheduleUuid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetAnnouncementSchedule>>> = ({ signal }) => adminGetAnnouncementSchedule(scheduleUuid, { signal });





   return  { queryKey, queryFn, enabled: scheduleUuid !== null && scheduleUuid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetAnnouncementSchedule>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetAnnouncementScheduleQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetAnnouncementSchedule>>>
export type AdminGetAnnouncementScheduleQueryError = ErrorType<HTTPValidationError>


export function useAdminGetAnnouncementSchedule<TData = Awaited<ReturnType<typeof adminGetAnnouncementSchedule>>, TError = ErrorType<HTTPValidationError>>(
 scheduleUuid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetAnnouncementSchedule>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetAnnouncementSchedule>>,
          TError,
          Awaited<ReturnType<typeof adminGetAnnouncementSchedule>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetAnnouncementSchedule<TData = Awaited<ReturnType<typeof adminGetAnnouncementSchedule>>, TError = ErrorType<HTTPValidationError>>(
 scheduleUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetAnnouncementSchedule>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetAnnouncementSchedule>>,
          TError,
          Awaited<ReturnType<typeof adminGetAnnouncementSchedule>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetAnnouncementSchedule<TData = Awaited<ReturnType<typeof adminGetAnnouncementSchedule>>, TError = ErrorType<HTTPValidationError>>(
 scheduleUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetAnnouncementSchedule>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Announcement Schedule
 */

export function useAdminGetAnnouncementSchedule<TData = Awaited<ReturnType<typeof adminGetAnnouncementSchedule>>, TError = ErrorType<HTTPValidationError>>(
 scheduleUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetAnnouncementSchedule>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminGetAnnouncementScheduleQueryOptions(scheduleUuid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminUpdateAnnouncementScheduleResponse200 = {
  data: AnnouncementScheduleOut
  status: 200
}

export type adminUpdateAnnouncementScheduleResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminUpdateAnnouncementScheduleResponseSuccess = (adminUpdateAnnouncementScheduleResponse200) & {
  headers: Headers;
};
export type adminUpdateAnnouncementScheduleResponseError = (adminUpdateAnnouncementScheduleResponse422) & {
  headers: Headers;
};

export type adminUpdateAnnouncementScheduleResponse = (adminUpdateAnnouncementScheduleResponseSuccess | adminUpdateAnnouncementScheduleResponseError)

export const getAdminUpdateAnnouncementScheduleUrl = (scheduleUuid: string,) => {




  return `/api/v1/admin/notifications/announcement-schedules/${scheduleUuid}`
}

/**
 * @summary Update Announcement Schedule
 */
export const adminUpdateAnnouncementSchedule = async (scheduleUuid: string,
    scheduleStatusUpdate: ScheduleStatusUpdate, options?: RequestInit): Promise<adminUpdateAnnouncementScheduleResponse> => {

  return mutator<adminUpdateAnnouncementScheduleResponse>(getAdminUpdateAnnouncementScheduleUrl(scheduleUuid),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(scheduleStatusUpdate)
  }
);}




export const getAdminUpdateAnnouncementScheduleMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateAnnouncementSchedule>>, TError,{scheduleUuid: string;data: BodyType<ScheduleStatusUpdate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateAnnouncementSchedule>>, TError,{scheduleUuid: string;data: BodyType<ScheduleStatusUpdate>}, TContext> => {

const mutationKey = ['adminUpdateAnnouncementSchedule'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateAnnouncementSchedule>>, {scheduleUuid: string;data: BodyType<ScheduleStatusUpdate>}> = (props) => {
          const {scheduleUuid,data} = props ?? {};

          return  adminUpdateAnnouncementSchedule(scheduleUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateAnnouncementScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateAnnouncementSchedule>>>
    export type AdminUpdateAnnouncementScheduleMutationBody = BodyType<ScheduleStatusUpdate>
    export type AdminUpdateAnnouncementScheduleMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Announcement Schedule
 */
export const useAdminUpdateAnnouncementSchedule = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateAnnouncementSchedule>>, TError,{scheduleUuid: string;data: BodyType<ScheduleStatusUpdate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateAnnouncementSchedule>>,
        TError,
        {scheduleUuid: string;data: BodyType<ScheduleStatusUpdate>},
        TContext
      > => {
      return useMutation(getAdminUpdateAnnouncementScheduleMutationOptions(options), queryClient);
    }
    export type adminAnnouncementScheduleOccurrencesResponse200 = {
  data: AnnouncementList
  status: 200
}

export type adminAnnouncementScheduleOccurrencesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminAnnouncementScheduleOccurrencesResponseSuccess = (adminAnnouncementScheduleOccurrencesResponse200) & {
  headers: Headers;
};
export type adminAnnouncementScheduleOccurrencesResponseError = (adminAnnouncementScheduleOccurrencesResponse422) & {
  headers: Headers;
};

export type adminAnnouncementScheduleOccurrencesResponse = (adminAnnouncementScheduleOccurrencesResponseSuccess | adminAnnouncementScheduleOccurrencesResponseError)

export const getAdminAnnouncementScheduleOccurrencesUrl = (scheduleUuid: string,
    params?: AdminAnnouncementScheduleOccurrencesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/notifications/announcement-schedules/${scheduleUuid}/occurrences?${stringifiedParams}` : `/api/v1/admin/notifications/announcement-schedules/${scheduleUuid}/occurrences`
}

/**
 * @summary Announcement Schedule Occurrences
 */
export const adminAnnouncementScheduleOccurrences = async (scheduleUuid: string,
    params?: AdminAnnouncementScheduleOccurrencesParams, options?: RequestInit): Promise<adminAnnouncementScheduleOccurrencesResponse> => {

  return mutator<adminAnnouncementScheduleOccurrencesResponse>(getAdminAnnouncementScheduleOccurrencesUrl(scheduleUuid,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminAnnouncementScheduleOccurrencesQueryKey = (scheduleUuid: string,
    params?: AdminAnnouncementScheduleOccurrencesParams,) => {
    return [
    `/api/v1/admin/notifications/announcement-schedules/${scheduleUuid}/occurrences`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminAnnouncementScheduleOccurrencesQueryOptions = <TData = Awaited<ReturnType<typeof adminAnnouncementScheduleOccurrences>>, TError = ErrorType<HTTPValidationError>>(scheduleUuid: string,
    params?: AdminAnnouncementScheduleOccurrencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminAnnouncementScheduleOccurrences>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminAnnouncementScheduleOccurrencesQueryKey(scheduleUuid,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminAnnouncementScheduleOccurrences>>> = ({ signal }) => adminAnnouncementScheduleOccurrences(scheduleUuid,params, { signal });





   return  { queryKey, queryFn, enabled: scheduleUuid !== null && scheduleUuid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminAnnouncementScheduleOccurrences>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminAnnouncementScheduleOccurrencesQueryResult = NonNullable<Awaited<ReturnType<typeof adminAnnouncementScheduleOccurrences>>>
export type AdminAnnouncementScheduleOccurrencesQueryError = ErrorType<HTTPValidationError>


export function useAdminAnnouncementScheduleOccurrences<TData = Awaited<ReturnType<typeof adminAnnouncementScheduleOccurrences>>, TError = ErrorType<HTTPValidationError>>(
 scheduleUuid: string,
    params: undefined |  AdminAnnouncementScheduleOccurrencesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminAnnouncementScheduleOccurrences>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminAnnouncementScheduleOccurrences>>,
          TError,
          Awaited<ReturnType<typeof adminAnnouncementScheduleOccurrences>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminAnnouncementScheduleOccurrences<TData = Awaited<ReturnType<typeof adminAnnouncementScheduleOccurrences>>, TError = ErrorType<HTTPValidationError>>(
 scheduleUuid: string,
    params?: AdminAnnouncementScheduleOccurrencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminAnnouncementScheduleOccurrences>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminAnnouncementScheduleOccurrences>>,
          TError,
          Awaited<ReturnType<typeof adminAnnouncementScheduleOccurrences>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminAnnouncementScheduleOccurrences<TData = Awaited<ReturnType<typeof adminAnnouncementScheduleOccurrences>>, TError = ErrorType<HTTPValidationError>>(
 scheduleUuid: string,
    params?: AdminAnnouncementScheduleOccurrencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminAnnouncementScheduleOccurrences>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Announcement Schedule Occurrences
 */

export function useAdminAnnouncementScheduleOccurrences<TData = Awaited<ReturnType<typeof adminAnnouncementScheduleOccurrences>>, TError = ErrorType<HTTPValidationError>>(
 scheduleUuid: string,
    params?: AdminAnnouncementScheduleOccurrencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminAnnouncementScheduleOccurrences>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminAnnouncementScheduleOccurrencesQueryOptions(scheduleUuid,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






