/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminExportPaymentsParams,
  AdminListPaymentsParams,
  HTTPValidationError,
  PaymentCreate,
  PaymentDetail,
  PaymentList,
  PaymentUpdate
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type adminListPaymentsResponse200 = {
  data: PaymentList
  status: 200
}

export type adminListPaymentsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListPaymentsResponseSuccess = (adminListPaymentsResponse200) & {
  headers: Headers;
};
export type adminListPaymentsResponseError = (adminListPaymentsResponse422) & {
  headers: Headers;
};

export type adminListPaymentsResponse = (adminListPaymentsResponseSuccess | adminListPaymentsResponseError)

export const getAdminListPaymentsUrl = (params?: AdminListPaymentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/payments?${stringifiedParams}` : `/api/v1/admin/payments`
}

/**
 * @summary List Payments
 */
export const adminListPayments = async (params?: AdminListPaymentsParams, options?: RequestInit): Promise<adminListPaymentsResponse> => {

  return mutator<adminListPaymentsResponse>(getAdminListPaymentsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListPaymentsQueryKey = (params?: AdminListPaymentsParams,) => {
    return [
    `/api/v1/admin/payments`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListPaymentsQueryOptions = <TData = Awaited<ReturnType<typeof adminListPayments>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListPaymentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPayments>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListPaymentsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListPayments>>> = ({ signal }) => adminListPayments(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListPayments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListPaymentsQueryResult = NonNullable<Awaited<ReturnType<typeof adminListPayments>>>
export type AdminListPaymentsQueryError = ErrorType<HTTPValidationError>


export function useAdminListPayments<TData = Awaited<ReturnType<typeof adminListPayments>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListPaymentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPayments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListPayments>>,
          TError,
          Awaited<ReturnType<typeof adminListPayments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListPayments<TData = Awaited<ReturnType<typeof adminListPayments>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListPaymentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPayments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListPayments>>,
          TError,
          Awaited<ReturnType<typeof adminListPayments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListPayments<TData = Awaited<ReturnType<typeof adminListPayments>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListPaymentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPayments>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Payments
 */

export function useAdminListPayments<TData = Awaited<ReturnType<typeof adminListPayments>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListPaymentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPayments>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListPaymentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminCreatePaymentResponse201 = {
  data: PaymentDetail
  status: 201
}

export type adminCreatePaymentResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCreatePaymentResponseSuccess = (adminCreatePaymentResponse201) & {
  headers: Headers;
};
export type adminCreatePaymentResponseError = (adminCreatePaymentResponse422) & {
  headers: Headers;
};

export type adminCreatePaymentResponse = (adminCreatePaymentResponseSuccess | adminCreatePaymentResponseError)

export const getAdminCreatePaymentUrl = () => {




  return `/api/v1/admin/payments`
}

/**
 * @summary Create Payment
 */
export const adminCreatePayment = async (paymentCreate: PaymentCreate, options?: RequestInit): Promise<adminCreatePaymentResponse> => {

  return mutator<adminCreatePaymentResponse>(getAdminCreatePaymentUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(paymentCreate)
  }
);}




export const getAdminCreatePaymentMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreatePayment>>, TError,{data: BodyType<PaymentCreate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCreatePayment>>, TError,{data: BodyType<PaymentCreate>}, TContext> => {

const mutationKey = ['adminCreatePayment'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreatePayment>>, {data: BodyType<PaymentCreate>}> = (props) => {
          const {data} = props ?? {};

          return  adminCreatePayment(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCreatePaymentMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreatePayment>>>
    export type AdminCreatePaymentMutationBody = BodyType<PaymentCreate>
    export type AdminCreatePaymentMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Payment
 */
export const useAdminCreatePayment = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreatePayment>>, TError,{data: BodyType<PaymentCreate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreatePayment>>,
        TError,
        {data: BodyType<PaymentCreate>},
        TContext
      > => {
      return useMutation(getAdminCreatePaymentMutationOptions(options), queryClient);
    }
    export type adminExportPaymentsResponse200 = {
  data: unknown
  status: 200
}

export type adminExportPaymentsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminExportPaymentsResponseSuccess = (adminExportPaymentsResponse200) & {
  headers: Headers;
};
export type adminExportPaymentsResponseError = (adminExportPaymentsResponse422) & {
  headers: Headers;
};

export type adminExportPaymentsResponse = (adminExportPaymentsResponseSuccess | adminExportPaymentsResponseError)

export const getAdminExportPaymentsUrl = (params?: AdminExportPaymentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/payments/export?${stringifiedParams}` : `/api/v1/admin/payments/export`
}

/**
 * @summary Export Payments
 */
export const adminExportPayments = async (params?: AdminExportPaymentsParams, options?: RequestInit): Promise<adminExportPaymentsResponse> => {

  return mutator<adminExportPaymentsResponse>(getAdminExportPaymentsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminExportPaymentsQueryKey = (params?: AdminExportPaymentsParams,) => {
    return [
    `/api/v1/admin/payments/export`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminExportPaymentsQueryOptions = <TData = Awaited<ReturnType<typeof adminExportPayments>>, TError = ErrorType<HTTPValidationError>>(params?: AdminExportPaymentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportPayments>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminExportPaymentsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminExportPayments>>> = ({ signal }) => adminExportPayments(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminExportPayments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminExportPaymentsQueryResult = NonNullable<Awaited<ReturnType<typeof adminExportPayments>>>
export type AdminExportPaymentsQueryError = ErrorType<HTTPValidationError>


export function useAdminExportPayments<TData = Awaited<ReturnType<typeof adminExportPayments>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminExportPaymentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportPayments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminExportPayments>>,
          TError,
          Awaited<ReturnType<typeof adminExportPayments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminExportPayments<TData = Awaited<ReturnType<typeof adminExportPayments>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminExportPaymentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportPayments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminExportPayments>>,
          TError,
          Awaited<ReturnType<typeof adminExportPayments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminExportPayments<TData = Awaited<ReturnType<typeof adminExportPayments>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminExportPaymentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportPayments>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Export Payments
 */

export function useAdminExportPayments<TData = Awaited<ReturnType<typeof adminExportPayments>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminExportPaymentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportPayments>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminExportPaymentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminGetPaymentResponse200 = {
  data: PaymentDetail
  status: 200
}

export type adminGetPaymentResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminGetPaymentResponseSuccess = (adminGetPaymentResponse200) & {
  headers: Headers;
};
export type adminGetPaymentResponseError = (adminGetPaymentResponse422) & {
  headers: Headers;
};

export type adminGetPaymentResponse = (adminGetPaymentResponseSuccess | adminGetPaymentResponseError)

export const getAdminGetPaymentUrl = (paymentUuid: string,) => {




  return `/api/v1/admin/payments/${paymentUuid}`
}

/**
 * @summary Get Payment
 */
export const adminGetPayment = async (paymentUuid: string, options?: RequestInit): Promise<adminGetPaymentResponse> => {

  return mutator<adminGetPaymentResponse>(getAdminGetPaymentUrl(paymentUuid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminGetPaymentQueryKey = (paymentUuid: string,) => {
    return [
    `/api/v1/admin/payments/${paymentUuid}`
    ] as const;
    }


export const getAdminGetPaymentQueryOptions = <TData = Awaited<ReturnType<typeof adminGetPayment>>, TError = ErrorType<HTTPValidationError>>(paymentUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetPayment>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetPaymentQueryKey(paymentUuid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetPayment>>> = ({ signal }) => adminGetPayment(paymentUuid, { signal });





   return  { queryKey, queryFn, enabled: paymentUuid !== null && paymentUuid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetPayment>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetPaymentQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetPayment>>>
export type AdminGetPaymentQueryError = ErrorType<HTTPValidationError>


export function useAdminGetPayment<TData = Awaited<ReturnType<typeof adminGetPayment>>, TError = ErrorType<HTTPValidationError>>(
 paymentUuid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetPayment>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetPayment>>,
          TError,
          Awaited<ReturnType<typeof adminGetPayment>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetPayment<TData = Awaited<ReturnType<typeof adminGetPayment>>, TError = ErrorType<HTTPValidationError>>(
 paymentUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetPayment>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetPayment>>,
          TError,
          Awaited<ReturnType<typeof adminGetPayment>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetPayment<TData = Awaited<ReturnType<typeof adminGetPayment>>, TError = ErrorType<HTTPValidationError>>(
 paymentUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetPayment>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Payment
 */

export function useAdminGetPayment<TData = Awaited<ReturnType<typeof adminGetPayment>>, TError = ErrorType<HTTPValidationError>>(
 paymentUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetPayment>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminGetPaymentQueryOptions(paymentUuid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminUpdatePaymentResponse200 = {
  data: PaymentDetail
  status: 200
}

export type adminUpdatePaymentResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminUpdatePaymentResponseSuccess = (adminUpdatePaymentResponse200) & {
  headers: Headers;
};
export type adminUpdatePaymentResponseError = (adminUpdatePaymentResponse422) & {
  headers: Headers;
};

export type adminUpdatePaymentResponse = (adminUpdatePaymentResponseSuccess | adminUpdatePaymentResponseError)

export const getAdminUpdatePaymentUrl = (paymentUuid: string,) => {




  return `/api/v1/admin/payments/${paymentUuid}`
}

/**
 * @summary Update Payment
 */
export const adminUpdatePayment = async (paymentUuid: string,
    paymentUpdate: PaymentUpdate, options?: RequestInit): Promise<adminUpdatePaymentResponse> => {

  return mutator<adminUpdatePaymentResponse>(getAdminUpdatePaymentUrl(paymentUuid),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(paymentUpdate)
  }
);}




export const getAdminUpdatePaymentMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdatePayment>>, TError,{paymentUuid: string;data: BodyType<PaymentUpdate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdatePayment>>, TError,{paymentUuid: string;data: BodyType<PaymentUpdate>}, TContext> => {

const mutationKey = ['adminUpdatePayment'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdatePayment>>, {paymentUuid: string;data: BodyType<PaymentUpdate>}> = (props) => {
          const {paymentUuid,data} = props ?? {};

          return  adminUpdatePayment(paymentUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdatePaymentMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdatePayment>>>
    export type AdminUpdatePaymentMutationBody = BodyType<PaymentUpdate>
    export type AdminUpdatePaymentMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Payment
 */
export const useAdminUpdatePayment = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdatePayment>>, TError,{paymentUuid: string;data: BodyType<PaymentUpdate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdatePayment>>,
        TError,
        {paymentUuid: string;data: BodyType<PaymentUpdate>},
        TContext
      > => {
      return useMutation(getAdminUpdatePaymentMutationOptions(options), queryClient);
    }
    export type adminDeletePaymentResponse204 = {
  data: void
  status: 204
}

export type adminDeletePaymentResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminDeletePaymentResponseSuccess = (adminDeletePaymentResponse204) & {
  headers: Headers;
};
export type adminDeletePaymentResponseError = (adminDeletePaymentResponse422) & {
  headers: Headers;
};

export type adminDeletePaymentResponse = (adminDeletePaymentResponseSuccess | adminDeletePaymentResponseError)

export const getAdminDeletePaymentUrl = (paymentUuid: string,) => {




  return `/api/v1/admin/payments/${paymentUuid}`
}

/**
 * @summary Delete Payment
 */
export const adminDeletePayment = async (paymentUuid: string, options?: RequestInit): Promise<adminDeletePaymentResponse> => {

  return mutator<adminDeletePaymentResponse>(getAdminDeletePaymentUrl(paymentUuid),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getAdminDeletePaymentMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeletePayment>>, TError,{paymentUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminDeletePayment>>, TError,{paymentUuid: string}, TContext> => {

const mutationKey = ['adminDeletePayment'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminDeletePayment>>, {paymentUuid: string}> = (props) => {
          const {paymentUuid} = props ?? {};

          return  adminDeletePayment(paymentUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminDeletePaymentMutationResult = NonNullable<Awaited<ReturnType<typeof adminDeletePayment>>>

    export type AdminDeletePaymentMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Payment
 */
export const useAdminDeletePayment = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeletePayment>>, TError,{paymentUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminDeletePayment>>,
        TError,
        {paymentUuid: string},
        TContext
      > => {
      return useMutation(getAdminDeletePaymentMutationOptions(options), queryClient);
    }
