/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddExtraMaterialRequest,
  AdminListProductionItemsParams,
  AdvanceProductionItemRequest,
  CancelProductionItemRequest,
  CompleteProductionStepRequest,
  CreateProductionItemRequest,
  HTTPValidationError,
  ProductionItemDetail,
  ProductionItemList,
  UpdateTestingRequest
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type adminListProductionItemsResponse200 = {
  data: ProductionItemList
  status: 200
}

export type adminListProductionItemsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListProductionItemsResponseSuccess = (adminListProductionItemsResponse200) & {
  headers: Headers;
};
export type adminListProductionItemsResponseError = (adminListProductionItemsResponse422) & {
  headers: Headers;
};

export type adminListProductionItemsResponse = (adminListProductionItemsResponseSuccess | adminListProductionItemsResponseError)

export const getAdminListProductionItemsUrl = (params?: AdminListProductionItemsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/production/items?${stringifiedParams}` : `/api/v1/admin/production/items`
}

/**
 * @summary List Production Items
 */
export const adminListProductionItems = async (params?: AdminListProductionItemsParams, options?: RequestInit): Promise<adminListProductionItemsResponse> => {

  return mutator<adminListProductionItemsResponse>(getAdminListProductionItemsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListProductionItemsQueryKey = (params?: AdminListProductionItemsParams,) => {
    return [
    `/api/v1/admin/production/items`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListProductionItemsQueryOptions = <TData = Awaited<ReturnType<typeof adminListProductionItems>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListProductionItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListProductionItems>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListProductionItemsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListProductionItems>>> = ({ signal }) => adminListProductionItems(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListProductionItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListProductionItemsQueryResult = NonNullable<Awaited<ReturnType<typeof adminListProductionItems>>>
export type AdminListProductionItemsQueryError = ErrorType<HTTPValidationError>


export function useAdminListProductionItems<TData = Awaited<ReturnType<typeof adminListProductionItems>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListProductionItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListProductionItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListProductionItems>>,
          TError,
          Awaited<ReturnType<typeof adminListProductionItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListProductionItems<TData = Awaited<ReturnType<typeof adminListProductionItems>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListProductionItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListProductionItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListProductionItems>>,
          TError,
          Awaited<ReturnType<typeof adminListProductionItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListProductionItems<TData = Awaited<ReturnType<typeof adminListProductionItems>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListProductionItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListProductionItems>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Production Items
 */

export function useAdminListProductionItems<TData = Awaited<ReturnType<typeof adminListProductionItems>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListProductionItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListProductionItems>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListProductionItemsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminCreateProductionItemResponse201 = {
  data: ProductionItemDetail
  status: 201
}

export type adminCreateProductionItemResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCreateProductionItemResponseSuccess = (adminCreateProductionItemResponse201) & {
  headers: Headers;
};
export type adminCreateProductionItemResponseError = (adminCreateProductionItemResponse422) & {
  headers: Headers;
};

export type adminCreateProductionItemResponse = (adminCreateProductionItemResponseSuccess | adminCreateProductionItemResponseError)

export const getAdminCreateProductionItemUrl = () => {




  return `/api/v1/admin/production/items`
}

/**
 * @summary Create Production Item
 */
export const adminCreateProductionItem = async (createProductionItemRequest: CreateProductionItemRequest, options?: RequestInit): Promise<adminCreateProductionItemResponse> => {

  return mutator<adminCreateProductionItemResponse>(getAdminCreateProductionItemUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createProductionItemRequest)
  }
);}




export const getAdminCreateProductionItemMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateProductionItem>>, TError,{data: BodyType<CreateProductionItemRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateProductionItem>>, TError,{data: BodyType<CreateProductionItemRequest>}, TContext> => {

const mutationKey = ['adminCreateProductionItem'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateProductionItem>>, {data: BodyType<CreateProductionItemRequest>}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateProductionItem(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateProductionItemMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateProductionItem>>>
    export type AdminCreateProductionItemMutationBody = BodyType<CreateProductionItemRequest>
    export type AdminCreateProductionItemMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Production Item
 */
export const useAdminCreateProductionItem = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateProductionItem>>, TError,{data: BodyType<CreateProductionItemRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateProductionItem>>,
        TError,
        {data: BodyType<CreateProductionItemRequest>},
        TContext
      > => {
      return useMutation(getAdminCreateProductionItemMutationOptions(options), queryClient);
    }
    export type adminGetProductionItemResponse200 = {
  data: ProductionItemDetail
  status: 200
}

export type adminGetProductionItemResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminGetProductionItemResponseSuccess = (adminGetProductionItemResponse200) & {
  headers: Headers;
};
export type adminGetProductionItemResponseError = (adminGetProductionItemResponse422) & {
  headers: Headers;
};

export type adminGetProductionItemResponse = (adminGetProductionItemResponseSuccess | adminGetProductionItemResponseError)

export const getAdminGetProductionItemUrl = (itemUuid: string,) => {




  return `/api/v1/admin/production/items/${itemUuid}`
}

/**
 * @summary Get Production Item
 */
export const adminGetProductionItem = async (itemUuid: string, options?: RequestInit): Promise<adminGetProductionItemResponse> => {

  return mutator<adminGetProductionItemResponse>(getAdminGetProductionItemUrl(itemUuid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminGetProductionItemQueryKey = (itemUuid: string,) => {
    return [
    `/api/v1/admin/production/items/${itemUuid}`
    ] as const;
    }


export const getAdminGetProductionItemQueryOptions = <TData = Awaited<ReturnType<typeof adminGetProductionItem>>, TError = ErrorType<HTTPValidationError>>(itemUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetProductionItem>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetProductionItemQueryKey(itemUuid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetProductionItem>>> = ({ signal }) => adminGetProductionItem(itemUuid, { signal });





   return  { queryKey, queryFn, enabled: itemUuid !== null && itemUuid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetProductionItem>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetProductionItemQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetProductionItem>>>
export type AdminGetProductionItemQueryError = ErrorType<HTTPValidationError>


export function useAdminGetProductionItem<TData = Awaited<ReturnType<typeof adminGetProductionItem>>, TError = ErrorType<HTTPValidationError>>(
 itemUuid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetProductionItem>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetProductionItem>>,
          TError,
          Awaited<ReturnType<typeof adminGetProductionItem>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetProductionItem<TData = Awaited<ReturnType<typeof adminGetProductionItem>>, TError = ErrorType<HTTPValidationError>>(
 itemUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetProductionItem>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetProductionItem>>,
          TError,
          Awaited<ReturnType<typeof adminGetProductionItem>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetProductionItem<TData = Awaited<ReturnType<typeof adminGetProductionItem>>, TError = ErrorType<HTTPValidationError>>(
 itemUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetProductionItem>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Production Item
 */

export function useAdminGetProductionItem<TData = Awaited<ReturnType<typeof adminGetProductionItem>>, TError = ErrorType<HTTPValidationError>>(
 itemUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetProductionItem>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminGetProductionItemQueryOptions(itemUuid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminAdvanceProductionItemResponse200 = {
  data: ProductionItemDetail
  status: 200
}

export type adminAdvanceProductionItemResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminAdvanceProductionItemResponseSuccess = (adminAdvanceProductionItemResponse200) & {
  headers: Headers;
};
export type adminAdvanceProductionItemResponseError = (adminAdvanceProductionItemResponse422) & {
  headers: Headers;
};

export type adminAdvanceProductionItemResponse = (adminAdvanceProductionItemResponseSuccess | adminAdvanceProductionItemResponseError)

export const getAdminAdvanceProductionItemUrl = (itemUuid: string,) => {




  return `/api/v1/admin/production/items/${itemUuid}/advance`
}

/**
 * @summary Advance Production Item
 */
export const adminAdvanceProductionItem = async (itemUuid: string,
    advanceProductionItemRequest: AdvanceProductionItemRequest, options?: RequestInit): Promise<adminAdvanceProductionItemResponse> => {

  return mutator<adminAdvanceProductionItemResponse>(getAdminAdvanceProductionItemUrl(itemUuid),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(advanceProductionItemRequest)
  }
);}




export const getAdminAdvanceProductionItemMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAdvanceProductionItem>>, TError,{itemUuid: string;data: BodyType<AdvanceProductionItemRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminAdvanceProductionItem>>, TError,{itemUuid: string;data: BodyType<AdvanceProductionItemRequest>}, TContext> => {

const mutationKey = ['adminAdvanceProductionItem'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminAdvanceProductionItem>>, {itemUuid: string;data: BodyType<AdvanceProductionItemRequest>}> = (props) => {
          const {itemUuid,data} = props ?? {};

          return  adminAdvanceProductionItem(itemUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminAdvanceProductionItemMutationResult = NonNullable<Awaited<ReturnType<typeof adminAdvanceProductionItem>>>
    export type AdminAdvanceProductionItemMutationBody = BodyType<AdvanceProductionItemRequest>
    export type AdminAdvanceProductionItemMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Advance Production Item
 */
export const useAdminAdvanceProductionItem = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAdvanceProductionItem>>, TError,{itemUuid: string;data: BodyType<AdvanceProductionItemRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminAdvanceProductionItem>>,
        TError,
        {itemUuid: string;data: BodyType<AdvanceProductionItemRequest>},
        TContext
      > => {
      return useMutation(getAdminAdvanceProductionItemMutationOptions(options), queryClient);
    }
    export type adminCompleteProductionStepResponse200 = {
  data: ProductionItemDetail
  status: 200
}

export type adminCompleteProductionStepResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCompleteProductionStepResponseSuccess = (adminCompleteProductionStepResponse200) & {
  headers: Headers;
};
export type adminCompleteProductionStepResponseError = (adminCompleteProductionStepResponse422) & {
  headers: Headers;
};

export type adminCompleteProductionStepResponse = (adminCompleteProductionStepResponseSuccess | adminCompleteProductionStepResponseError)

export const getAdminCompleteProductionStepUrl = (itemUuid: string,) => {




  return `/api/v1/admin/production/items/${itemUuid}/complete-step`
}

/**
 * Complete the item's first PENDING production step (feature 072).

Strict order; RM Issue consumes the order's reserved raw material; the
last step auto-advances the item to TESTING.
 * @summary Complete Production Step
 */
export const adminCompleteProductionStep = async (itemUuid: string,
    completeProductionStepRequest: CompleteProductionStepRequest, options?: RequestInit): Promise<adminCompleteProductionStepResponse> => {

  return mutator<adminCompleteProductionStepResponse>(getAdminCompleteProductionStepUrl(itemUuid),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(completeProductionStepRequest)
  }
);}




export const getAdminCompleteProductionStepMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCompleteProductionStep>>, TError,{itemUuid: string;data: BodyType<CompleteProductionStepRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCompleteProductionStep>>, TError,{itemUuid: string;data: BodyType<CompleteProductionStepRequest>}, TContext> => {

const mutationKey = ['adminCompleteProductionStep'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCompleteProductionStep>>, {itemUuid: string;data: BodyType<CompleteProductionStepRequest>}> = (props) => {
          const {itemUuid,data} = props ?? {};

          return  adminCompleteProductionStep(itemUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCompleteProductionStepMutationResult = NonNullable<Awaited<ReturnType<typeof adminCompleteProductionStep>>>
    export type AdminCompleteProductionStepMutationBody = BodyType<CompleteProductionStepRequest>
    export type AdminCompleteProductionStepMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Complete Production Step
 */
export const useAdminCompleteProductionStep = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCompleteProductionStep>>, TError,{itemUuid: string;data: BodyType<CompleteProductionStepRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCompleteProductionStep>>,
        TError,
        {itemUuid: string;data: BodyType<CompleteProductionStepRequest>},
        TContext
      > => {
      return useMutation(getAdminCompleteProductionStepMutationOptions(options), queryClient);
    }
    export type adminUpdateProductionTestingResponse200 = {
  data: ProductionItemDetail
  status: 200
}

export type adminUpdateProductionTestingResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminUpdateProductionTestingResponseSuccess = (adminUpdateProductionTestingResponse200) & {
  headers: Headers;
};
export type adminUpdateProductionTestingResponseError = (adminUpdateProductionTestingResponse422) & {
  headers: Headers;
};

export type adminUpdateProductionTestingResponse = (adminUpdateProductionTestingResponseSuccess | adminUpdateProductionTestingResponseError)

export const getAdminUpdateProductionTestingUrl = (itemUuid: string,) => {




  return `/api/v1/admin/production/items/${itemUuid}/testing`
}

/**
 * @summary Update Production Testing
 */
export const adminUpdateProductionTesting = async (itemUuid: string,
    updateTestingRequest: UpdateTestingRequest, options?: RequestInit): Promise<adminUpdateProductionTestingResponse> => {

  return mutator<adminUpdateProductionTestingResponse>(getAdminUpdateProductionTestingUrl(itemUuid),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateTestingRequest)
  }
);}




export const getAdminUpdateProductionTestingMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateProductionTesting>>, TError,{itemUuid: string;data: BodyType<UpdateTestingRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateProductionTesting>>, TError,{itemUuid: string;data: BodyType<UpdateTestingRequest>}, TContext> => {

const mutationKey = ['adminUpdateProductionTesting'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateProductionTesting>>, {itemUuid: string;data: BodyType<UpdateTestingRequest>}> = (props) => {
          const {itemUuid,data} = props ?? {};

          return  adminUpdateProductionTesting(itemUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateProductionTestingMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateProductionTesting>>>
    export type AdminUpdateProductionTestingMutationBody = BodyType<UpdateTestingRequest>
    export type AdminUpdateProductionTestingMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Production Testing
 */
export const useAdminUpdateProductionTesting = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateProductionTesting>>, TError,{itemUuid: string;data: BodyType<UpdateTestingRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateProductionTesting>>,
        TError,
        {itemUuid: string;data: BodyType<UpdateTestingRequest>},
        TContext
      > => {
      return useMutation(getAdminUpdateProductionTestingMutationOptions(options), queryClient);
    }
    export type adminCancelProductionItemResponse200 = {
  data: ProductionItemDetail
  status: 200
}

export type adminCancelProductionItemResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCancelProductionItemResponseSuccess = (adminCancelProductionItemResponse200) & {
  headers: Headers;
};
export type adminCancelProductionItemResponseError = (adminCancelProductionItemResponse422) & {
  headers: Headers;
};

export type adminCancelProductionItemResponse = (adminCancelProductionItemResponseSuccess | adminCancelProductionItemResponseError)

export const getAdminCancelProductionItemUrl = (itemUuid: string,) => {




  return `/api/v1/admin/production/items/${itemUuid}/cancel`
}

/**
 * @summary Cancel Production Item
 */
export const adminCancelProductionItem = async (itemUuid: string,
    cancelProductionItemRequest: CancelProductionItemRequest, options?: RequestInit): Promise<adminCancelProductionItemResponse> => {

  return mutator<adminCancelProductionItemResponse>(getAdminCancelProductionItemUrl(itemUuid),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(cancelProductionItemRequest)
  }
);}




export const getAdminCancelProductionItemMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCancelProductionItem>>, TError,{itemUuid: string;data: BodyType<CancelProductionItemRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCancelProductionItem>>, TError,{itemUuid: string;data: BodyType<CancelProductionItemRequest>}, TContext> => {

const mutationKey = ['adminCancelProductionItem'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCancelProductionItem>>, {itemUuid: string;data: BodyType<CancelProductionItemRequest>}> = (props) => {
          const {itemUuid,data} = props ?? {};

          return  adminCancelProductionItem(itemUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCancelProductionItemMutationResult = NonNullable<Awaited<ReturnType<typeof adminCancelProductionItem>>>
    export type AdminCancelProductionItemMutationBody = BodyType<CancelProductionItemRequest>
    export type AdminCancelProductionItemMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Cancel Production Item
 */
export const useAdminCancelProductionItem = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCancelProductionItem>>, TError,{itemUuid: string;data: BodyType<CancelProductionItemRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCancelProductionItem>>,
        TError,
        {itemUuid: string;data: BodyType<CancelProductionItemRequest>},
        TContext
      > => {
      return useMutation(getAdminCancelProductionItemMutationOptions(options), queryClient);
    }
    export type adminRevertProductionCompletionResponse200 = {
  data: ProductionItemDetail
  status: 200
}

export type adminRevertProductionCompletionResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminRevertProductionCompletionResponseSuccess = (adminRevertProductionCompletionResponse200) & {
  headers: Headers;
};
export type adminRevertProductionCompletionResponseError = (adminRevertProductionCompletionResponse422) & {
  headers: Headers;
};

export type adminRevertProductionCompletionResponse = (adminRevertProductionCompletionResponseSuccess | adminRevertProductionCompletionResponseError)

export const getAdminRevertProductionCompletionUrl = (itemUuid: string,) => {




  return `/api/v1/admin/production/items/${itemUuid}/revert-completion`
}

/**
 * Undo an accidental completion while the posted FG stock is untouched.
 * @summary Revert Production Completion
 */
export const adminRevertProductionCompletion = async (itemUuid: string, options?: RequestInit): Promise<adminRevertProductionCompletionResponse> => {

  return mutator<adminRevertProductionCompletionResponse>(getAdminRevertProductionCompletionUrl(itemUuid),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminRevertProductionCompletionMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminRevertProductionCompletion>>, TError,{itemUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminRevertProductionCompletion>>, TError,{itemUuid: string}, TContext> => {

const mutationKey = ['adminRevertProductionCompletion'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminRevertProductionCompletion>>, {itemUuid: string}> = (props) => {
          const {itemUuid} = props ?? {};

          return  adminRevertProductionCompletion(itemUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminRevertProductionCompletionMutationResult = NonNullable<Awaited<ReturnType<typeof adminRevertProductionCompletion>>>

    export type AdminRevertProductionCompletionMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Revert Production Completion
 */
export const useAdminRevertProductionCompletion = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminRevertProductionCompletion>>, TError,{itemUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminRevertProductionCompletion>>,
        TError,
        {itemUuid: string},
        TContext
      > => {
      return useMutation(getAdminRevertProductionCompletionMutationOptions(options), queryClient);
    }
    export type adminAddProductionExtraMaterialResponse200 = {
  data: ProductionItemDetail
  status: 200
}

export type adminAddProductionExtraMaterialResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminAddProductionExtraMaterialResponseSuccess = (adminAddProductionExtraMaterialResponse200) & {
  headers: Headers;
};
export type adminAddProductionExtraMaterialResponseError = (adminAddProductionExtraMaterialResponse422) & {
  headers: Headers;
};

export type adminAddProductionExtraMaterialResponse = (adminAddProductionExtraMaterialResponseSuccess | adminAddProductionExtraMaterialResponseError)

export const getAdminAddProductionExtraMaterialUrl = (itemUuid: string,) => {




  return `/api/v1/admin/production/items/${itemUuid}/extra-materials`
}

/**
 * @summary Add Production Extra Material
 */
export const adminAddProductionExtraMaterial = async (itemUuid: string,
    addExtraMaterialRequest: AddExtraMaterialRequest, options?: RequestInit): Promise<adminAddProductionExtraMaterialResponse> => {

  return mutator<adminAddProductionExtraMaterialResponse>(getAdminAddProductionExtraMaterialUrl(itemUuid),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addExtraMaterialRequest)
  }
);}




export const getAdminAddProductionExtraMaterialMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAddProductionExtraMaterial>>, TError,{itemUuid: string;data: BodyType<AddExtraMaterialRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminAddProductionExtraMaterial>>, TError,{itemUuid: string;data: BodyType<AddExtraMaterialRequest>}, TContext> => {

const mutationKey = ['adminAddProductionExtraMaterial'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminAddProductionExtraMaterial>>, {itemUuid: string;data: BodyType<AddExtraMaterialRequest>}> = (props) => {
          const {itemUuid,data} = props ?? {};

          return  adminAddProductionExtraMaterial(itemUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminAddProductionExtraMaterialMutationResult = NonNullable<Awaited<ReturnType<typeof adminAddProductionExtraMaterial>>>
    export type AdminAddProductionExtraMaterialMutationBody = BodyType<AddExtraMaterialRequest>
    export type AdminAddProductionExtraMaterialMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Add Production Extra Material
 */
export const useAdminAddProductionExtraMaterial = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAddProductionExtraMaterial>>, TError,{itemUuid: string;data: BodyType<AddExtraMaterialRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminAddProductionExtraMaterial>>,
        TError,
        {itemUuid: string;data: BodyType<AddExtraMaterialRequest>},
        TContext
      > => {
      return useMutation(getAdminAddProductionExtraMaterialMutationOptions(options), queryClient);
    }
    export type adminRemoveProductionExtraMaterialResponse200 = {
  data: ProductionItemDetail
  status: 200
}

export type adminRemoveProductionExtraMaterialResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminRemoveProductionExtraMaterialResponseSuccess = (adminRemoveProductionExtraMaterialResponse200) & {
  headers: Headers;
};
export type adminRemoveProductionExtraMaterialResponseError = (adminRemoveProductionExtraMaterialResponse422) & {
  headers: Headers;
};

export type adminRemoveProductionExtraMaterialResponse = (adminRemoveProductionExtraMaterialResponseSuccess | adminRemoveProductionExtraMaterialResponseError)

export const getAdminRemoveProductionExtraMaterialUrl = (itemUuid: string,
    extraGroup: string,) => {




  return `/api/v1/admin/production/items/${itemUuid}/extra-materials/${extraGroup}`
}

/**
 * @summary Remove Production Extra Material
 */
export const adminRemoveProductionExtraMaterial = async (itemUuid: string,
    extraGroup: string, options?: RequestInit): Promise<adminRemoveProductionExtraMaterialResponse> => {

  return mutator<adminRemoveProductionExtraMaterialResponse>(getAdminRemoveProductionExtraMaterialUrl(itemUuid,extraGroup),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getAdminRemoveProductionExtraMaterialMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminRemoveProductionExtraMaterial>>, TError,{itemUuid: string;extraGroup: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminRemoveProductionExtraMaterial>>, TError,{itemUuid: string;extraGroup: string}, TContext> => {

const mutationKey = ['adminRemoveProductionExtraMaterial'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminRemoveProductionExtraMaterial>>, {itemUuid: string;extraGroup: string}> = (props) => {
          const {itemUuid,extraGroup} = props ?? {};

          return  adminRemoveProductionExtraMaterial(itemUuid,extraGroup,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminRemoveProductionExtraMaterialMutationResult = NonNullable<Awaited<ReturnType<typeof adminRemoveProductionExtraMaterial>>>

    export type AdminRemoveProductionExtraMaterialMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Remove Production Extra Material
 */
export const useAdminRemoveProductionExtraMaterial = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminRemoveProductionExtraMaterial>>, TError,{itemUuid: string;extraGroup: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminRemoveProductionExtraMaterial>>,
        TError,
        {itemUuid: string;extraGroup: string},
        TContext
      > => {
      return useMutation(getAdminRemoveProductionExtraMaterialMutationOptions(options), queryClient);
    }
