/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddPoFollowupRequest,
  AdminListMyPurchaseFollowupsParams,
  AdminListPurchaseOrdersParams,
  CreatePurchaseOrderRequest,
  HTTPValidationError,
  PoMyFollowupList,
  PurchaseOrderDetail,
  PurchaseOrderList,
  UpdatePurchaseOrderRequest
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type adminListMyPurchaseFollowupsResponse200 = {
  data: PoMyFollowupList
  status: 200
}

export type adminListMyPurchaseFollowupsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListMyPurchaseFollowupsResponseSuccess = (adminListMyPurchaseFollowupsResponse200) & {
  headers: Headers;
};
export type adminListMyPurchaseFollowupsResponseError = (adminListMyPurchaseFollowupsResponse422) & {
  headers: Headers;
};

export type adminListMyPurchaseFollowupsResponse = (adminListMyPurchaseFollowupsResponseSuccess | adminListMyPurchaseFollowupsResponseError)

export const getAdminListMyPurchaseFollowupsUrl = (params?: AdminListMyPurchaseFollowupsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/purchasing/my-followups?${stringifiedParams}` : `/api/v1/admin/purchasing/my-followups`
}

/**
 * @summary List My Purchase Followups
 */
export const adminListMyPurchaseFollowups = async (params?: AdminListMyPurchaseFollowupsParams, options?: RequestInit): Promise<adminListMyPurchaseFollowupsResponse> => {

  return mutator<adminListMyPurchaseFollowupsResponse>(getAdminListMyPurchaseFollowupsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListMyPurchaseFollowupsQueryKey = (params?: AdminListMyPurchaseFollowupsParams,) => {
    return [
    `/api/v1/admin/purchasing/my-followups`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListMyPurchaseFollowupsQueryOptions = <TData = Awaited<ReturnType<typeof adminListMyPurchaseFollowups>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListMyPurchaseFollowupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMyPurchaseFollowups>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListMyPurchaseFollowupsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListMyPurchaseFollowups>>> = ({ signal }) => adminListMyPurchaseFollowups(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListMyPurchaseFollowups>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListMyPurchaseFollowupsQueryResult = NonNullable<Awaited<ReturnType<typeof adminListMyPurchaseFollowups>>>
export type AdminListMyPurchaseFollowupsQueryError = ErrorType<HTTPValidationError>


export function useAdminListMyPurchaseFollowups<TData = Awaited<ReturnType<typeof adminListMyPurchaseFollowups>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListMyPurchaseFollowupsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMyPurchaseFollowups>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListMyPurchaseFollowups>>,
          TError,
          Awaited<ReturnType<typeof adminListMyPurchaseFollowups>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListMyPurchaseFollowups<TData = Awaited<ReturnType<typeof adminListMyPurchaseFollowups>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListMyPurchaseFollowupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMyPurchaseFollowups>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListMyPurchaseFollowups>>,
          TError,
          Awaited<ReturnType<typeof adminListMyPurchaseFollowups>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListMyPurchaseFollowups<TData = Awaited<ReturnType<typeof adminListMyPurchaseFollowups>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListMyPurchaseFollowupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMyPurchaseFollowups>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List My Purchase Followups
 */

export function useAdminListMyPurchaseFollowups<TData = Awaited<ReturnType<typeof adminListMyPurchaseFollowups>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListMyPurchaseFollowupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMyPurchaseFollowups>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListMyPurchaseFollowupsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminMarkPurchaseFollowupDoneResponse200 = {
  data: PurchaseOrderDetail
  status: 200
}

export type adminMarkPurchaseFollowupDoneResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminMarkPurchaseFollowupDoneResponseSuccess = (adminMarkPurchaseFollowupDoneResponse200) & {
  headers: Headers;
};
export type adminMarkPurchaseFollowupDoneResponseError = (adminMarkPurchaseFollowupDoneResponse422) & {
  headers: Headers;
};

export type adminMarkPurchaseFollowupDoneResponse = (adminMarkPurchaseFollowupDoneResponseSuccess | adminMarkPurchaseFollowupDoneResponseError)

export const getAdminMarkPurchaseFollowupDoneUrl = (followupUuid: string,) => {




  return `/api/v1/admin/purchasing/followups/${followupUuid}/done`
}

/**
 * @summary Mark Purchase Followup Done
 */
export const adminMarkPurchaseFollowupDone = async (followupUuid: string, options?: RequestInit): Promise<adminMarkPurchaseFollowupDoneResponse> => {

  return mutator<adminMarkPurchaseFollowupDoneResponse>(getAdminMarkPurchaseFollowupDoneUrl(followupUuid),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminMarkPurchaseFollowupDoneMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminMarkPurchaseFollowupDone>>, TError,{followupUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminMarkPurchaseFollowupDone>>, TError,{followupUuid: string}, TContext> => {

const mutationKey = ['adminMarkPurchaseFollowupDone'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminMarkPurchaseFollowupDone>>, {followupUuid: string}> = (props) => {
          const {followupUuid} = props ?? {};

          return  adminMarkPurchaseFollowupDone(followupUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminMarkPurchaseFollowupDoneMutationResult = NonNullable<Awaited<ReturnType<typeof adminMarkPurchaseFollowupDone>>>

    export type AdminMarkPurchaseFollowupDoneMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Mark Purchase Followup Done
 */
export const useAdminMarkPurchaseFollowupDone = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminMarkPurchaseFollowupDone>>, TError,{followupUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminMarkPurchaseFollowupDone>>,
        TError,
        {followupUuid: string},
        TContext
      > => {
      return useMutation(getAdminMarkPurchaseFollowupDoneMutationOptions(options), queryClient);
    }
    export type adminListPurchaseOrdersResponse200 = {
  data: PurchaseOrderList
  status: 200
}

export type adminListPurchaseOrdersResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListPurchaseOrdersResponseSuccess = (adminListPurchaseOrdersResponse200) & {
  headers: Headers;
};
export type adminListPurchaseOrdersResponseError = (adminListPurchaseOrdersResponse422) & {
  headers: Headers;
};

export type adminListPurchaseOrdersResponse = (adminListPurchaseOrdersResponseSuccess | adminListPurchaseOrdersResponseError)

export const getAdminListPurchaseOrdersUrl = (params?: AdminListPurchaseOrdersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/purchasing/purchase-orders?${stringifiedParams}` : `/api/v1/admin/purchasing/purchase-orders`
}

/**
 * @summary List Purchase Orders
 */
export const adminListPurchaseOrders = async (params?: AdminListPurchaseOrdersParams, options?: RequestInit): Promise<adminListPurchaseOrdersResponse> => {

  return mutator<adminListPurchaseOrdersResponse>(getAdminListPurchaseOrdersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListPurchaseOrdersQueryKey = (params?: AdminListPurchaseOrdersParams,) => {
    return [
    `/api/v1/admin/purchasing/purchase-orders`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListPurchaseOrdersQueryOptions = <TData = Awaited<ReturnType<typeof adminListPurchaseOrders>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListPurchaseOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPurchaseOrders>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListPurchaseOrdersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListPurchaseOrders>>> = ({ signal }) => adminListPurchaseOrders(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListPurchaseOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListPurchaseOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof adminListPurchaseOrders>>>
export type AdminListPurchaseOrdersQueryError = ErrorType<HTTPValidationError>


export function useAdminListPurchaseOrders<TData = Awaited<ReturnType<typeof adminListPurchaseOrders>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListPurchaseOrdersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPurchaseOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListPurchaseOrders>>,
          TError,
          Awaited<ReturnType<typeof adminListPurchaseOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListPurchaseOrders<TData = Awaited<ReturnType<typeof adminListPurchaseOrders>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListPurchaseOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPurchaseOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListPurchaseOrders>>,
          TError,
          Awaited<ReturnType<typeof adminListPurchaseOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListPurchaseOrders<TData = Awaited<ReturnType<typeof adminListPurchaseOrders>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListPurchaseOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPurchaseOrders>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Purchase Orders
 */

export function useAdminListPurchaseOrders<TData = Awaited<ReturnType<typeof adminListPurchaseOrders>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListPurchaseOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPurchaseOrders>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListPurchaseOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminCreatePurchaseOrderResponse201 = {
  data: PurchaseOrderDetail
  status: 201
}

export type adminCreatePurchaseOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCreatePurchaseOrderResponseSuccess = (adminCreatePurchaseOrderResponse201) & {
  headers: Headers;
};
export type adminCreatePurchaseOrderResponseError = (adminCreatePurchaseOrderResponse422) & {
  headers: Headers;
};

export type adminCreatePurchaseOrderResponse = (adminCreatePurchaseOrderResponseSuccess | adminCreatePurchaseOrderResponseError)

export const getAdminCreatePurchaseOrderUrl = () => {




  return `/api/v1/admin/purchasing/purchase-orders`
}

/**
 * @summary Create Purchase Order
 */
export const adminCreatePurchaseOrder = async (createPurchaseOrderRequest: CreatePurchaseOrderRequest, options?: RequestInit): Promise<adminCreatePurchaseOrderResponse> => {

  return mutator<adminCreatePurchaseOrderResponse>(getAdminCreatePurchaseOrderUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPurchaseOrderRequest)
  }
);}




export const getAdminCreatePurchaseOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreatePurchaseOrder>>, TError,{data: BodyType<CreatePurchaseOrderRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCreatePurchaseOrder>>, TError,{data: BodyType<CreatePurchaseOrderRequest>}, TContext> => {

const mutationKey = ['adminCreatePurchaseOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreatePurchaseOrder>>, {data: BodyType<CreatePurchaseOrderRequest>}> = (props) => {
          const {data} = props ?? {};

          return  adminCreatePurchaseOrder(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCreatePurchaseOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreatePurchaseOrder>>>
    export type AdminCreatePurchaseOrderMutationBody = BodyType<CreatePurchaseOrderRequest>
    export type AdminCreatePurchaseOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Purchase Order
 */
export const useAdminCreatePurchaseOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreatePurchaseOrder>>, TError,{data: BodyType<CreatePurchaseOrderRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreatePurchaseOrder>>,
        TError,
        {data: BodyType<CreatePurchaseOrderRequest>},
        TContext
      > => {
      return useMutation(getAdminCreatePurchaseOrderMutationOptions(options), queryClient);
    }
    export type adminGetPurchaseOrderResponse200 = {
  data: PurchaseOrderDetail
  status: 200
}

export type adminGetPurchaseOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminGetPurchaseOrderResponseSuccess = (adminGetPurchaseOrderResponse200) & {
  headers: Headers;
};
export type adminGetPurchaseOrderResponseError = (adminGetPurchaseOrderResponse422) & {
  headers: Headers;
};

export type adminGetPurchaseOrderResponse = (adminGetPurchaseOrderResponseSuccess | adminGetPurchaseOrderResponseError)

export const getAdminGetPurchaseOrderUrl = (poUuid: string,) => {




  return `/api/v1/admin/purchasing/purchase-orders/${poUuid}`
}

/**
 * @summary Get Purchase Order
 */
export const adminGetPurchaseOrder = async (poUuid: string, options?: RequestInit): Promise<adminGetPurchaseOrderResponse> => {

  return mutator<adminGetPurchaseOrderResponse>(getAdminGetPurchaseOrderUrl(poUuid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminGetPurchaseOrderQueryKey = (poUuid: string,) => {
    return [
    `/api/v1/admin/purchasing/purchase-orders/${poUuid}`
    ] as const;
    }


export const getAdminGetPurchaseOrderQueryOptions = <TData = Awaited<ReturnType<typeof adminGetPurchaseOrder>>, TError = ErrorType<HTTPValidationError>>(poUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetPurchaseOrder>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetPurchaseOrderQueryKey(poUuid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetPurchaseOrder>>> = ({ signal }) => adminGetPurchaseOrder(poUuid, { signal });





   return  { queryKey, queryFn, enabled: poUuid !== null && poUuid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetPurchaseOrder>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetPurchaseOrderQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetPurchaseOrder>>>
export type AdminGetPurchaseOrderQueryError = ErrorType<HTTPValidationError>


export function useAdminGetPurchaseOrder<TData = Awaited<ReturnType<typeof adminGetPurchaseOrder>>, TError = ErrorType<HTTPValidationError>>(
 poUuid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetPurchaseOrder>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetPurchaseOrder>>,
          TError,
          Awaited<ReturnType<typeof adminGetPurchaseOrder>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetPurchaseOrder<TData = Awaited<ReturnType<typeof adminGetPurchaseOrder>>, TError = ErrorType<HTTPValidationError>>(
 poUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetPurchaseOrder>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetPurchaseOrder>>,
          TError,
          Awaited<ReturnType<typeof adminGetPurchaseOrder>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetPurchaseOrder<TData = Awaited<ReturnType<typeof adminGetPurchaseOrder>>, TError = ErrorType<HTTPValidationError>>(
 poUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetPurchaseOrder>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Purchase Order
 */

export function useAdminGetPurchaseOrder<TData = Awaited<ReturnType<typeof adminGetPurchaseOrder>>, TError = ErrorType<HTTPValidationError>>(
 poUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetPurchaseOrder>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminGetPurchaseOrderQueryOptions(poUuid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminUpdatePurchaseOrderResponse200 = {
  data: PurchaseOrderDetail
  status: 200
}

export type adminUpdatePurchaseOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminUpdatePurchaseOrderResponseSuccess = (adminUpdatePurchaseOrderResponse200) & {
  headers: Headers;
};
export type adminUpdatePurchaseOrderResponseError = (adminUpdatePurchaseOrderResponse422) & {
  headers: Headers;
};

export type adminUpdatePurchaseOrderResponse = (adminUpdatePurchaseOrderResponseSuccess | adminUpdatePurchaseOrderResponseError)

export const getAdminUpdatePurchaseOrderUrl = (poUuid: string,) => {




  return `/api/v1/admin/purchasing/purchase-orders/${poUuid}`
}

/**
 * @summary Update Purchase Order
 */
export const adminUpdatePurchaseOrder = async (poUuid: string,
    updatePurchaseOrderRequest: UpdatePurchaseOrderRequest, options?: RequestInit): Promise<adminUpdatePurchaseOrderResponse> => {

  return mutator<adminUpdatePurchaseOrderResponse>(getAdminUpdatePurchaseOrderUrl(poUuid),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePurchaseOrderRequest)
  }
);}




export const getAdminUpdatePurchaseOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdatePurchaseOrder>>, TError,{poUuid: string;data: BodyType<UpdatePurchaseOrderRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdatePurchaseOrder>>, TError,{poUuid: string;data: BodyType<UpdatePurchaseOrderRequest>}, TContext> => {

const mutationKey = ['adminUpdatePurchaseOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdatePurchaseOrder>>, {poUuid: string;data: BodyType<UpdatePurchaseOrderRequest>}> = (props) => {
          const {poUuid,data} = props ?? {};

          return  adminUpdatePurchaseOrder(poUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdatePurchaseOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdatePurchaseOrder>>>
    export type AdminUpdatePurchaseOrderMutationBody = BodyType<UpdatePurchaseOrderRequest>
    export type AdminUpdatePurchaseOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Purchase Order
 */
export const useAdminUpdatePurchaseOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdatePurchaseOrder>>, TError,{poUuid: string;data: BodyType<UpdatePurchaseOrderRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdatePurchaseOrder>>,
        TError,
        {poUuid: string;data: BodyType<UpdatePurchaseOrderRequest>},
        TContext
      > => {
      return useMutation(getAdminUpdatePurchaseOrderMutationOptions(options), queryClient);
    }
    export type adminDeletePurchaseOrderResponse204 = {
  data: void
  status: 204
}

export type adminDeletePurchaseOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminDeletePurchaseOrderResponseSuccess = (adminDeletePurchaseOrderResponse204) & {
  headers: Headers;
};
export type adminDeletePurchaseOrderResponseError = (adminDeletePurchaseOrderResponse422) & {
  headers: Headers;
};

export type adminDeletePurchaseOrderResponse = (adminDeletePurchaseOrderResponseSuccess | adminDeletePurchaseOrderResponseError)

export const getAdminDeletePurchaseOrderUrl = (poUuid: string,) => {




  return `/api/v1/admin/purchasing/purchase-orders/${poUuid}`
}

/**
 * @summary Delete Purchase Order
 */
export const adminDeletePurchaseOrder = async (poUuid: string, options?: RequestInit): Promise<adminDeletePurchaseOrderResponse> => {

  return mutator<adminDeletePurchaseOrderResponse>(getAdminDeletePurchaseOrderUrl(poUuid),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getAdminDeletePurchaseOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeletePurchaseOrder>>, TError,{poUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminDeletePurchaseOrder>>, TError,{poUuid: string}, TContext> => {

const mutationKey = ['adminDeletePurchaseOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminDeletePurchaseOrder>>, {poUuid: string}> = (props) => {
          const {poUuid} = props ?? {};

          return  adminDeletePurchaseOrder(poUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminDeletePurchaseOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminDeletePurchaseOrder>>>

    export type AdminDeletePurchaseOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Purchase Order
 */
export const useAdminDeletePurchaseOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeletePurchaseOrder>>, TError,{poUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminDeletePurchaseOrder>>,
        TError,
        {poUuid: string},
        TContext
      > => {
      return useMutation(getAdminDeletePurchaseOrderMutationOptions(options), queryClient);
    }
    export type adminPlacePurchaseOrderResponse200 = {
  data: PurchaseOrderDetail
  status: 200
}

export type adminPlacePurchaseOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminPlacePurchaseOrderResponseSuccess = (adminPlacePurchaseOrderResponse200) & {
  headers: Headers;
};
export type adminPlacePurchaseOrderResponseError = (adminPlacePurchaseOrderResponse422) & {
  headers: Headers;
};

export type adminPlacePurchaseOrderResponse = (adminPlacePurchaseOrderResponseSuccess | adminPlacePurchaseOrderResponseError)

export const getAdminPlacePurchaseOrderUrl = (poUuid: string,) => {




  return `/api/v1/admin/purchasing/purchase-orders/${poUuid}/place`
}

/**
 * @summary Place Purchase Order
 */
export const adminPlacePurchaseOrder = async (poUuid: string, options?: RequestInit): Promise<adminPlacePurchaseOrderResponse> => {

  return mutator<adminPlacePurchaseOrderResponse>(getAdminPlacePurchaseOrderUrl(poUuid),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminPlacePurchaseOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminPlacePurchaseOrder>>, TError,{poUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminPlacePurchaseOrder>>, TError,{poUuid: string}, TContext> => {

const mutationKey = ['adminPlacePurchaseOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminPlacePurchaseOrder>>, {poUuid: string}> = (props) => {
          const {poUuid} = props ?? {};

          return  adminPlacePurchaseOrder(poUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminPlacePurchaseOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminPlacePurchaseOrder>>>

    export type AdminPlacePurchaseOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Place Purchase Order
 */
export const useAdminPlacePurchaseOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminPlacePurchaseOrder>>, TError,{poUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminPlacePurchaseOrder>>,
        TError,
        {poUuid: string},
        TContext
      > => {
      return useMutation(getAdminPlacePurchaseOrderMutationOptions(options), queryClient);
    }
    export type adminCancelPurchaseOrderResponse200 = {
  data: PurchaseOrderDetail
  status: 200
}

export type adminCancelPurchaseOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCancelPurchaseOrderResponseSuccess = (adminCancelPurchaseOrderResponse200) & {
  headers: Headers;
};
export type adminCancelPurchaseOrderResponseError = (adminCancelPurchaseOrderResponse422) & {
  headers: Headers;
};

export type adminCancelPurchaseOrderResponse = (adminCancelPurchaseOrderResponseSuccess | adminCancelPurchaseOrderResponseError)

export const getAdminCancelPurchaseOrderUrl = (poUuid: string,) => {




  return `/api/v1/admin/purchasing/purchase-orders/${poUuid}/cancel`
}

/**
 * @summary Cancel Purchase Order
 */
export const adminCancelPurchaseOrder = async (poUuid: string, options?: RequestInit): Promise<adminCancelPurchaseOrderResponse> => {

  return mutator<adminCancelPurchaseOrderResponse>(getAdminCancelPurchaseOrderUrl(poUuid),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminCancelPurchaseOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCancelPurchaseOrder>>, TError,{poUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCancelPurchaseOrder>>, TError,{poUuid: string}, TContext> => {

const mutationKey = ['adminCancelPurchaseOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCancelPurchaseOrder>>, {poUuid: string}> = (props) => {
          const {poUuid} = props ?? {};

          return  adminCancelPurchaseOrder(poUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCancelPurchaseOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminCancelPurchaseOrder>>>

    export type AdminCancelPurchaseOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Cancel Purchase Order
 */
export const useAdminCancelPurchaseOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCancelPurchaseOrder>>, TError,{poUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCancelPurchaseOrder>>,
        TError,
        {poUuid: string},
        TContext
      > => {
      return useMutation(getAdminCancelPurchaseOrderMutationOptions(options), queryClient);
    }
    export type adminClosePurchaseOrderResponse200 = {
  data: PurchaseOrderDetail
  status: 200
}

export type adminClosePurchaseOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminClosePurchaseOrderResponseSuccess = (adminClosePurchaseOrderResponse200) & {
  headers: Headers;
};
export type adminClosePurchaseOrderResponseError = (adminClosePurchaseOrderResponse422) & {
  headers: Headers;
};

export type adminClosePurchaseOrderResponse = (adminClosePurchaseOrderResponseSuccess | adminClosePurchaseOrderResponseError)

export const getAdminClosePurchaseOrderUrl = (poUuid: string,) => {




  return `/api/v1/admin/purchasing/purchase-orders/${poUuid}/close`
}

/**
 * @summary Close Purchase Order
 */
export const adminClosePurchaseOrder = async (poUuid: string, options?: RequestInit): Promise<adminClosePurchaseOrderResponse> => {

  return mutator<adminClosePurchaseOrderResponse>(getAdminClosePurchaseOrderUrl(poUuid),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminClosePurchaseOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminClosePurchaseOrder>>, TError,{poUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminClosePurchaseOrder>>, TError,{poUuid: string}, TContext> => {

const mutationKey = ['adminClosePurchaseOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminClosePurchaseOrder>>, {poUuid: string}> = (props) => {
          const {poUuid} = props ?? {};

          return  adminClosePurchaseOrder(poUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminClosePurchaseOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminClosePurchaseOrder>>>

    export type AdminClosePurchaseOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Close Purchase Order
 */
export const useAdminClosePurchaseOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminClosePurchaseOrder>>, TError,{poUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminClosePurchaseOrder>>,
        TError,
        {poUuid: string},
        TContext
      > => {
      return useMutation(getAdminClosePurchaseOrderMutationOptions(options), queryClient);
    }
    export type adminAddPurchaseOrderFollowupResponse201 = {
  data: PurchaseOrderDetail
  status: 201
}

export type adminAddPurchaseOrderFollowupResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminAddPurchaseOrderFollowupResponseSuccess = (adminAddPurchaseOrderFollowupResponse201) & {
  headers: Headers;
};
export type adminAddPurchaseOrderFollowupResponseError = (adminAddPurchaseOrderFollowupResponse422) & {
  headers: Headers;
};

export type adminAddPurchaseOrderFollowupResponse = (adminAddPurchaseOrderFollowupResponseSuccess | adminAddPurchaseOrderFollowupResponseError)

export const getAdminAddPurchaseOrderFollowupUrl = (poUuid: string,) => {




  return `/api/v1/admin/purchasing/purchase-orders/${poUuid}/followups`
}

/**
 * @summary Add Purchase Order Followup
 */
export const adminAddPurchaseOrderFollowup = async (poUuid: string,
    addPoFollowupRequest: AddPoFollowupRequest, options?: RequestInit): Promise<adminAddPurchaseOrderFollowupResponse> => {

  return mutator<adminAddPurchaseOrderFollowupResponse>(getAdminAddPurchaseOrderFollowupUrl(poUuid),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addPoFollowupRequest)
  }
);}




export const getAdminAddPurchaseOrderFollowupMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAddPurchaseOrderFollowup>>, TError,{poUuid: string;data: BodyType<AddPoFollowupRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminAddPurchaseOrderFollowup>>, TError,{poUuid: string;data: BodyType<AddPoFollowupRequest>}, TContext> => {

const mutationKey = ['adminAddPurchaseOrderFollowup'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminAddPurchaseOrderFollowup>>, {poUuid: string;data: BodyType<AddPoFollowupRequest>}> = (props) => {
          const {poUuid,data} = props ?? {};

          return  adminAddPurchaseOrderFollowup(poUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminAddPurchaseOrderFollowupMutationResult = NonNullable<Awaited<ReturnType<typeof adminAddPurchaseOrderFollowup>>>
    export type AdminAddPurchaseOrderFollowupMutationBody = BodyType<AddPoFollowupRequest>
    export type AdminAddPurchaseOrderFollowupMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Add Purchase Order Followup
 */
export const useAdminAddPurchaseOrderFollowup = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAddPurchaseOrderFollowup>>, TError,{poUuid: string;data: BodyType<AddPoFollowupRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminAddPurchaseOrderFollowup>>,
        TError,
        {poUuid: string;data: BodyType<AddPoFollowupRequest>},
        TContext
      > => {
      return useMutation(getAdminAddPurchaseOrderFollowupMutationOptions(options), queryClient);
    }
