/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminDelayedManufacturingReportParams,
  AdminDoctorStatementParams,
  AdminExpiringBatchesReportParams,
  AdminExportDelayedManufacturingReportParams,
  AdminExportSalesPaymentsReportParams,
  AdminExportTopSellingReportParams,
  AdminSalesPaymentsReportParams,
  AdminTopSellingReportParams,
  DashboardInventoryStats,
  DashboardSummary,
  DelayedManufacturingReport,
  DoctorStatement,
  ExpiringBatchesReport,
  HTTPValidationError,
  LowStockReport,
  SalesPaymentsReport,
  TopSellingReport
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType } from '../api/sdk-mutator';





export type adminSalesPaymentsReportResponse200 = {
  data: SalesPaymentsReport
  status: 200
}

export type adminSalesPaymentsReportResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminSalesPaymentsReportResponseSuccess = (adminSalesPaymentsReportResponse200) & {
  headers: Headers;
};
export type adminSalesPaymentsReportResponseError = (adminSalesPaymentsReportResponse422) & {
  headers: Headers;
};

export type adminSalesPaymentsReportResponse = (adminSalesPaymentsReportResponseSuccess | adminSalesPaymentsReportResponseError)

export const getAdminSalesPaymentsReportUrl = (params?: AdminSalesPaymentsReportParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/reports/sales-payments?${stringifiedParams}` : `/api/v1/admin/reports/sales-payments`
}

/**
 * @summary Sales Payments Report
 */
export const adminSalesPaymentsReport = async (params?: AdminSalesPaymentsReportParams, options?: RequestInit): Promise<adminSalesPaymentsReportResponse> => {

  return mutator<adminSalesPaymentsReportResponse>(getAdminSalesPaymentsReportUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminSalesPaymentsReportQueryKey = (params?: AdminSalesPaymentsReportParams,) => {
    return [
    `/api/v1/admin/reports/sales-payments`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminSalesPaymentsReportQueryOptions = <TData = Awaited<ReturnType<typeof adminSalesPaymentsReport>>, TError = ErrorType<HTTPValidationError>>(params?: AdminSalesPaymentsReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminSalesPaymentsReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminSalesPaymentsReportQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminSalesPaymentsReport>>> = ({ signal }) => adminSalesPaymentsReport(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminSalesPaymentsReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminSalesPaymentsReportQueryResult = NonNullable<Awaited<ReturnType<typeof adminSalesPaymentsReport>>>
export type AdminSalesPaymentsReportQueryError = ErrorType<HTTPValidationError>


export function useAdminSalesPaymentsReport<TData = Awaited<ReturnType<typeof adminSalesPaymentsReport>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminSalesPaymentsReportParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminSalesPaymentsReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminSalesPaymentsReport>>,
          TError,
          Awaited<ReturnType<typeof adminSalesPaymentsReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminSalesPaymentsReport<TData = Awaited<ReturnType<typeof adminSalesPaymentsReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminSalesPaymentsReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminSalesPaymentsReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminSalesPaymentsReport>>,
          TError,
          Awaited<ReturnType<typeof adminSalesPaymentsReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminSalesPaymentsReport<TData = Awaited<ReturnType<typeof adminSalesPaymentsReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminSalesPaymentsReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminSalesPaymentsReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Sales Payments Report
 */

export function useAdminSalesPaymentsReport<TData = Awaited<ReturnType<typeof adminSalesPaymentsReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminSalesPaymentsReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminSalesPaymentsReport>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminSalesPaymentsReportQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminExportSalesPaymentsReportResponse200 = {
  data: unknown
  status: 200
}

export type adminExportSalesPaymentsReportResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminExportSalesPaymentsReportResponseSuccess = (adminExportSalesPaymentsReportResponse200) & {
  headers: Headers;
};
export type adminExportSalesPaymentsReportResponseError = (adminExportSalesPaymentsReportResponse422) & {
  headers: Headers;
};

export type adminExportSalesPaymentsReportResponse = (adminExportSalesPaymentsReportResponseSuccess | adminExportSalesPaymentsReportResponseError)

export const getAdminExportSalesPaymentsReportUrl = (params?: AdminExportSalesPaymentsReportParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/reports/sales-payments/export?${stringifiedParams}` : `/api/v1/admin/reports/sales-payments/export`
}

/**
 * @summary Export Sales Payments Report
 */
export const adminExportSalesPaymentsReport = async (params?: AdminExportSalesPaymentsReportParams, options?: RequestInit): Promise<adminExportSalesPaymentsReportResponse> => {

  return mutator<adminExportSalesPaymentsReportResponse>(getAdminExportSalesPaymentsReportUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminExportSalesPaymentsReportQueryKey = (params?: AdminExportSalesPaymentsReportParams,) => {
    return [
    `/api/v1/admin/reports/sales-payments/export`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminExportSalesPaymentsReportQueryOptions = <TData = Awaited<ReturnType<typeof adminExportSalesPaymentsReport>>, TError = ErrorType<HTTPValidationError>>(params?: AdminExportSalesPaymentsReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportSalesPaymentsReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminExportSalesPaymentsReportQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminExportSalesPaymentsReport>>> = ({ signal }) => adminExportSalesPaymentsReport(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminExportSalesPaymentsReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminExportSalesPaymentsReportQueryResult = NonNullable<Awaited<ReturnType<typeof adminExportSalesPaymentsReport>>>
export type AdminExportSalesPaymentsReportQueryError = ErrorType<HTTPValidationError>


export function useAdminExportSalesPaymentsReport<TData = Awaited<ReturnType<typeof adminExportSalesPaymentsReport>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminExportSalesPaymentsReportParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportSalesPaymentsReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminExportSalesPaymentsReport>>,
          TError,
          Awaited<ReturnType<typeof adminExportSalesPaymentsReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminExportSalesPaymentsReport<TData = Awaited<ReturnType<typeof adminExportSalesPaymentsReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminExportSalesPaymentsReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportSalesPaymentsReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminExportSalesPaymentsReport>>,
          TError,
          Awaited<ReturnType<typeof adminExportSalesPaymentsReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminExportSalesPaymentsReport<TData = Awaited<ReturnType<typeof adminExportSalesPaymentsReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminExportSalesPaymentsReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportSalesPaymentsReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Export Sales Payments Report
 */

export function useAdminExportSalesPaymentsReport<TData = Awaited<ReturnType<typeof adminExportSalesPaymentsReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminExportSalesPaymentsReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportSalesPaymentsReport>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminExportSalesPaymentsReportQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminExpiringBatchesReportResponse200 = {
  data: ExpiringBatchesReport
  status: 200
}

export type adminExpiringBatchesReportResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminExpiringBatchesReportResponseSuccess = (adminExpiringBatchesReportResponse200) & {
  headers: Headers;
};
export type adminExpiringBatchesReportResponseError = (adminExpiringBatchesReportResponse422) & {
  headers: Headers;
};

export type adminExpiringBatchesReportResponse = (adminExpiringBatchesReportResponseSuccess | adminExpiringBatchesReportResponseError)

export const getAdminExpiringBatchesReportUrl = (params?: AdminExpiringBatchesReportParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/reports/expiring-batches?${stringifiedParams}` : `/api/v1/admin/reports/expiring-batches`
}

/**
 * @summary Expiring Batches Report
 */
export const adminExpiringBatchesReport = async (params?: AdminExpiringBatchesReportParams, options?: RequestInit): Promise<adminExpiringBatchesReportResponse> => {

  return mutator<adminExpiringBatchesReportResponse>(getAdminExpiringBatchesReportUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminExpiringBatchesReportQueryKey = (params?: AdminExpiringBatchesReportParams,) => {
    return [
    `/api/v1/admin/reports/expiring-batches`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminExpiringBatchesReportQueryOptions = <TData = Awaited<ReturnType<typeof adminExpiringBatchesReport>>, TError = ErrorType<HTTPValidationError>>(params?: AdminExpiringBatchesReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExpiringBatchesReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminExpiringBatchesReportQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminExpiringBatchesReport>>> = ({ signal }) => adminExpiringBatchesReport(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminExpiringBatchesReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminExpiringBatchesReportQueryResult = NonNullable<Awaited<ReturnType<typeof adminExpiringBatchesReport>>>
export type AdminExpiringBatchesReportQueryError = ErrorType<HTTPValidationError>


export function useAdminExpiringBatchesReport<TData = Awaited<ReturnType<typeof adminExpiringBatchesReport>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminExpiringBatchesReportParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExpiringBatchesReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminExpiringBatchesReport>>,
          TError,
          Awaited<ReturnType<typeof adminExpiringBatchesReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminExpiringBatchesReport<TData = Awaited<ReturnType<typeof adminExpiringBatchesReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminExpiringBatchesReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExpiringBatchesReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminExpiringBatchesReport>>,
          TError,
          Awaited<ReturnType<typeof adminExpiringBatchesReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminExpiringBatchesReport<TData = Awaited<ReturnType<typeof adminExpiringBatchesReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminExpiringBatchesReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExpiringBatchesReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Expiring Batches Report
 */

export function useAdminExpiringBatchesReport<TData = Awaited<ReturnType<typeof adminExpiringBatchesReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminExpiringBatchesReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExpiringBatchesReport>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminExpiringBatchesReportQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminTopSellingReportResponse200 = {
  data: TopSellingReport
  status: 200
}

export type adminTopSellingReportResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminTopSellingReportResponseSuccess = (adminTopSellingReportResponse200) & {
  headers: Headers;
};
export type adminTopSellingReportResponseError = (adminTopSellingReportResponse422) & {
  headers: Headers;
};

export type adminTopSellingReportResponse = (adminTopSellingReportResponseSuccess | adminTopSellingReportResponseError)

export const getAdminTopSellingReportUrl = (params?: AdminTopSellingReportParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/reports/top-selling?${stringifiedParams}` : `/api/v1/admin/reports/top-selling`
}

/**
 * @summary Top Selling Report
 */
export const adminTopSellingReport = async (params?: AdminTopSellingReportParams, options?: RequestInit): Promise<adminTopSellingReportResponse> => {

  return mutator<adminTopSellingReportResponse>(getAdminTopSellingReportUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminTopSellingReportQueryKey = (params?: AdminTopSellingReportParams,) => {
    return [
    `/api/v1/admin/reports/top-selling`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminTopSellingReportQueryOptions = <TData = Awaited<ReturnType<typeof adminTopSellingReport>>, TError = ErrorType<HTTPValidationError>>(params?: AdminTopSellingReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminTopSellingReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminTopSellingReportQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminTopSellingReport>>> = ({ signal }) => adminTopSellingReport(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminTopSellingReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminTopSellingReportQueryResult = NonNullable<Awaited<ReturnType<typeof adminTopSellingReport>>>
export type AdminTopSellingReportQueryError = ErrorType<HTTPValidationError>


export function useAdminTopSellingReport<TData = Awaited<ReturnType<typeof adminTopSellingReport>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminTopSellingReportParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminTopSellingReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminTopSellingReport>>,
          TError,
          Awaited<ReturnType<typeof adminTopSellingReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminTopSellingReport<TData = Awaited<ReturnType<typeof adminTopSellingReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminTopSellingReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminTopSellingReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminTopSellingReport>>,
          TError,
          Awaited<ReturnType<typeof adminTopSellingReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminTopSellingReport<TData = Awaited<ReturnType<typeof adminTopSellingReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminTopSellingReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminTopSellingReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Top Selling Report
 */

export function useAdminTopSellingReport<TData = Awaited<ReturnType<typeof adminTopSellingReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminTopSellingReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminTopSellingReport>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminTopSellingReportQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminExportTopSellingReportResponse200 = {
  data: unknown
  status: 200
}

export type adminExportTopSellingReportResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminExportTopSellingReportResponseSuccess = (adminExportTopSellingReportResponse200) & {
  headers: Headers;
};
export type adminExportTopSellingReportResponseError = (adminExportTopSellingReportResponse422) & {
  headers: Headers;
};

export type adminExportTopSellingReportResponse = (adminExportTopSellingReportResponseSuccess | adminExportTopSellingReportResponseError)

export const getAdminExportTopSellingReportUrl = (params?: AdminExportTopSellingReportParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/reports/top-selling/export?${stringifiedParams}` : `/api/v1/admin/reports/top-selling/export`
}

/**
 * @summary Export Top Selling Report
 */
export const adminExportTopSellingReport = async (params?: AdminExportTopSellingReportParams, options?: RequestInit): Promise<adminExportTopSellingReportResponse> => {

  return mutator<adminExportTopSellingReportResponse>(getAdminExportTopSellingReportUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminExportTopSellingReportQueryKey = (params?: AdminExportTopSellingReportParams,) => {
    return [
    `/api/v1/admin/reports/top-selling/export`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminExportTopSellingReportQueryOptions = <TData = Awaited<ReturnType<typeof adminExportTopSellingReport>>, TError = ErrorType<HTTPValidationError>>(params?: AdminExportTopSellingReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportTopSellingReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminExportTopSellingReportQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminExportTopSellingReport>>> = ({ signal }) => adminExportTopSellingReport(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminExportTopSellingReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminExportTopSellingReportQueryResult = NonNullable<Awaited<ReturnType<typeof adminExportTopSellingReport>>>
export type AdminExportTopSellingReportQueryError = ErrorType<HTTPValidationError>


export function useAdminExportTopSellingReport<TData = Awaited<ReturnType<typeof adminExportTopSellingReport>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminExportTopSellingReportParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportTopSellingReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminExportTopSellingReport>>,
          TError,
          Awaited<ReturnType<typeof adminExportTopSellingReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminExportTopSellingReport<TData = Awaited<ReturnType<typeof adminExportTopSellingReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminExportTopSellingReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportTopSellingReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminExportTopSellingReport>>,
          TError,
          Awaited<ReturnType<typeof adminExportTopSellingReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminExportTopSellingReport<TData = Awaited<ReturnType<typeof adminExportTopSellingReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminExportTopSellingReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportTopSellingReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Export Top Selling Report
 */

export function useAdminExportTopSellingReport<TData = Awaited<ReturnType<typeof adminExportTopSellingReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminExportTopSellingReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportTopSellingReport>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminExportTopSellingReportQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminLowStockReportResponse200 = {
  data: LowStockReport
  status: 200
}

export type adminLowStockReportResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminLowStockReportResponseSuccess = (adminLowStockReportResponse200) & {
  headers: Headers;
};
export type adminLowStockReportResponseError = (adminLowStockReportResponse422) & {
  headers: Headers;
};

export type adminLowStockReportResponse = (adminLowStockReportResponseSuccess | adminLowStockReportResponseError)

export const getAdminLowStockReportUrl = () => {




  return `/api/v1/admin/reports/low-stock`
}

/**
 * @summary Low Stock Report
 */
export const adminLowStockReport = async ( options?: RequestInit): Promise<adminLowStockReportResponse> => {

  return mutator<adminLowStockReportResponse>(getAdminLowStockReportUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminLowStockReportQueryKey = () => {
    return [
    `/api/v1/admin/reports/low-stock`
    ] as const;
    }


export const getAdminLowStockReportQueryOptions = <TData = Awaited<ReturnType<typeof adminLowStockReport>>, TError = ErrorType<HTTPValidationError>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminLowStockReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminLowStockReportQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminLowStockReport>>> = ({ signal }) => adminLowStockReport({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminLowStockReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminLowStockReportQueryResult = NonNullable<Awaited<ReturnType<typeof adminLowStockReport>>>
export type AdminLowStockReportQueryError = ErrorType<HTTPValidationError>


export function useAdminLowStockReport<TData = Awaited<ReturnType<typeof adminLowStockReport>>, TError = ErrorType<HTTPValidationError>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminLowStockReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminLowStockReport>>,
          TError,
          Awaited<ReturnType<typeof adminLowStockReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminLowStockReport<TData = Awaited<ReturnType<typeof adminLowStockReport>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminLowStockReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminLowStockReport>>,
          TError,
          Awaited<ReturnType<typeof adminLowStockReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminLowStockReport<TData = Awaited<ReturnType<typeof adminLowStockReport>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminLowStockReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Low Stock Report
 */

export function useAdminLowStockReport<TData = Awaited<ReturnType<typeof adminLowStockReport>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminLowStockReport>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminLowStockReportQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminExportLowStockReportResponse200 = {
  data: unknown
  status: 200
}

export type adminExportLowStockReportResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminExportLowStockReportResponseSuccess = (adminExportLowStockReportResponse200) & {
  headers: Headers;
};
export type adminExportLowStockReportResponseError = (adminExportLowStockReportResponse422) & {
  headers: Headers;
};

export type adminExportLowStockReportResponse = (adminExportLowStockReportResponseSuccess | adminExportLowStockReportResponseError)

export const getAdminExportLowStockReportUrl = () => {




  return `/api/v1/admin/reports/low-stock/export`
}

/**
 * @summary Export Low Stock Report
 */
export const adminExportLowStockReport = async ( options?: RequestInit): Promise<adminExportLowStockReportResponse> => {

  return mutator<adminExportLowStockReportResponse>(getAdminExportLowStockReportUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminExportLowStockReportQueryKey = () => {
    return [
    `/api/v1/admin/reports/low-stock/export`
    ] as const;
    }


export const getAdminExportLowStockReportQueryOptions = <TData = Awaited<ReturnType<typeof adminExportLowStockReport>>, TError = ErrorType<HTTPValidationError>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportLowStockReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminExportLowStockReportQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminExportLowStockReport>>> = ({ signal }) => adminExportLowStockReport({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminExportLowStockReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminExportLowStockReportQueryResult = NonNullable<Awaited<ReturnType<typeof adminExportLowStockReport>>>
export type AdminExportLowStockReportQueryError = ErrorType<HTTPValidationError>


export function useAdminExportLowStockReport<TData = Awaited<ReturnType<typeof adminExportLowStockReport>>, TError = ErrorType<HTTPValidationError>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportLowStockReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminExportLowStockReport>>,
          TError,
          Awaited<ReturnType<typeof adminExportLowStockReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminExportLowStockReport<TData = Awaited<ReturnType<typeof adminExportLowStockReport>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportLowStockReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminExportLowStockReport>>,
          TError,
          Awaited<ReturnType<typeof adminExportLowStockReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminExportLowStockReport<TData = Awaited<ReturnType<typeof adminExportLowStockReport>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportLowStockReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Export Low Stock Report
 */

export function useAdminExportLowStockReport<TData = Awaited<ReturnType<typeof adminExportLowStockReport>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportLowStockReport>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminExportLowStockReportQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminDelayedManufacturingReportResponse200 = {
  data: DelayedManufacturingReport
  status: 200
}

export type adminDelayedManufacturingReportResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminDelayedManufacturingReportResponseSuccess = (adminDelayedManufacturingReportResponse200) & {
  headers: Headers;
};
export type adminDelayedManufacturingReportResponseError = (adminDelayedManufacturingReportResponse422) & {
  headers: Headers;
};

export type adminDelayedManufacturingReportResponse = (adminDelayedManufacturingReportResponseSuccess | adminDelayedManufacturingReportResponseError)

export const getAdminDelayedManufacturingReportUrl = (params?: AdminDelayedManufacturingReportParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/reports/delayed-manufacturing?${stringifiedParams}` : `/api/v1/admin/reports/delayed-manufacturing`
}

/**
 * @summary Delayed Manufacturing Report
 */
export const adminDelayedManufacturingReport = async (params?: AdminDelayedManufacturingReportParams, options?: RequestInit): Promise<adminDelayedManufacturingReportResponse> => {

  return mutator<adminDelayedManufacturingReportResponse>(getAdminDelayedManufacturingReportUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminDelayedManufacturingReportQueryKey = (params?: AdminDelayedManufacturingReportParams,) => {
    return [
    `/api/v1/admin/reports/delayed-manufacturing`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminDelayedManufacturingReportQueryOptions = <TData = Awaited<ReturnType<typeof adminDelayedManufacturingReport>>, TError = ErrorType<HTTPValidationError>>(params?: AdminDelayedManufacturingReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDelayedManufacturingReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminDelayedManufacturingReportQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminDelayedManufacturingReport>>> = ({ signal }) => adminDelayedManufacturingReport(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminDelayedManufacturingReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminDelayedManufacturingReportQueryResult = NonNullable<Awaited<ReturnType<typeof adminDelayedManufacturingReport>>>
export type AdminDelayedManufacturingReportQueryError = ErrorType<HTTPValidationError>


export function useAdminDelayedManufacturingReport<TData = Awaited<ReturnType<typeof adminDelayedManufacturingReport>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminDelayedManufacturingReportParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDelayedManufacturingReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminDelayedManufacturingReport>>,
          TError,
          Awaited<ReturnType<typeof adminDelayedManufacturingReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminDelayedManufacturingReport<TData = Awaited<ReturnType<typeof adminDelayedManufacturingReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminDelayedManufacturingReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDelayedManufacturingReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminDelayedManufacturingReport>>,
          TError,
          Awaited<ReturnType<typeof adminDelayedManufacturingReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminDelayedManufacturingReport<TData = Awaited<ReturnType<typeof adminDelayedManufacturingReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminDelayedManufacturingReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDelayedManufacturingReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delayed Manufacturing Report
 */

export function useAdminDelayedManufacturingReport<TData = Awaited<ReturnType<typeof adminDelayedManufacturingReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminDelayedManufacturingReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDelayedManufacturingReport>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminDelayedManufacturingReportQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminExportDelayedManufacturingReportResponse200 = {
  data: unknown
  status: 200
}

export type adminExportDelayedManufacturingReportResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminExportDelayedManufacturingReportResponseSuccess = (adminExportDelayedManufacturingReportResponse200) & {
  headers: Headers;
};
export type adminExportDelayedManufacturingReportResponseError = (adminExportDelayedManufacturingReportResponse422) & {
  headers: Headers;
};

export type adminExportDelayedManufacturingReportResponse = (adminExportDelayedManufacturingReportResponseSuccess | adminExportDelayedManufacturingReportResponseError)

export const getAdminExportDelayedManufacturingReportUrl = (params?: AdminExportDelayedManufacturingReportParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/reports/delayed-manufacturing/export?${stringifiedParams}` : `/api/v1/admin/reports/delayed-manufacturing/export`
}

/**
 * @summary Export Delayed Manufacturing Report
 */
export const adminExportDelayedManufacturingReport = async (params?: AdminExportDelayedManufacturingReportParams, options?: RequestInit): Promise<adminExportDelayedManufacturingReportResponse> => {

  return mutator<adminExportDelayedManufacturingReportResponse>(getAdminExportDelayedManufacturingReportUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminExportDelayedManufacturingReportQueryKey = (params?: AdminExportDelayedManufacturingReportParams,) => {
    return [
    `/api/v1/admin/reports/delayed-manufacturing/export`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminExportDelayedManufacturingReportQueryOptions = <TData = Awaited<ReturnType<typeof adminExportDelayedManufacturingReport>>, TError = ErrorType<HTTPValidationError>>(params?: AdminExportDelayedManufacturingReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportDelayedManufacturingReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminExportDelayedManufacturingReportQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminExportDelayedManufacturingReport>>> = ({ signal }) => adminExportDelayedManufacturingReport(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminExportDelayedManufacturingReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminExportDelayedManufacturingReportQueryResult = NonNullable<Awaited<ReturnType<typeof adminExportDelayedManufacturingReport>>>
export type AdminExportDelayedManufacturingReportQueryError = ErrorType<HTTPValidationError>


export function useAdminExportDelayedManufacturingReport<TData = Awaited<ReturnType<typeof adminExportDelayedManufacturingReport>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminExportDelayedManufacturingReportParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportDelayedManufacturingReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminExportDelayedManufacturingReport>>,
          TError,
          Awaited<ReturnType<typeof adminExportDelayedManufacturingReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminExportDelayedManufacturingReport<TData = Awaited<ReturnType<typeof adminExportDelayedManufacturingReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminExportDelayedManufacturingReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportDelayedManufacturingReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminExportDelayedManufacturingReport>>,
          TError,
          Awaited<ReturnType<typeof adminExportDelayedManufacturingReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminExportDelayedManufacturingReport<TData = Awaited<ReturnType<typeof adminExportDelayedManufacturingReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminExportDelayedManufacturingReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportDelayedManufacturingReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Export Delayed Manufacturing Report
 */

export function useAdminExportDelayedManufacturingReport<TData = Awaited<ReturnType<typeof adminExportDelayedManufacturingReport>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminExportDelayedManufacturingReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminExportDelayedManufacturingReport>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminExportDelayedManufacturingReportQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminDoctorStatementResponse200 = {
  data: DoctorStatement
  status: 200
}

export type adminDoctorStatementResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminDoctorStatementResponseSuccess = (adminDoctorStatementResponse200) & {
  headers: Headers;
};
export type adminDoctorStatementResponseError = (adminDoctorStatementResponse422) & {
  headers: Headers;
};

export type adminDoctorStatementResponse = (adminDoctorStatementResponseSuccess | adminDoctorStatementResponseError)

export const getAdminDoctorStatementUrl = (params: AdminDoctorStatementParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/reports/doctor-statement?${stringifiedParams}` : `/api/v1/admin/reports/doctor-statement`
}

/**
 * Chronological orders-vs-payments account statement for one doctor.
 * @summary Doctor Statement
 */
export const adminDoctorStatement = async (params: AdminDoctorStatementParams, options?: RequestInit): Promise<adminDoctorStatementResponse> => {

  return mutator<adminDoctorStatementResponse>(getAdminDoctorStatementUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminDoctorStatementQueryKey = (params?: AdminDoctorStatementParams,) => {
    return [
    `/api/v1/admin/reports/doctor-statement`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminDoctorStatementQueryOptions = <TData = Awaited<ReturnType<typeof adminDoctorStatement>>, TError = ErrorType<HTTPValidationError>>(params: AdminDoctorStatementParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDoctorStatement>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminDoctorStatementQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminDoctorStatement>>> = ({ signal }) => adminDoctorStatement(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminDoctorStatement>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminDoctorStatementQueryResult = NonNullable<Awaited<ReturnType<typeof adminDoctorStatement>>>
export type AdminDoctorStatementQueryError = ErrorType<HTTPValidationError>


export function useAdminDoctorStatement<TData = Awaited<ReturnType<typeof adminDoctorStatement>>, TError = ErrorType<HTTPValidationError>>(
 params: AdminDoctorStatementParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDoctorStatement>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminDoctorStatement>>,
          TError,
          Awaited<ReturnType<typeof adminDoctorStatement>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminDoctorStatement<TData = Awaited<ReturnType<typeof adminDoctorStatement>>, TError = ErrorType<HTTPValidationError>>(
 params: AdminDoctorStatementParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDoctorStatement>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminDoctorStatement>>,
          TError,
          Awaited<ReturnType<typeof adminDoctorStatement>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminDoctorStatement<TData = Awaited<ReturnType<typeof adminDoctorStatement>>, TError = ErrorType<HTTPValidationError>>(
 params: AdminDoctorStatementParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDoctorStatement>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Doctor Statement
 */

export function useAdminDoctorStatement<TData = Awaited<ReturnType<typeof adminDoctorStatement>>, TError = ErrorType<HTTPValidationError>>(
 params: AdminDoctorStatementParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDoctorStatement>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminDoctorStatementQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminDashboardInventoryStatsResponse200 = {
  data: DashboardInventoryStats
  status: 200
}

export type adminDashboardInventoryStatsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminDashboardInventoryStatsResponseSuccess = (adminDashboardInventoryStatsResponse200) & {
  headers: Headers;
};
export type adminDashboardInventoryStatsResponseError = (adminDashboardInventoryStatsResponse422) & {
  headers: Headers;
};

export type adminDashboardInventoryStatsResponse = (adminDashboardInventoryStatsResponseSuccess | adminDashboardInventoryStatsResponseError)

export const getAdminDashboardInventoryStatsUrl = () => {




  return `/api/v1/admin/reports/dashboard-inventory-stats`
}

/**
 * Dashboard inventory chart aggregates (status donut, expiry buckets,
batches per store) computed in SQL over ALL live batches.
 * @summary Dashboard Inventory Stats
 */
export const adminDashboardInventoryStats = async ( options?: RequestInit): Promise<adminDashboardInventoryStatsResponse> => {

  return mutator<adminDashboardInventoryStatsResponse>(getAdminDashboardInventoryStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminDashboardInventoryStatsQueryKey = () => {
    return [
    `/api/v1/admin/reports/dashboard-inventory-stats`
    ] as const;
    }


export const getAdminDashboardInventoryStatsQueryOptions = <TData = Awaited<ReturnType<typeof adminDashboardInventoryStats>>, TError = ErrorType<HTTPValidationError>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDashboardInventoryStats>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminDashboardInventoryStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminDashboardInventoryStats>>> = ({ signal }) => adminDashboardInventoryStats({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminDashboardInventoryStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminDashboardInventoryStatsQueryResult = NonNullable<Awaited<ReturnType<typeof adminDashboardInventoryStats>>>
export type AdminDashboardInventoryStatsQueryError = ErrorType<HTTPValidationError>


export function useAdminDashboardInventoryStats<TData = Awaited<ReturnType<typeof adminDashboardInventoryStats>>, TError = ErrorType<HTTPValidationError>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDashboardInventoryStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminDashboardInventoryStats>>,
          TError,
          Awaited<ReturnType<typeof adminDashboardInventoryStats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminDashboardInventoryStats<TData = Awaited<ReturnType<typeof adminDashboardInventoryStats>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDashboardInventoryStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminDashboardInventoryStats>>,
          TError,
          Awaited<ReturnType<typeof adminDashboardInventoryStats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminDashboardInventoryStats<TData = Awaited<ReturnType<typeof adminDashboardInventoryStats>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDashboardInventoryStats>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Dashboard Inventory Stats
 */

export function useAdminDashboardInventoryStats<TData = Awaited<ReturnType<typeof adminDashboardInventoryStats>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDashboardInventoryStats>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminDashboardInventoryStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminDashboardSummaryResponse200 = {
  data: DashboardSummary
  status: 200
}

export type adminDashboardSummaryResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminDashboardSummaryResponseSuccess = (adminDashboardSummaryResponse200) & {
  headers: Headers;
};
export type adminDashboardSummaryResponseError = (adminDashboardSummaryResponse422) & {
  headers: Headers;
};

export type adminDashboardSummaryResponse = (adminDashboardSummaryResponseSuccess | adminDashboardSummaryResponseError)

export const getAdminDashboardSummaryUrl = () => {




  return `/api/v1/admin/reports/dashboard-summary`
}

/**
 * All dashboard KPIs in one call; per-section fields are null unless the
caller holds that module's view permission (auth-only endpoint).
 * @summary Dashboard Summary
 */
export const adminDashboardSummary = async ( options?: RequestInit): Promise<adminDashboardSummaryResponse> => {

  return mutator<adminDashboardSummaryResponse>(getAdminDashboardSummaryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminDashboardSummaryQueryKey = () => {
    return [
    `/api/v1/admin/reports/dashboard-summary`
    ] as const;
    }


export const getAdminDashboardSummaryQueryOptions = <TData = Awaited<ReturnType<typeof adminDashboardSummary>>, TError = ErrorType<HTTPValidationError>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDashboardSummary>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminDashboardSummaryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminDashboardSummary>>> = ({ signal }) => adminDashboardSummary({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminDashboardSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminDashboardSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof adminDashboardSummary>>>
export type AdminDashboardSummaryQueryError = ErrorType<HTTPValidationError>


export function useAdminDashboardSummary<TData = Awaited<ReturnType<typeof adminDashboardSummary>>, TError = ErrorType<HTTPValidationError>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDashboardSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminDashboardSummary>>,
          TError,
          Awaited<ReturnType<typeof adminDashboardSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminDashboardSummary<TData = Awaited<ReturnType<typeof adminDashboardSummary>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDashboardSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminDashboardSummary>>,
          TError,
          Awaited<ReturnType<typeof adminDashboardSummary>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminDashboardSummary<TData = Awaited<ReturnType<typeof adminDashboardSummary>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDashboardSummary>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Dashboard Summary
 */

export function useAdminDashboardSummary<TData = Awaited<ReturnType<typeof adminDashboardSummary>>, TError = ErrorType<HTTPValidationError>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminDashboardSummary>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminDashboardSummaryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






