/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminListStockReturnsParams,
  CancelReturnIn,
  HTTPValidationError,
  StockReturnCreate,
  StockReturnDetail,
  StockReturnList,
  StockReturnUpdate
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type adminListStockReturnsResponse200 = {
  data: StockReturnList
  status: 200
}

export type adminListStockReturnsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListStockReturnsResponseSuccess = (adminListStockReturnsResponse200) & {
  headers: Headers;
};
export type adminListStockReturnsResponseError = (adminListStockReturnsResponse422) & {
  headers: Headers;
};

export type adminListStockReturnsResponse = (adminListStockReturnsResponseSuccess | adminListStockReturnsResponseError)

export const getAdminListStockReturnsUrl = (params?: AdminListStockReturnsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/returns/returns?${stringifiedParams}` : `/api/v1/admin/returns/returns`
}

/**
 * @summary List Stock Returns
 */
export const adminListStockReturns = async (params?: AdminListStockReturnsParams, options?: RequestInit): Promise<adminListStockReturnsResponse> => {

  return mutator<adminListStockReturnsResponse>(getAdminListStockReturnsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListStockReturnsQueryKey = (params?: AdminListStockReturnsParams,) => {
    return [
    `/api/v1/admin/returns/returns`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListStockReturnsQueryOptions = <TData = Awaited<ReturnType<typeof adminListStockReturns>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListStockReturnsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListStockReturns>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListStockReturnsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListStockReturns>>> = ({ signal }) => adminListStockReturns(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListStockReturns>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListStockReturnsQueryResult = NonNullable<Awaited<ReturnType<typeof adminListStockReturns>>>
export type AdminListStockReturnsQueryError = ErrorType<HTTPValidationError>


export function useAdminListStockReturns<TData = Awaited<ReturnType<typeof adminListStockReturns>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListStockReturnsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListStockReturns>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListStockReturns>>,
          TError,
          Awaited<ReturnType<typeof adminListStockReturns>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListStockReturns<TData = Awaited<ReturnType<typeof adminListStockReturns>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListStockReturnsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListStockReturns>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListStockReturns>>,
          TError,
          Awaited<ReturnType<typeof adminListStockReturns>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListStockReturns<TData = Awaited<ReturnType<typeof adminListStockReturns>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListStockReturnsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListStockReturns>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Stock Returns
 */

export function useAdminListStockReturns<TData = Awaited<ReturnType<typeof adminListStockReturns>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListStockReturnsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListStockReturns>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListStockReturnsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminCreateStockReturnResponse201 = {
  data: StockReturnDetail
  status: 201
}

export type adminCreateStockReturnResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCreateStockReturnResponseSuccess = (adminCreateStockReturnResponse201) & {
  headers: Headers;
};
export type adminCreateStockReturnResponseError = (adminCreateStockReturnResponse422) & {
  headers: Headers;
};

export type adminCreateStockReturnResponse = (adminCreateStockReturnResponseSuccess | adminCreateStockReturnResponseError)

export const getAdminCreateStockReturnUrl = () => {




  return `/api/v1/admin/returns/returns`
}

/**
 * @summary Create Stock Return
 */
export const adminCreateStockReturn = async (stockReturnCreate: StockReturnCreate, options?: RequestInit): Promise<adminCreateStockReturnResponse> => {

  return mutator<adminCreateStockReturnResponse>(getAdminCreateStockReturnUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(stockReturnCreate)
  }
);}




export const getAdminCreateStockReturnMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateStockReturn>>, TError,{data: BodyType<StockReturnCreate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateStockReturn>>, TError,{data: BodyType<StockReturnCreate>}, TContext> => {

const mutationKey = ['adminCreateStockReturn'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateStockReturn>>, {data: BodyType<StockReturnCreate>}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateStockReturn(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateStockReturnMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateStockReturn>>>
    export type AdminCreateStockReturnMutationBody = BodyType<StockReturnCreate>
    export type AdminCreateStockReturnMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Stock Return
 */
export const useAdminCreateStockReturn = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateStockReturn>>, TError,{data: BodyType<StockReturnCreate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateStockReturn>>,
        TError,
        {data: BodyType<StockReturnCreate>},
        TContext
      > => {
      return useMutation(getAdminCreateStockReturnMutationOptions(options), queryClient);
    }
    export type adminGetStockReturnResponse200 = {
  data: StockReturnDetail
  status: 200
}

export type adminGetStockReturnResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminGetStockReturnResponseSuccess = (adminGetStockReturnResponse200) & {
  headers: Headers;
};
export type adminGetStockReturnResponseError = (adminGetStockReturnResponse422) & {
  headers: Headers;
};

export type adminGetStockReturnResponse = (adminGetStockReturnResponseSuccess | adminGetStockReturnResponseError)

export const getAdminGetStockReturnUrl = (returnUuid: string,) => {




  return `/api/v1/admin/returns/returns/${returnUuid}`
}

/**
 * @summary Get Stock Return
 */
export const adminGetStockReturn = async (returnUuid: string, options?: RequestInit): Promise<adminGetStockReturnResponse> => {

  return mutator<adminGetStockReturnResponse>(getAdminGetStockReturnUrl(returnUuid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminGetStockReturnQueryKey = (returnUuid: string,) => {
    return [
    `/api/v1/admin/returns/returns/${returnUuid}`
    ] as const;
    }


export const getAdminGetStockReturnQueryOptions = <TData = Awaited<ReturnType<typeof adminGetStockReturn>>, TError = ErrorType<HTTPValidationError>>(returnUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetStockReturn>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetStockReturnQueryKey(returnUuid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetStockReturn>>> = ({ signal }) => adminGetStockReturn(returnUuid, { signal });





   return  { queryKey, queryFn, enabled: returnUuid !== null && returnUuid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetStockReturn>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetStockReturnQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetStockReturn>>>
export type AdminGetStockReturnQueryError = ErrorType<HTTPValidationError>


export function useAdminGetStockReturn<TData = Awaited<ReturnType<typeof adminGetStockReturn>>, TError = ErrorType<HTTPValidationError>>(
 returnUuid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetStockReturn>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetStockReturn>>,
          TError,
          Awaited<ReturnType<typeof adminGetStockReturn>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetStockReturn<TData = Awaited<ReturnType<typeof adminGetStockReturn>>, TError = ErrorType<HTTPValidationError>>(
 returnUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetStockReturn>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetStockReturn>>,
          TError,
          Awaited<ReturnType<typeof adminGetStockReturn>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetStockReturn<TData = Awaited<ReturnType<typeof adminGetStockReturn>>, TError = ErrorType<HTTPValidationError>>(
 returnUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetStockReturn>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Stock Return
 */

export function useAdminGetStockReturn<TData = Awaited<ReturnType<typeof adminGetStockReturn>>, TError = ErrorType<HTTPValidationError>>(
 returnUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetStockReturn>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminGetStockReturnQueryOptions(returnUuid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminUpdateStockReturnResponse200 = {
  data: StockReturnDetail
  status: 200
}

export type adminUpdateStockReturnResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminUpdateStockReturnResponseSuccess = (adminUpdateStockReturnResponse200) & {
  headers: Headers;
};
export type adminUpdateStockReturnResponseError = (adminUpdateStockReturnResponse422) & {
  headers: Headers;
};

export type adminUpdateStockReturnResponse = (adminUpdateStockReturnResponseSuccess | adminUpdateStockReturnResponseError)

export const getAdminUpdateStockReturnUrl = (returnUuid: string,) => {




  return `/api/v1/admin/returns/returns/${returnUuid}`
}

/**
 * @summary Update Stock Return
 */
export const adminUpdateStockReturn = async (returnUuid: string,
    stockReturnUpdate: StockReturnUpdate, options?: RequestInit): Promise<adminUpdateStockReturnResponse> => {

  return mutator<adminUpdateStockReturnResponse>(getAdminUpdateStockReturnUrl(returnUuid),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(stockReturnUpdate)
  }
);}




export const getAdminUpdateStockReturnMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateStockReturn>>, TError,{returnUuid: string;data: BodyType<StockReturnUpdate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateStockReturn>>, TError,{returnUuid: string;data: BodyType<StockReturnUpdate>}, TContext> => {

const mutationKey = ['adminUpdateStockReturn'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateStockReturn>>, {returnUuid: string;data: BodyType<StockReturnUpdate>}> = (props) => {
          const {returnUuid,data} = props ?? {};

          return  adminUpdateStockReturn(returnUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateStockReturnMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateStockReturn>>>
    export type AdminUpdateStockReturnMutationBody = BodyType<StockReturnUpdate>
    export type AdminUpdateStockReturnMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Stock Return
 */
export const useAdminUpdateStockReturn = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateStockReturn>>, TError,{returnUuid: string;data: BodyType<StockReturnUpdate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateStockReturn>>,
        TError,
        {returnUuid: string;data: BodyType<StockReturnUpdate>},
        TContext
      > => {
      return useMutation(getAdminUpdateStockReturnMutationOptions(options), queryClient);
    }
    export type adminDeleteStockReturnResponse204 = {
  data: void
  status: 204
}

export type adminDeleteStockReturnResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminDeleteStockReturnResponseSuccess = (adminDeleteStockReturnResponse204) & {
  headers: Headers;
};
export type adminDeleteStockReturnResponseError = (adminDeleteStockReturnResponse422) & {
  headers: Headers;
};

export type adminDeleteStockReturnResponse = (adminDeleteStockReturnResponseSuccess | adminDeleteStockReturnResponseError)

export const getAdminDeleteStockReturnUrl = (returnUuid: string,) => {




  return `/api/v1/admin/returns/returns/${returnUuid}`
}

/**
 * @summary Delete Stock Return
 */
export const adminDeleteStockReturn = async (returnUuid: string, options?: RequestInit): Promise<adminDeleteStockReturnResponse> => {

  return mutator<adminDeleteStockReturnResponse>(getAdminDeleteStockReturnUrl(returnUuid),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getAdminDeleteStockReturnMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteStockReturn>>, TError,{returnUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminDeleteStockReturn>>, TError,{returnUuid: string}, TContext> => {

const mutationKey = ['adminDeleteStockReturn'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminDeleteStockReturn>>, {returnUuid: string}> = (props) => {
          const {returnUuid} = props ?? {};

          return  adminDeleteStockReturn(returnUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminDeleteStockReturnMutationResult = NonNullable<Awaited<ReturnType<typeof adminDeleteStockReturn>>>

    export type AdminDeleteStockReturnMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Stock Return
 */
export const useAdminDeleteStockReturn = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteStockReturn>>, TError,{returnUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminDeleteStockReturn>>,
        TError,
        {returnUuid: string},
        TContext
      > => {
      return useMutation(getAdminDeleteStockReturnMutationOptions(options), queryClient);
    }
    export type adminPostStockReturnResponse200 = {
  data: StockReturnDetail
  status: 200
}

export type adminPostStockReturnResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminPostStockReturnResponseSuccess = (adminPostStockReturnResponse200) & {
  headers: Headers;
};
export type adminPostStockReturnResponseError = (adminPostStockReturnResponse422) & {
  headers: Headers;
};

export type adminPostStockReturnResponse = (adminPostStockReturnResponseSuccess | adminPostStockReturnResponseError)

export const getAdminPostStockReturnUrl = (returnUuid: string,) => {




  return `/api/v1/admin/returns/returns/${returnUuid}/post`
}

/**
 * @summary Post Stock Return
 */
export const adminPostStockReturn = async (returnUuid: string, options?: RequestInit): Promise<adminPostStockReturnResponse> => {

  return mutator<adminPostStockReturnResponse>(getAdminPostStockReturnUrl(returnUuid),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminPostStockReturnMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminPostStockReturn>>, TError,{returnUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminPostStockReturn>>, TError,{returnUuid: string}, TContext> => {

const mutationKey = ['adminPostStockReturn'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminPostStockReturn>>, {returnUuid: string}> = (props) => {
          const {returnUuid} = props ?? {};

          return  adminPostStockReturn(returnUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminPostStockReturnMutationResult = NonNullable<Awaited<ReturnType<typeof adminPostStockReturn>>>

    export type AdminPostStockReturnMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Post Stock Return
 */
export const useAdminPostStockReturn = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminPostStockReturn>>, TError,{returnUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminPostStockReturn>>,
        TError,
        {returnUuid: string},
        TContext
      > => {
      return useMutation(getAdminPostStockReturnMutationOptions(options), queryClient);
    }
    export type adminCancelStockReturnResponse200 = {
  data: StockReturnDetail
  status: 200
}

export type adminCancelStockReturnResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCancelStockReturnResponseSuccess = (adminCancelStockReturnResponse200) & {
  headers: Headers;
};
export type adminCancelStockReturnResponseError = (adminCancelStockReturnResponse422) & {
  headers: Headers;
};

export type adminCancelStockReturnResponse = (adminCancelStockReturnResponseSuccess | adminCancelStockReturnResponseError)

export const getAdminCancelStockReturnUrl = (returnUuid: string,) => {




  return `/api/v1/admin/returns/returns/${returnUuid}/cancel`
}

/**
 * @summary Cancel Stock Return
 */
export const adminCancelStockReturn = async (returnUuid: string,
    cancelReturnInNull?: CancelReturnIn | null, options?: RequestInit): Promise<adminCancelStockReturnResponse> => {

  return mutator<adminCancelStockReturnResponse>(getAdminCancelStockReturnUrl(returnUuid),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(cancelReturnInNull)
  }
);}




export const getAdminCancelStockReturnMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCancelStockReturn>>, TError,{returnUuid: string;data?: BodyType<CancelReturnIn | null>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCancelStockReturn>>, TError,{returnUuid: string;data?: BodyType<CancelReturnIn | null>}, TContext> => {

const mutationKey = ['adminCancelStockReturn'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCancelStockReturn>>, {returnUuid: string;data?: BodyType<CancelReturnIn | null>}> = (props) => {
          const {returnUuid,data} = props ?? {};

          return  adminCancelStockReturn(returnUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCancelStockReturnMutationResult = NonNullable<Awaited<ReturnType<typeof adminCancelStockReturn>>>
    export type AdminCancelStockReturnMutationBody = BodyType<CancelReturnIn | null> | undefined
    export type AdminCancelStockReturnMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Cancel Stock Return
 */
export const useAdminCancelStockReturn = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCancelStockReturn>>, TError,{returnUuid: string;data?: BodyType<CancelReturnIn | null>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCancelStockReturn>>,
        TError,
        {returnUuid: string;data?: BodyType<CancelReturnIn | null>},
        TContext
      > => {
      return useMutation(getAdminCancelStockReturnMutationOptions(options), queryClient);
    }
