/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddSoFollowupRequest,
  AdminListMySalesFollowupsParams,
  AdminListSalesOrdersParams,
  AdminSalesPricePreviewParams,
  CancelOrderIn,
  DispatchOrderRequest,
  HTTPValidationError,
  PricePreview,
  SalesOrderCreate,
  SalesOrderDetail,
  SalesOrderList,
  SalesOrderUpdate,
  SoMyFollowupList
} from './schemas';

import { mutator } from '../api/sdk-mutator';
import type { ErrorType , BodyType } from '../api/sdk-mutator';





export type adminListMySalesFollowupsResponse200 = {
  data: SoMyFollowupList
  status: 200
}

export type adminListMySalesFollowupsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListMySalesFollowupsResponseSuccess = (adminListMySalesFollowupsResponse200) & {
  headers: Headers;
};
export type adminListMySalesFollowupsResponseError = (adminListMySalesFollowupsResponse422) & {
  headers: Headers;
};

export type adminListMySalesFollowupsResponse = (adminListMySalesFollowupsResponseSuccess | adminListMySalesFollowupsResponseError)

export const getAdminListMySalesFollowupsUrl = (params?: AdminListMySalesFollowupsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/sales/my-followups?${stringifiedParams}` : `/api/v1/admin/sales/my-followups`
}

/**
 * @summary List My Sales Followups
 */
export const adminListMySalesFollowups = async (params?: AdminListMySalesFollowupsParams, options?: RequestInit): Promise<adminListMySalesFollowupsResponse> => {

  return mutator<adminListMySalesFollowupsResponse>(getAdminListMySalesFollowupsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListMySalesFollowupsQueryKey = (params?: AdminListMySalesFollowupsParams,) => {
    return [
    `/api/v1/admin/sales/my-followups`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListMySalesFollowupsQueryOptions = <TData = Awaited<ReturnType<typeof adminListMySalesFollowups>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListMySalesFollowupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMySalesFollowups>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListMySalesFollowupsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListMySalesFollowups>>> = ({ signal }) => adminListMySalesFollowups(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListMySalesFollowups>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListMySalesFollowupsQueryResult = NonNullable<Awaited<ReturnType<typeof adminListMySalesFollowups>>>
export type AdminListMySalesFollowupsQueryError = ErrorType<HTTPValidationError>


export function useAdminListMySalesFollowups<TData = Awaited<ReturnType<typeof adminListMySalesFollowups>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListMySalesFollowupsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMySalesFollowups>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListMySalesFollowups>>,
          TError,
          Awaited<ReturnType<typeof adminListMySalesFollowups>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListMySalesFollowups<TData = Awaited<ReturnType<typeof adminListMySalesFollowups>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListMySalesFollowupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMySalesFollowups>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListMySalesFollowups>>,
          TError,
          Awaited<ReturnType<typeof adminListMySalesFollowups>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListMySalesFollowups<TData = Awaited<ReturnType<typeof adminListMySalesFollowups>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListMySalesFollowupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMySalesFollowups>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List My Sales Followups
 */

export function useAdminListMySalesFollowups<TData = Awaited<ReturnType<typeof adminListMySalesFollowups>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListMySalesFollowupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListMySalesFollowups>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListMySalesFollowupsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminMarkSalesFollowupDoneResponse200 = {
  data: SalesOrderDetail
  status: 200
}

export type adminMarkSalesFollowupDoneResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminMarkSalesFollowupDoneResponseSuccess = (adminMarkSalesFollowupDoneResponse200) & {
  headers: Headers;
};
export type adminMarkSalesFollowupDoneResponseError = (adminMarkSalesFollowupDoneResponse422) & {
  headers: Headers;
};

export type adminMarkSalesFollowupDoneResponse = (adminMarkSalesFollowupDoneResponseSuccess | adminMarkSalesFollowupDoneResponseError)

export const getAdminMarkSalesFollowupDoneUrl = (followupUuid: string,) => {




  return `/api/v1/admin/sales/followups/${followupUuid}/done`
}

/**
 * @summary Mark Sales Followup Done
 */
export const adminMarkSalesFollowupDone = async (followupUuid: string, options?: RequestInit): Promise<adminMarkSalesFollowupDoneResponse> => {

  return mutator<adminMarkSalesFollowupDoneResponse>(getAdminMarkSalesFollowupDoneUrl(followupUuid),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminMarkSalesFollowupDoneMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminMarkSalesFollowupDone>>, TError,{followupUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminMarkSalesFollowupDone>>, TError,{followupUuid: string}, TContext> => {

const mutationKey = ['adminMarkSalesFollowupDone'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminMarkSalesFollowupDone>>, {followupUuid: string}> = (props) => {
          const {followupUuid} = props ?? {};

          return  adminMarkSalesFollowupDone(followupUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminMarkSalesFollowupDoneMutationResult = NonNullable<Awaited<ReturnType<typeof adminMarkSalesFollowupDone>>>

    export type AdminMarkSalesFollowupDoneMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Mark Sales Followup Done
 */
export const useAdminMarkSalesFollowupDone = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminMarkSalesFollowupDone>>, TError,{followupUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminMarkSalesFollowupDone>>,
        TError,
        {followupUuid: string},
        TContext
      > => {
      return useMutation(getAdminMarkSalesFollowupDoneMutationOptions(options), queryClient);
    }
    export type adminListSalesOrdersResponse200 = {
  data: SalesOrderList
  status: 200
}

export type adminListSalesOrdersResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminListSalesOrdersResponseSuccess = (adminListSalesOrdersResponse200) & {
  headers: Headers;
};
export type adminListSalesOrdersResponseError = (adminListSalesOrdersResponse422) & {
  headers: Headers;
};

export type adminListSalesOrdersResponse = (adminListSalesOrdersResponseSuccess | adminListSalesOrdersResponseError)

export const getAdminListSalesOrdersUrl = (params?: AdminListSalesOrdersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/sales/orders?${stringifiedParams}` : `/api/v1/admin/sales/orders`
}

/**
 * @summary List Sales Orders
 */
export const adminListSalesOrders = async (params?: AdminListSalesOrdersParams, options?: RequestInit): Promise<adminListSalesOrdersResponse> => {

  return mutator<adminListSalesOrdersResponse>(getAdminListSalesOrdersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminListSalesOrdersQueryKey = (params?: AdminListSalesOrdersParams,) => {
    return [
    `/api/v1/admin/sales/orders`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminListSalesOrdersQueryOptions = <TData = Awaited<ReturnType<typeof adminListSalesOrders>>, TError = ErrorType<HTTPValidationError>>(params?: AdminListSalesOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListSalesOrders>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListSalesOrdersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListSalesOrders>>> = ({ signal }) => adminListSalesOrders(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListSalesOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListSalesOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof adminListSalesOrders>>>
export type AdminListSalesOrdersQueryError = ErrorType<HTTPValidationError>


export function useAdminListSalesOrders<TData = Awaited<ReturnType<typeof adminListSalesOrders>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  AdminListSalesOrdersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListSalesOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListSalesOrders>>,
          TError,
          Awaited<ReturnType<typeof adminListSalesOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListSalesOrders<TData = Awaited<ReturnType<typeof adminListSalesOrders>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListSalesOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListSalesOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListSalesOrders>>,
          TError,
          Awaited<ReturnType<typeof adminListSalesOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListSalesOrders<TData = Awaited<ReturnType<typeof adminListSalesOrders>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListSalesOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListSalesOrders>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Sales Orders
 */

export function useAdminListSalesOrders<TData = Awaited<ReturnType<typeof adminListSalesOrders>>, TError = ErrorType<HTTPValidationError>>(
 params?: AdminListSalesOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListSalesOrders>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListSalesOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminCreateSalesOrderResponse201 = {
  data: SalesOrderDetail
  status: 201
}

export type adminCreateSalesOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCreateSalesOrderResponseSuccess = (adminCreateSalesOrderResponse201) & {
  headers: Headers;
};
export type adminCreateSalesOrderResponseError = (adminCreateSalesOrderResponse422) & {
  headers: Headers;
};

export type adminCreateSalesOrderResponse = (adminCreateSalesOrderResponseSuccess | adminCreateSalesOrderResponseError)

export const getAdminCreateSalesOrderUrl = () => {




  return `/api/v1/admin/sales/orders`
}

/**
 * @summary Create Sales Order
 */
export const adminCreateSalesOrder = async (salesOrderCreate: SalesOrderCreate, options?: RequestInit): Promise<adminCreateSalesOrderResponse> => {

  return mutator<adminCreateSalesOrderResponse>(getAdminCreateSalesOrderUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(salesOrderCreate)
  }
);}




export const getAdminCreateSalesOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateSalesOrder>>, TError,{data: BodyType<SalesOrderCreate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCreateSalesOrder>>, TError,{data: BodyType<SalesOrderCreate>}, TContext> => {

const mutationKey = ['adminCreateSalesOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateSalesOrder>>, {data: BodyType<SalesOrderCreate>}> = (props) => {
          const {data} = props ?? {};

          return  adminCreateSalesOrder(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCreateSalesOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateSalesOrder>>>
    export type AdminCreateSalesOrderMutationBody = BodyType<SalesOrderCreate>
    export type AdminCreateSalesOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Sales Order
 */
export const useAdminCreateSalesOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateSalesOrder>>, TError,{data: BodyType<SalesOrderCreate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreateSalesOrder>>,
        TError,
        {data: BodyType<SalesOrderCreate>},
        TContext
      > => {
      return useMutation(getAdminCreateSalesOrderMutationOptions(options), queryClient);
    }
    export type adminSalesPricePreviewResponse200 = {
  data: PricePreview
  status: 200
}

export type adminSalesPricePreviewResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminSalesPricePreviewResponseSuccess = (adminSalesPricePreviewResponse200) & {
  headers: Headers;
};
export type adminSalesPricePreviewResponseError = (adminSalesPricePreviewResponse422) & {
  headers: Headers;
};

export type adminSalesPricePreviewResponse = (adminSalesPricePreviewResponseSuccess | adminSalesPricePreviewResponseError)

export const getAdminSalesPricePreviewUrl = (params: AdminSalesPricePreviewParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/sales/orders/price-preview?${stringifiedParams}` : `/api/v1/admin/sales/orders/price-preview`
}

/**
 * @summary Sales Price Preview
 */
export const adminSalesPricePreview = async (params: AdminSalesPricePreviewParams, options?: RequestInit): Promise<adminSalesPricePreviewResponse> => {

  return mutator<adminSalesPricePreviewResponse>(getAdminSalesPricePreviewUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminSalesPricePreviewQueryKey = (params?: AdminSalesPricePreviewParams,) => {
    return [
    `/api/v1/admin/sales/orders/price-preview`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdminSalesPricePreviewQueryOptions = <TData = Awaited<ReturnType<typeof adminSalesPricePreview>>, TError = ErrorType<HTTPValidationError>>(params: AdminSalesPricePreviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminSalesPricePreview>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminSalesPricePreviewQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminSalesPricePreview>>> = ({ signal }) => adminSalesPricePreview(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminSalesPricePreview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminSalesPricePreviewQueryResult = NonNullable<Awaited<ReturnType<typeof adminSalesPricePreview>>>
export type AdminSalesPricePreviewQueryError = ErrorType<HTTPValidationError>


export function useAdminSalesPricePreview<TData = Awaited<ReturnType<typeof adminSalesPricePreview>>, TError = ErrorType<HTTPValidationError>>(
 params: AdminSalesPricePreviewParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminSalesPricePreview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminSalesPricePreview>>,
          TError,
          Awaited<ReturnType<typeof adminSalesPricePreview>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminSalesPricePreview<TData = Awaited<ReturnType<typeof adminSalesPricePreview>>, TError = ErrorType<HTTPValidationError>>(
 params: AdminSalesPricePreviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminSalesPricePreview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminSalesPricePreview>>,
          TError,
          Awaited<ReturnType<typeof adminSalesPricePreview>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminSalesPricePreview<TData = Awaited<ReturnType<typeof adminSalesPricePreview>>, TError = ErrorType<HTTPValidationError>>(
 params: AdminSalesPricePreviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminSalesPricePreview>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Sales Price Preview
 */

export function useAdminSalesPricePreview<TData = Awaited<ReturnType<typeof adminSalesPricePreview>>, TError = ErrorType<HTTPValidationError>>(
 params: AdminSalesPricePreviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminSalesPricePreview>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminSalesPricePreviewQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminGetSalesOrderResponse200 = {
  data: SalesOrderDetail
  status: 200
}

export type adminGetSalesOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminGetSalesOrderResponseSuccess = (adminGetSalesOrderResponse200) & {
  headers: Headers;
};
export type adminGetSalesOrderResponseError = (adminGetSalesOrderResponse422) & {
  headers: Headers;
};

export type adminGetSalesOrderResponse = (adminGetSalesOrderResponseSuccess | adminGetSalesOrderResponseError)

export const getAdminGetSalesOrderUrl = (orderUuid: string,) => {




  return `/api/v1/admin/sales/orders/${orderUuid}`
}

/**
 * @summary Get Sales Order
 */
export const adminGetSalesOrder = async (orderUuid: string, options?: RequestInit): Promise<adminGetSalesOrderResponse> => {

  return mutator<adminGetSalesOrderResponse>(getAdminGetSalesOrderUrl(orderUuid),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdminGetSalesOrderQueryKey = (orderUuid: string,) => {
    return [
    `/api/v1/admin/sales/orders/${orderUuid}`
    ] as const;
    }


export const getAdminGetSalesOrderQueryOptions = <TData = Awaited<ReturnType<typeof adminGetSalesOrder>>, TError = ErrorType<HTTPValidationError>>(orderUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetSalesOrder>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetSalesOrderQueryKey(orderUuid);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetSalesOrder>>> = ({ signal }) => adminGetSalesOrder(orderUuid, { signal });





   return  { queryKey, queryFn, enabled: orderUuid !== null && orderUuid !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetSalesOrder>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetSalesOrderQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetSalesOrder>>>
export type AdminGetSalesOrderQueryError = ErrorType<HTTPValidationError>


export function useAdminGetSalesOrder<TData = Awaited<ReturnType<typeof adminGetSalesOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderUuid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetSalesOrder>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetSalesOrder>>,
          TError,
          Awaited<ReturnType<typeof adminGetSalesOrder>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetSalesOrder<TData = Awaited<ReturnType<typeof adminGetSalesOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetSalesOrder>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetSalesOrder>>,
          TError,
          Awaited<ReturnType<typeof adminGetSalesOrder>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetSalesOrder<TData = Awaited<ReturnType<typeof adminGetSalesOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetSalesOrder>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Sales Order
 */

export function useAdminGetSalesOrder<TData = Awaited<ReturnType<typeof adminGetSalesOrder>>, TError = ErrorType<HTTPValidationError>>(
 orderUuid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetSalesOrder>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminGetSalesOrderQueryOptions(orderUuid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type adminUpdateSalesOrderResponse200 = {
  data: SalesOrderDetail
  status: 200
}

export type adminUpdateSalesOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminUpdateSalesOrderResponseSuccess = (adminUpdateSalesOrderResponse200) & {
  headers: Headers;
};
export type adminUpdateSalesOrderResponseError = (adminUpdateSalesOrderResponse422) & {
  headers: Headers;
};

export type adminUpdateSalesOrderResponse = (adminUpdateSalesOrderResponseSuccess | adminUpdateSalesOrderResponseError)

export const getAdminUpdateSalesOrderUrl = (orderUuid: string,) => {




  return `/api/v1/admin/sales/orders/${orderUuid}`
}

/**
 * @summary Update Sales Order
 */
export const adminUpdateSalesOrder = async (orderUuid: string,
    salesOrderUpdate: SalesOrderUpdate, options?: RequestInit): Promise<adminUpdateSalesOrderResponse> => {

  return mutator<adminUpdateSalesOrderResponse>(getAdminUpdateSalesOrderUrl(orderUuid),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(salesOrderUpdate)
  }
);}




export const getAdminUpdateSalesOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateSalesOrder>>, TError,{orderUuid: string;data: BodyType<SalesOrderUpdate>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateSalesOrder>>, TError,{orderUuid: string;data: BodyType<SalesOrderUpdate>}, TContext> => {

const mutationKey = ['adminUpdateSalesOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateSalesOrder>>, {orderUuid: string;data: BodyType<SalesOrderUpdate>}> = (props) => {
          const {orderUuid,data} = props ?? {};

          return  adminUpdateSalesOrder(orderUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateSalesOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateSalesOrder>>>
    export type AdminUpdateSalesOrderMutationBody = BodyType<SalesOrderUpdate>
    export type AdminUpdateSalesOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Sales Order
 */
export const useAdminUpdateSalesOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateSalesOrder>>, TError,{orderUuid: string;data: BodyType<SalesOrderUpdate>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateSalesOrder>>,
        TError,
        {orderUuid: string;data: BodyType<SalesOrderUpdate>},
        TContext
      > => {
      return useMutation(getAdminUpdateSalesOrderMutationOptions(options), queryClient);
    }
    export type adminDeleteSalesOrderResponse204 = {
  data: void
  status: 204
}

export type adminDeleteSalesOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminDeleteSalesOrderResponseSuccess = (adminDeleteSalesOrderResponse204) & {
  headers: Headers;
};
export type adminDeleteSalesOrderResponseError = (adminDeleteSalesOrderResponse422) & {
  headers: Headers;
};

export type adminDeleteSalesOrderResponse = (adminDeleteSalesOrderResponseSuccess | adminDeleteSalesOrderResponseError)

export const getAdminDeleteSalesOrderUrl = (orderUuid: string,) => {




  return `/api/v1/admin/sales/orders/${orderUuid}`
}

/**
 * @summary Delete Sales Order
 */
export const adminDeleteSalesOrder = async (orderUuid: string, options?: RequestInit): Promise<adminDeleteSalesOrderResponse> => {

  return mutator<adminDeleteSalesOrderResponse>(getAdminDeleteSalesOrderUrl(orderUuid),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getAdminDeleteSalesOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteSalesOrder>>, TError,{orderUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminDeleteSalesOrder>>, TError,{orderUuid: string}, TContext> => {

const mutationKey = ['adminDeleteSalesOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminDeleteSalesOrder>>, {orderUuid: string}> = (props) => {
          const {orderUuid} = props ?? {};

          return  adminDeleteSalesOrder(orderUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminDeleteSalesOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminDeleteSalesOrder>>>

    export type AdminDeleteSalesOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Sales Order
 */
export const useAdminDeleteSalesOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteSalesOrder>>, TError,{orderUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminDeleteSalesOrder>>,
        TError,
        {orderUuid: string},
        TContext
      > => {
      return useMutation(getAdminDeleteSalesOrderMutationOptions(options), queryClient);
    }
    export type adminAllocateSalesOrderResponse200 = {
  data: SalesOrderDetail
  status: 200
}

export type adminAllocateSalesOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminAllocateSalesOrderResponseSuccess = (adminAllocateSalesOrderResponse200) & {
  headers: Headers;
};
export type adminAllocateSalesOrderResponseError = (adminAllocateSalesOrderResponse422) & {
  headers: Headers;
};

export type adminAllocateSalesOrderResponse = (adminAllocateSalesOrderResponseSuccess | adminAllocateSalesOrderResponseError)

export const getAdminAllocateSalesOrderUrl = (orderUuid: string,) => {




  return `/api/v1/admin/sales/orders/${orderUuid}/allocate`
}

/**
 * @summary Allocate Sales Order
 */
export const adminAllocateSalesOrder = async (orderUuid: string, options?: RequestInit): Promise<adminAllocateSalesOrderResponse> => {

  return mutator<adminAllocateSalesOrderResponse>(getAdminAllocateSalesOrderUrl(orderUuid),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminAllocateSalesOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAllocateSalesOrder>>, TError,{orderUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminAllocateSalesOrder>>, TError,{orderUuid: string}, TContext> => {

const mutationKey = ['adminAllocateSalesOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminAllocateSalesOrder>>, {orderUuid: string}> = (props) => {
          const {orderUuid} = props ?? {};

          return  adminAllocateSalesOrder(orderUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminAllocateSalesOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminAllocateSalesOrder>>>

    export type AdminAllocateSalesOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Allocate Sales Order
 */
export const useAdminAllocateSalesOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAllocateSalesOrder>>, TError,{orderUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminAllocateSalesOrder>>,
        TError,
        {orderUuid: string},
        TContext
      > => {
      return useMutation(getAdminAllocateSalesOrderMutationOptions(options), queryClient);
    }
    export type adminDispatchSalesOrderResponse200 = {
  data: SalesOrderDetail
  status: 200
}

export type adminDispatchSalesOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminDispatchSalesOrderResponseSuccess = (adminDispatchSalesOrderResponse200) & {
  headers: Headers;
};
export type adminDispatchSalesOrderResponseError = (adminDispatchSalesOrderResponse422) & {
  headers: Headers;
};

export type adminDispatchSalesOrderResponse = (adminDispatchSalesOrderResponseSuccess | adminDispatchSalesOrderResponseError)

export const getAdminDispatchSalesOrderUrl = (orderUuid: string,) => {




  return `/api/v1/admin/sales/orders/${orderUuid}/dispatch`
}

/**
 * @summary Dispatch Sales Order
 */
export const adminDispatchSalesOrder = async (orderUuid: string,
    dispatchOrderRequest: DispatchOrderRequest, options?: RequestInit): Promise<adminDispatchSalesOrderResponse> => {

  return mutator<adminDispatchSalesOrderResponse>(getAdminDispatchSalesOrderUrl(orderUuid),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(dispatchOrderRequest)
  }
);}




export const getAdminDispatchSalesOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDispatchSalesOrder>>, TError,{orderUuid: string;data: BodyType<DispatchOrderRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminDispatchSalesOrder>>, TError,{orderUuid: string;data: BodyType<DispatchOrderRequest>}, TContext> => {

const mutationKey = ['adminDispatchSalesOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminDispatchSalesOrder>>, {orderUuid: string;data: BodyType<DispatchOrderRequest>}> = (props) => {
          const {orderUuid,data} = props ?? {};

          return  adminDispatchSalesOrder(orderUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminDispatchSalesOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminDispatchSalesOrder>>>
    export type AdminDispatchSalesOrderMutationBody = BodyType<DispatchOrderRequest>
    export type AdminDispatchSalesOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Dispatch Sales Order
 */
export const useAdminDispatchSalesOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDispatchSalesOrder>>, TError,{orderUuid: string;data: BodyType<DispatchOrderRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminDispatchSalesOrder>>,
        TError,
        {orderUuid: string;data: BodyType<DispatchOrderRequest>},
        TContext
      > => {
      return useMutation(getAdminDispatchSalesOrderMutationOptions(options), queryClient);
    }
    export type adminConfirmSalesOrderResponse200 = {
  data: SalesOrderDetail
  status: 200
}

export type adminConfirmSalesOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminConfirmSalesOrderResponseSuccess = (adminConfirmSalesOrderResponse200) & {
  headers: Headers;
};
export type adminConfirmSalesOrderResponseError = (adminConfirmSalesOrderResponse422) & {
  headers: Headers;
};

export type adminConfirmSalesOrderResponse = (adminConfirmSalesOrderResponseSuccess | adminConfirmSalesOrderResponseError)

export const getAdminConfirmSalesOrderUrl = (orderUuid: string,) => {




  return `/api/v1/admin/sales/orders/${orderUuid}/confirm`
}

/**
 * @summary Confirm Sales Order
 */
export const adminConfirmSalesOrder = async (orderUuid: string, options?: RequestInit): Promise<adminConfirmSalesOrderResponse> => {

  return mutator<adminConfirmSalesOrderResponse>(getAdminConfirmSalesOrderUrl(orderUuid),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminConfirmSalesOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminConfirmSalesOrder>>, TError,{orderUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminConfirmSalesOrder>>, TError,{orderUuid: string}, TContext> => {

const mutationKey = ['adminConfirmSalesOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminConfirmSalesOrder>>, {orderUuid: string}> = (props) => {
          const {orderUuid} = props ?? {};

          return  adminConfirmSalesOrder(orderUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminConfirmSalesOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminConfirmSalesOrder>>>

    export type AdminConfirmSalesOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Confirm Sales Order
 */
export const useAdminConfirmSalesOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminConfirmSalesOrder>>, TError,{orderUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminConfirmSalesOrder>>,
        TError,
        {orderUuid: string},
        TContext
      > => {
      return useMutation(getAdminConfirmSalesOrderMutationOptions(options), queryClient);
    }
    export type adminCancelSalesOrderResponse200 = {
  data: SalesOrderDetail
  status: 200
}

export type adminCancelSalesOrderResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminCancelSalesOrderResponseSuccess = (adminCancelSalesOrderResponse200) & {
  headers: Headers;
};
export type adminCancelSalesOrderResponseError = (adminCancelSalesOrderResponse422) & {
  headers: Headers;
};

export type adminCancelSalesOrderResponse = (adminCancelSalesOrderResponseSuccess | adminCancelSalesOrderResponseError)

export const getAdminCancelSalesOrderUrl = (orderUuid: string,) => {




  return `/api/v1/admin/sales/orders/${orderUuid}/cancel`
}

/**
 * @summary Cancel Sales Order
 */
export const adminCancelSalesOrder = async (orderUuid: string,
    cancelOrderInNull?: CancelOrderIn | null, options?: RequestInit): Promise<adminCancelSalesOrderResponse> => {

  return mutator<adminCancelSalesOrderResponse>(getAdminCancelSalesOrderUrl(orderUuid),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(cancelOrderInNull)
  }
);}




export const getAdminCancelSalesOrderMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCancelSalesOrder>>, TError,{orderUuid: string;data?: BodyType<CancelOrderIn | null>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCancelSalesOrder>>, TError,{orderUuid: string;data?: BodyType<CancelOrderIn | null>}, TContext> => {

const mutationKey = ['adminCancelSalesOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCancelSalesOrder>>, {orderUuid: string;data?: BodyType<CancelOrderIn | null>}> = (props) => {
          const {orderUuid,data} = props ?? {};

          return  adminCancelSalesOrder(orderUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminCancelSalesOrderMutationResult = NonNullable<Awaited<ReturnType<typeof adminCancelSalesOrder>>>
    export type AdminCancelSalesOrderMutationBody = BodyType<CancelOrderIn | null> | undefined
    export type AdminCancelSalesOrderMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Cancel Sales Order
 */
export const useAdminCancelSalesOrder = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCancelSalesOrder>>, TError,{orderUuid: string;data?: BodyType<CancelOrderIn | null>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCancelSalesOrder>>,
        TError,
        {orderUuid: string;data?: BodyType<CancelOrderIn | null>},
        TContext
      > => {
      return useMutation(getAdminCancelSalesOrderMutationOptions(options), queryClient);
    }
    export type adminAddSalesOrderFollowupResponse200 = {
  data: SalesOrderDetail
  status: 200
}

export type adminAddSalesOrderFollowupResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminAddSalesOrderFollowupResponseSuccess = (adminAddSalesOrderFollowupResponse200) & {
  headers: Headers;
};
export type adminAddSalesOrderFollowupResponseError = (adminAddSalesOrderFollowupResponse422) & {
  headers: Headers;
};

export type adminAddSalesOrderFollowupResponse = (adminAddSalesOrderFollowupResponseSuccess | adminAddSalesOrderFollowupResponseError)

export const getAdminAddSalesOrderFollowupUrl = (orderUuid: string,) => {




  return `/api/v1/admin/sales/orders/${orderUuid}/followups`
}

/**
 * @summary Add Sales Order Followup
 */
export const adminAddSalesOrderFollowup = async (orderUuid: string,
    addSoFollowupRequest: AddSoFollowupRequest, options?: RequestInit): Promise<adminAddSalesOrderFollowupResponse> => {

  return mutator<adminAddSalesOrderFollowupResponse>(getAdminAddSalesOrderFollowupUrl(orderUuid),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addSoFollowupRequest)
  }
);}




export const getAdminAddSalesOrderFollowupMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAddSalesOrderFollowup>>, TError,{orderUuid: string;data: BodyType<AddSoFollowupRequest>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminAddSalesOrderFollowup>>, TError,{orderUuid: string;data: BodyType<AddSoFollowupRequest>}, TContext> => {

const mutationKey = ['adminAddSalesOrderFollowup'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminAddSalesOrderFollowup>>, {orderUuid: string;data: BodyType<AddSoFollowupRequest>}> = (props) => {
          const {orderUuid,data} = props ?? {};

          return  adminAddSalesOrderFollowup(orderUuid,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminAddSalesOrderFollowupMutationResult = NonNullable<Awaited<ReturnType<typeof adminAddSalesOrderFollowup>>>
    export type AdminAddSalesOrderFollowupMutationBody = BodyType<AddSoFollowupRequest>
    export type AdminAddSalesOrderFollowupMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Add Sales Order Followup
 */
export const useAdminAddSalesOrderFollowup = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAddSalesOrderFollowup>>, TError,{orderUuid: string;data: BodyType<AddSoFollowupRequest>}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminAddSalesOrderFollowup>>,
        TError,
        {orderUuid: string;data: BodyType<AddSoFollowupRequest>},
        TContext
      > => {
      return useMutation(getAdminAddSalesOrderFollowupMutationOptions(options), queryClient);
    }
    export type adminChaseSalesOrderPaymentResponse200 = {
  data: SalesOrderDetail
  status: 200
}

export type adminChaseSalesOrderPaymentResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type adminChaseSalesOrderPaymentResponseSuccess = (adminChaseSalesOrderPaymentResponse200) & {
  headers: Headers;
};
export type adminChaseSalesOrderPaymentResponseError = (adminChaseSalesOrderPaymentResponse422) & {
  headers: Headers;
};

export type adminChaseSalesOrderPaymentResponse = (adminChaseSalesOrderPaymentResponseSuccess | adminChaseSalesOrderPaymentResponseError)

export const getAdminChaseSalesOrderPaymentUrl = (orderUuid: string,) => {




  return `/api/v1/admin/sales/orders/${orderUuid}/chase-payment`
}

/**
 * @summary Chase Sales Order Payment
 */
export const adminChaseSalesOrderPayment = async (orderUuid: string, options?: RequestInit): Promise<adminChaseSalesOrderPaymentResponse> => {

  return mutator<adminChaseSalesOrderPaymentResponse>(getAdminChaseSalesOrderPaymentUrl(orderUuid),
  {
    ...options,
    method: 'POST'


  }
);}




export const getAdminChaseSalesOrderPaymentMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminChaseSalesOrderPayment>>, TError,{orderUuid: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminChaseSalesOrderPayment>>, TError,{orderUuid: string}, TContext> => {

const mutationKey = ['adminChaseSalesOrderPayment'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminChaseSalesOrderPayment>>, {orderUuid: string}> = (props) => {
          const {orderUuid} = props ?? {};

          return  adminChaseSalesOrderPayment(orderUuid,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdminChaseSalesOrderPaymentMutationResult = NonNullable<Awaited<ReturnType<typeof adminChaseSalesOrderPayment>>>

    export type AdminChaseSalesOrderPaymentMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Chase Sales Order Payment
 */
export const useAdminChaseSalesOrderPayment = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminChaseSalesOrderPayment>>, TError,{orderUuid: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminChaseSalesOrderPayment>>,
        TError,
        {orderUuid: string},
        TContext
      > => {
      return useMutation(getAdminChaseSalesOrderPaymentMutationOptions(options), queryClient);
    }
