/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { BodyUploadAudioLanguage } from './bodyUploadAudioLanguage';

export interface BodyUploadAudio {
  file: Blob;
  language?: BodyUploadAudioLanguage;
  speaker?: string;
}
