/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type BodyUploadAudioLanguage = typeof BodyUploadAudioLanguage[keyof typeof BodyUploadAudioLanguage];


export const BodyUploadAudioLanguage = {
  auto: 'auto',
  hi: 'hi',
  mr: 'mr',
  en: 'en',
} as const;
