/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { ExaminationInFindings } from './examinationInFindings';

export interface ExaminationIn {
  examiner: string;
  findings: ExaminationInFindings;
}
