/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type PatientOutPreferredLanguage = typeof PatientOutPreferredLanguage[keyof typeof PatientOutPreferredLanguage];


export const PatientOutPreferredLanguage = {
  hi: 'hi',
  mr: 'mr',
  en: 'en',
} as const;
