/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type PatientOutStatus = typeof PatientOutStatus[keyof typeof PatientOutStatus];


export const PatientOutStatus = {
  active: 'active',
  inactive: 'inactive',
} as const;
