/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { PatientInBloodGroup } from './patientInBloodGroup';
import type { PatientInGender } from './patientInGender';
import type { PatientInPrakriti } from './patientInPrakriti';
import type { PatientInPreferredLanguage } from './patientInPreferredLanguage';
import type { PatientInStatus } from './patientInStatus';

export interface PatientIn {
  /**
     * @minLength 1
     * @maxLength 120
     */
  full_name: string;
  date_of_birth: string;
  gender: PatientInGender;
  /** @pattern ^\d{10}$ */
  phone: string;
  email?: string | null;
  preferred_language: PatientInPreferredLanguage;
  address_line?: string | null;
  city?: string | null;
  state?: string | null;
  pin_code?: string | null;
  prakriti?: PatientInPrakriti;
  chief_complaint?: string | null;
  allergies?: string[];
  conditions?: string[];
  medications?: string[];
  blood_group?: PatientInBloodGroup;
  status?: PatientInStatus;
  notes?: string | null;
}
