/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */
import type { PatientOutBloodGroup } from './patientOutBloodGroup';
import type { PatientOutGender } from './patientOutGender';
import type { PatientOutPrakriti } from './patientOutPrakriti';
import type { PatientOutPreferredLanguage } from './patientOutPreferredLanguage';
import type { PatientOutStatus } from './patientOutStatus';

export interface PatientOut {
  /**
     * @minLength 1
     * @maxLength 120
     */
  full_name: string;
  date_of_birth: string;
  gender: PatientOutGender;
  /** @pattern ^\d{10}$ */
  phone: string;
  email?: string | null;
  preferred_language: PatientOutPreferredLanguage;
  address_line?: string | null;
  city?: string | null;
  state?: string | null;
  pin_code?: string | null;
  prakriti?: PatientOutPrakriti;
  chief_complaint?: string | null;
  allergies?: string[];
  conditions?: string[];
  medications?: string[];
  blood_group?: PatientOutBloodGroup;
  status?: PatientOutStatus;
  notes?: string | null;
  id: string;
  registered_on: string;
  last_visit: string | null;
}
