/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type PatientInGender = typeof PatientInGender[keyof typeof PatientInGender];


export const PatientInGender = {
  male: 'male',
  female: 'female',
  other: 'other',
} as const;
