/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type PatientOutBloodGroup = typeof PatientOutBloodGroup[keyof typeof PatientOutBloodGroup];


export const PatientOutBloodGroup = {
  'A+': 'A+',
  'A-': 'A-',
  'B+': 'B+',
  'B-': 'B-',
  'AB+': 'AB+',
  'AB-': 'AB-',
  'O+': 'O+',
  'O-': 'O-',
  unknown: 'unknown',
} as const;
