/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type PatientOutPrakriti = typeof PatientOutPrakriti[keyof typeof PatientOutPrakriti];


export const PatientOutPrakriti = {
  vata: 'vata',
  pitta: 'pitta',
  kapha: 'kapha',
  'vata-pitta': 'vata-pitta',
  'pitta-kapha': 'pitta-kapha',
  'vata-kapha': 'vata-kapha',
  tridosha: 'tridosha',
  unknown: 'unknown',
} as const;
