/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type PatientInStatus = typeof PatientInStatus[keyof typeof PatientInStatus];


export const PatientInStatus = {
  active: 'active',
  inactive: 'inactive',
} as const;
