/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type PatientInBloodGroup = typeof PatientInBloodGroup[keyof typeof PatientInBloodGroup];


export const PatientInBloodGroup = {
  'A+': 'A+',
  'A-': 'A-',
  'B+': 'B+',
  'B-': 'B-',
  'AB+': 'AB+',
  'AB-': 'AB-',
  'O+': 'O+',
  'O-': 'O-',
  unknown: 'unknown',
} as const;
