/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type PatientInPreferredLanguage = typeof PatientInPreferredLanguage[keyof typeof PatientInPreferredLanguage];


export const PatientInPreferredLanguage = {
  hi: 'hi',
  mr: 'mr',
  en: 'en',
} as const;
