/**
 * Generated by orval — do not edit.
 * Regenerate via: bun run sdk:gen
 */

export type PatientOutGender = typeof PatientOutGender[keyof typeof PatientOutGender];


export const PatientOutGender = {
  male: 'male',
  female: 'female',
  other: 'other',
} as const;
